### ISSUE TITLE
Validation of desktop application id not in sync with spec

### ISSUE THREAD

**Issue by jnumm** [ximion/appstream#100]
Commit bb15c561 added the following to the id paragraph of docs/sources/metainfo/desktopapp.xml:
> the <filename>.desktop</filename> suffix of the filename may be omitted

However, the validator won't allow it: https://github.com/ximion/appstream/blob/master/src/as-validator.c#L557.

**Comment by ximion** [comment]
This is resolved now, thanks for noticing the issue and reporting it!
