### ISSUE TITLE
Add proprietary-license URL type?

### ISSUE THREAD

**Issue by jbicha** [ximion/appstream#107]
I wrote an appstream file for Steam. I added `<project_license>LicenseRef-proprietary</project_license>` but I'd like to point to the actual license too.

What do you think about adding a `proprietary-license` URL type? GNOME Software could then use that URL to override the default `License Proprietary > More information` popup link.

On the other hand, it doesn't have to be a URL if there was a way I could include the license text directly.

**Comment by hughsie** [comment]
I think the idea here was to use LicenseRef-free=http://some-url.com -- does that work in gnome-software?

**Comment by jbicha** [comment]
Ok, I [see that should work](https://git.gnome.org/browse/gnome-software/tree/src/gs-details-page.c#n1934) for Free Software, but what about Proprietary Software?

The GNOME Software solution is nice, but maybe this should really be done officially in appstream itself.

If there's enough of a demand for custom Free licenses, then maybe my proposed URL type could be `custom-license` with a note in the documentation that it's strongly discouraged for Free Software to use custom licenses.

**Comment by hughsie** [comment]
I think providing yet another way to specify a license is going to make it confusing for free software. I'd certainly accept a patch to add support for `LicenseRef-Proprietary=` making the URL a hyperlink in GNOME Software.

**Comment by ximion** [comment]
@hughsie Looks like SPDX doesn't have an explicit solution for this... But `LicenseRef-Proprietary=` would make sense to me.

Including the license text directly or having some kind of directive to include an external `COPYING` file into the data is opening a whole new can of worms, which I would like to avoid at least for now.

**Comment by cassidyjames** [comment]
For what it's worth, we're using the `LicenseRef-proprietary=url` in the store for Pop!_OS, as we saw a few FlatHub apps had picked up that convention.

https://github.com/flathub/com.spotify.Client/blob/bedf00b58c45208ffdb21c45475e4944a5e3e1ea/com.spotify.Client.appdata.xml#L8

https://github.com/flathub/com.visualstudio.code/blob/d7c9ff7a01a8033d4fb3be1302a8266ed7f83b0d/com.visualstudio.code.appdata.xml#L5
