### ISSUE TITLE
Appstream-qt (Appstream::Component) is missing setters

### ISSUE THREAD

**Issue by grulja** [ximion/appstream#110]
One cannot create custom Appstream::Component, e.g when manually parsing .flatpakref file where you can get homepage, title, description, comment, icon and so on. If you want to transform this into Appstream::Component you have to first use AsComponent (glib one), fill this with data and then construct new Appstream::Component and passing that AsComponent to the constructor.

**Comment by ximion** [comment]
PRs welcome for this ;-)
