### ISSUE TITLE
Glib errors when refreshing cache after 0.11 update

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream#112]
The first time the cache is refreshed after updating to 0.11 gives lots of errors like

(appstreamcli:6240): GLib-CRITICAL **: g_variant_get_type: assertion 'value != NULL' failed

(appstreamcli:6240): GLib-CRITICAL **: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(appstreamcli:6240): GLib-CRITICAL **: g_variant_get_int32: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT32)' failed

It only happens the first time, any subsequent cache refresh finishes without errors. The refresh seems to finish correctly despite the errors, but it certainly looks scary (and I'm already getting reports about it downstream)

**Comment by ximion** [comment]
Yeah, it's weird that this happens - I think the safest thing to prevent this from happening is to just bump the cache revision number everytime anything is changed on the serialization, as GVariant doesn't seem to cope with most changes.

An easy way to work around this issue and a thing we do in Debian anyway is to run "appstreamcli refresh --force" in the packages post-install hook.
That ensures the cache is always recent (and also saves a bit of time next time we run an apt update in Debian's case)-

**Comment by antonio-rojas** [comment]
We do run "appstreamcli refresh --force" post-install, that's how this issue came up. Users are seeing this scary message when updating their systems.

So I take it is safe to ignore it?

**Comment by ximion** [comment]
Yes, you can ignore it, but thanks for reporting it! There definitely is a bug here, I will look into it when I'm back home (for starters, the cache shouldn't be loaded when refreshing it).

**Comment by ximion** [comment]
This is fixed now as per https://github.com/ximion/appstream/commit/9fa293ab4d3ffd91dd133f331b7e24e9cfa5f80a - with future release I plan to improve the cache a bit more (mainly increase its performance a little).
