### ISSUE TITLE
Is the <releases/> tag really required?

### ISSUE THREAD

**Issue by elvisangelaccio** [ximion/appstream#113]
From the spec:

> ⁠2.1.3. XML Specification
The XML for a generic component definition starts with a <component> tag as the root element. The <component> element must at least have an id, name and releases tag

but `appstreamcli validate` does not complain if the `releases` tag is missing. In fact, the tag is not used at all in KDE applications. Bug in the spec or bug in the validator?

**Comment by hughsie** [comment]
Quite a few XFCE and GNOME apps use releases in the AppData, and for packaging formats like flatpak it's the only way we can get any kind of release notes.

**Comment by ximion** [comment]
@elvisangelaccio This is actually a typo, the component must have an id, name and *summary* tag to be valid. I'll fix this tomorrow.
Regardless though, as @hughsie said, a releases tag is a useful thing if it is kept up to date, so you might as well add one :-)
