### ISSUE TITLE
No icons when loading from the cache

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#124]
Since a couple of weeks I've been getting only the icons for the components that have stock icons, those that have it bundled aren't being offered.

I've been investigating a bit and my distro's icons are part of the xml and they're properly parsed when we call `appstreamcli refresh` but then when it's loaded back into the pool it doesn't list them.

**Comment by ximion** [comment]
Which version of AppStream are you using? I fixed a bug that sounds exactly like yours a couple of days ago (https://github.com/ximion/appstream/commit/a83f1f55aa98deaeb6b0ba786027b9ff42712081), but that particular issue was only introduced in Git master, and never made it into a release.

**Comment by aleixpol** [comment]
I was testing on master, just switched to the `APPSTREAM_0_11_2` and I have the same problem.
In fact I don't see much differences between the tag and master.

**Comment by ximion** [comment]
Run a forced update please (`appstreamcli refresh --force --verbose`) and paste the log somewhere.
Also check if the icon files are present.
This bug is a rather strong indication for AS not finding the cached icons for some reason, just like with the bug I fixed in master.

**Comment by aleixpol** [comment]
```
** (appstreamcli:14437): DEBUG: Added /usr/share/app-info/xmls to metadata search path.
** (appstreamcli:14437): DEBUG: Added /var/cache/app-info/xmls to metadata search path.
** (appstreamcli:14437): DEBUG: Data did not change, no cache refresh needed.
** (appstreamcli:14437): DEBUG: Forcing refresh anyway.
** (appstreamcli:14437): DEBUG: Refreshing AppStream cache
** (appstreamcli:14437): DEBUG: Searching for data in: /usr/share/app-info/xmls
** (appstreamcli:14437): DEBUG: Searching for data in: /var/cache/app-info/xmls
** (appstreamcli:14437): DEBUG: Reading: /usr/share/app-info/xmls/org.freedesktop.fwupd.xml
** (appstreamcli:14437): DEBUG: Reading: /usr/share/app-info/xmls/extra.xml.gz
** (appstreamcli:14437): DEBUG: Reading: /usr/share/app-info/xmls/core.xml.gz
** (appstreamcli:14437): DEBUG: Reading: /usr/share/app-info/xmls/community.xml.gz
** (appstreamcli:14437): DEBUG: Metadata ignored: Detected colliding ids: system/os/package/libreoffice-writer.desktop was already added with the same priority.
** (appstreamcli:14437): DEBUG: Metadata ignored: Detected colliding ids: system/os/package/libreoffice-calc.desktop was already added with the same priority.
** (appstreamcli:14437): DEBUG: Metadata ignored: Detected colliding ids: system/os/package/libreoffice-base.desktop was already added with the same priority.
** (appstreamcli:14437): DEBUG: Metadata ignored: Detected colliding ids: system/os/package/libreoffice-impress.desktop was already added with the same priority.
** (appstreamcli:14437): DEBUG: Metadata ignored: Detected colliding ids: system/os/package/libreoffice-draw.desktop was already added with the same priority.
** (appstreamcli:14437): DEBUG: Metadata ignored: Detected colliding ids: system/os/package/yabause.desktop was already added with the same priority.
** (appstreamcli:14437): DEBUG: system/os/package/vim-latex extends system/os/package/gvim.desktop, but system/os/package/gvim.desktop was not found.
** (appstreamcli:14437): DEBUG: system/os/package/zathura-pdf-poppler.desktop extends system/os/package/zathura.desktop, but system/os/package/zathura.desktop was not found.
** (appstreamcli:14437): DEBUG: system/os/package/nautilus-sendto extends system/os/package/nautilus.desktop, but system/os/package/nautilus.desktop was not found.
** (appstreamcli:14437): DEBUG: Stemming language is: en
```

**Comment by ximion** [comment]
Is that the whole log? Because the log doesn't look complete...
I'll fetch the Fedora metadata and try a local cache rebuild with that exact data to try to reproduce the issue.

**Comment by aleixpol** [comment]
That's on Arch Linux.

**Comment by ximion** [comment]
This should be working with the patch linked above - there was indeed an error in how/where the document context was set.

Actually, this issue is rather serious, so I might do another release rather soon (at Debconf, I guess, time is limited) that includes this patch.
Please check if this fixes the bug for you!

**Comment by aleixpol** [comment]
Yes, sorry for reopening.
Fix confirmed. Had to refresh the db.
