### ISSUE TITLE
AppStream information to prospect contributors

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#125]
One thing I'd like to look into is implementing a series of features that should help users become contributors. I thought that a good place where to include the extra information would be AppStream

What I suggest is to extend the `<url/>` tag with two aditional types: `contribute` and `vcs` (i.e. version control system, a different tag could help. `contribute` would link to a main contribute page if available and `vcs` would actually link to the git repository (or similar).

For example, for appstream itself it would be:
```
  <url type="homepage">https://www.freedesktop.org/wiki/Distributions/AppStream/</url>
  <url type="vcs">https://github.com/ximion/appstream.git</url>
  <url type="contribute">https://github.com/ximion/appstream/</url>
```

The end goal is that the system should have all the information required to lead the user from an application to its sources and the community that manages them.

**Comment by ximion** [comment]
@hughsie What do you think?
IMO having a "contribute" url type makes sense, having a "vcs" tag though is less helpful. Nobody would fork the project directly from the software center and hack on it, and the contribution page would for sure link to the VCS somewhere.
A contributor landing page would have some value though (although I am not sure how this would look like in the UI - if a project has set all the URL types, we would have quite a pile of links.) Also, a "contribute" url would have quite a big overlap with the existing "translate" url type.

**Comment by aleixpol** [comment]
FWIW I never said this was meant to be used from a software center, but rather an IDE or even the shell itself.

**Comment by hughsie** [comment]
I don't think it hurts to add, but I too am a bit confused exactly where it's going to be shown.

**Comment by aleixpol** [comment]
I need to run it by our design team still but the idea is that if KDevelop (or any IDE if someone else is interested) we get to have.

Here's few ideas for further context:
* In KDevelop we have a view for fetching projects from different sources. We have a KDE and a GitHub plugin, we could also have an AppStream one where the git URI comes from this metadata in discussion.
![spectacle ud1066](https://user-images.githubusercontent.com/1282478/29149499-d501a2ba-7d74-11e7-9535-a9cf7d6f8a08.png)

* We could also have a "Contribute..." button in the shell provided the information is offered and an IDE installed on the system. Another place could be the window decoration (which for us is shared).
![spectacle x10783](https://user-images.githubusercontent.com/1282478/29074787-cba90610-7c50-11e7-98c6-619e6a321389.png)

**Comment by basak** [comment]
> I don't think it hurts to add, but I too am a bit confused exactly where it's going to be shown.

In Ubuntu, I'm working on a tool that makes it easy to clone, patch and rebuild distribution source packages using git. Being able to automatically add an "upstream" remote would be really useful (for example to easily cherry-pick an upstream patch into a distribution release package version). This would need the upstream remote URL to be in metadata somewhere, and AppStream seems like the obvious place to put it.

Note that I would need a useable git URL, which isn't necessarily the same as a user-browseable one for all upstreams. In Debian packaging, we have `Vcs:` and `Vcs-Browser`. The former is something you can clone; the latter is something that works in a browser. So please specify both use cases so that we can reliably automate.

**Comment by cassidyjames** [comment]
I really like a "Contribute" URL as that seems handy to expose to users, especially through a software center. A way to point to a machine-friendly code repository itself seems interesting, but I think these should be separate considerations.

**Comment by btkostner** [comment]
Thinking about how elementary plans to deploy a flatpak repository, a vcs link would be useful for reverse lookup. Say someone gives https://github.com/danrabbit/harvey, it would be nice to parse our current appstream file to find the latest details of the application.

We could use a database to store all of this stuff, but it would be nicer and more robust by just parsing the already existing appstream data.

**Comment by Alexander-Wilms** [comment]
Since the AppStream specification now supports a variety of URL types, this issue can be marked as completed, right?

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

**Comment by basak** [comment]
Thanks. This probably works for nearly everyone but unfortunately not for [my use case that I detailed above](https://github.com/ximion/appstream/issues/125#issuecomment-747816398). I see a "vcs-browser" URL type, but not one that could be expected to be cloned by git.

Up to you if this should be tracked here or in a new issue though.

**Comment by ximion** [comment]
That should definitely be a new issue, but I am not sure if we should support things that are *that* developer-centric... I also think this has come up before. But well, let's see!
