### ISSUE TITLE
vala bindings reference non-existent header

### ISSUE THREAD

**Issue by rdieter** [ximion/appstream#136]
In recent releases (maybe since meson buildsystem introduced?), there's an error in the vala bindings:

cheader_filename references a non-existent file name: AppStream-1.0.h (instead of appstream.h ?)

**Comment by ximion** [comment]
Indeed! Previously, the header name was passed explicitly, now it seems to be inferred somehow, which is wrong.
Meson doesn't seem to have an option to set this yet, I'll have to look into this.

**Comment by decathorpe** [comment]
Thanks for filing the issue, I didn't yet have the time to report the bug myself ... I only noticed that the new appstream version broke builds of appcenter and slingshot on fedora, and I guess elementaryOS will hit the same problem eventually.

**Comment by ximion** [comment]
I need to submit a patch to Meson to allow setting `--c-include` on GIR generation to fix this properly. Until then, I have committed a workaround.

**Comment by rdieter** [comment]
Thanks, confirmed workaround works as advertised
