### ISSUE TITLE
Poor icon quality for big icons

### ISSUE THREAD

**Issue by inad9300** [ximion/appstream#137]
I'm not sure how this relates to AppStream, project from which I just heard for the first time a minute ago, but when trying to display icons in a relatively big size, they get quite blurry.

@danrabbit mentioned in https://github.com/elementary/appcenter/issues/279 that this was a problem and work-in-progress in AppStream, but I see not issue related to it, so I wanted to make sure that this is being taken care of by opening this one.

Thanks.

**Comment by danrabbit** [comment]
afaict this is already fixed in AppStream. This now needs work in AppCenter Dashboard and in elementary OS default settings.

**Comment by btkostner** [comment]
Also already reported in https://github.com/ximion/appstream/issues/21

**Comment by inad9300** [comment]
I had seen #21, but didn't think was related to this case. The issue mentions "DPI", which I assume refers to HiDPI, but I'm experiencing the aforementioned problems on a 15-inch screen with a 1920x1080 resolution. To my eyes, the issue just seems to be that a small icon is being resized inappropriately, and that a bigger icon would already look good.

**Comment by ximion** [comment]
Blurry icons can have multiple causes:
 * The app does not provide an icon that is big enough
 * The app does not use XDG icon directories or does not use them properly
 * 128x128px icons were not downloaded (check e.g. `/var/lib/app-info/icons/`)
 * The software center does not pick the right icon
 * Bug in the metadata generator icon finding logic (very unlikely, unless you found a weird corner case here - that particular code has been tested and revised quite often so far)

In any case, not an AppStream bug. To find out what happened, answering whether all icons are blurry or just a few, which icons are blurry in case it's not all and whether there actually are 128x128px icons in `/var/(lib|cache)/app-info/icons/` or `/usr/share/app-info/icons` is helpful.

**Comment by inad9300** [comment]
All the icons are blurry, I could not see one that is not. From the directories you mentioned, only `/var/lib/app-info/icons` exists. It contains many folders starting with `ubuntu-xenial-`, and a folder named `appcenter-xenial-main`. All of them contain one and only one folder inside them, named `64x64`. Maybe a piece of information interesting for you, @danrabbit?
