### ISSUE TITLE
Component::iconUrl disfunctional on AppStreamQt

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#14]
This is the current code to fetch the iconUrl:
```
// Icon urls
    QString concatIconUrlStrings = value(document, XapianValues::ICON_URLS);
    QStringList iconUrlStrings = concatIconUrlStrings.split('\n',QString::SkipEmptyParts);
    if(iconUrlStrings.size() %2 == 0) {
        for(int i = 0; i < iconUrlStrings.size(); i=i+2) {
            QString sizeStr = iconUrlStrings.at(i);
            QUrl url = QUrl::fromUserInput(iconUrlStrings.at(i+1));
            QSize size = parseSizeString(sizeStr);
            component.addIconUrl(url, size);
        }
    } else {
        qCWarning(APPSTREAMQT_DB, "Bad icon-url strings for component: '%s' (%s)", qPrintable(id), qPrintable(concatIconUrlStrings));
    }
```

I suspect the format has changed internally and the code in Qt side isn't working anymore. Any pointers of how to fix it will be very welcome, in order to get a proper fix.

**Comment by aleixpol** [comment]
I see it's using `IconUrls::ParseFromString (str);` comes from `::google::protobuf::MessageLite`. Should we also depend on that on the Qt side?

**Comment by ximion** [comment]
Oh, damn - I just wanted to write that I ported the code to the new database layout, but it turns out I missed doing that...
Give me a second, fixing this is trivial (but breaking it is a pretty big regression)

**Comment by ximion** [comment]
Regarding Protobuf: This is already done, the library links against protobuf-lite.
Reason for using protobuf is much increased performance compared to string-comparisons and string-splitting, while preserving the advantages of Xapian (low memory consumption and fast full-text search with stemming).
I just overlooked iconUrls when adapting the Qt code.
