### ISSUE TITLE
new-template TYPE documentation missing

### ISSUE THREAD

**Issue by scop** [ximion/appstream#143]
The man page for new-template says:

> The first TYPE parameter is the name of an AppStream component type. For a complete list check out the documentation[2] or the help output of appstreamcli for this subcommand.

But `appstreamcli new-template --help` says nothing about types, and the referenced HTML documentation page doesn't contain a list either: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by ximion** [comment]
The page you link does list all the valid component types, it's probably not super obvious though.
Additionally, if you type a wrong component type, ascli will show you a list of all the values you can choose from.

Granted, this could be displayed in a nicer way, so the patch below displays all possible values when `--help` is passed to the `new-template` subcommand.
