### ISSUE TITLE
ERROR: can't resolve libraries to shared libraries: yaml

### ISSUE THREAD

**Issue by bdouxx** [ximion/appstream#146]
Hi

I have a problem to compil  from git.
Can you help me?

```
git clone https://github.com/ximion/appstream.git
cd appstream
mkdir build
cd build
meson ..
```
> The Meson build system
> Version: 0.43.0
> Source dir: /home/bdouxx/depots_git/appstream
> Build dir: /home/bdouxx/depots_git/appstream/build
> Build type: native build
> Project name: AppStream
> Native C compiler: cc (gcc 6.4.0)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Configuring config.h using configuration
> Found pkg-config: /usr/bin/pkg-config (0.29.2)
> Native dependency glib-2.0 found: YES 2.50.3
> Native dependency gobject-2.0 found: YES 2.50.3
> Native dependency gio-2.0 found: YES 2.50.3
> Native dependency gio-unix-2.0 found: YES 2.50.3
> Native dependency libxml-2.0 found: YES 2.9.4
> Native dependency yaml-0.1 found: YES 0.1.7
> Library stemmer found: YES
> Has header "libstemmer.h": YES
> Native dependency glib-2.0 found: YES 2.50.3
> WARNING: GLib compiled dependencies do not work reliably with 
> the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
> Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
> Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
> Native dependency gobject-introspection-1.0 found: YES 1.50.0
> Program xsltproc found: YES (/usr/bin/xsltproc)
> Program sh found: YES (/bin/sh)
> Build targets in project: 19
> Found ninja-1.8.2 at /usr/bin/ninja
> 

`ninja`

> [59/60] Generating AppStream-1.0.gir with a custom command.
> FAILED: src/AppStream-1.0.gir 
> /usr/bin/g-ir-scanner -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/lib64/libffi-3.2.1/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include --no-libtool --namespace=AppStream --nsversion=1.0 --warn-all --output src/AppStream-1.0.gir --c-include=appstream.h -I/home/bdouxx/depots_git/appstream/src/ -I/home/bdouxx/depots_git/appstream/build/src/ -I/usr/include -I/usr/include -I./src/.. -I../src/.. --filelist=/home/bdouxx/depots_git/appstream/build/src/appstream@sha/AppStream_1.0_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --symbol-prefix=as --identifier-prefix=As --pkg-export=appstream --cflags-begin -Werror=implicit-function-declaration -Wno-unused-parameter -DAS_COMPILATION -I/usr/include -I./src/.. -I../src/.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -pthread -I/usr/include/gio-unix-2.0/ --cflags-end -L/home/bdouxx/depots_git/appstream/build/src/ -lglib-2.0 -lxml2 -lyaml -lgobject-2.0 -lgio-2.0 -lstemmer -L/home/bdouxx/depots_git/appstream/build/src/ --library appstream
> ERROR: can't resolve libraries to shared libraries: yaml
> ninja: build stopped: subcommand failed.

```


ll /usr/lib64/libyaml*
lrwxrwxrwx 1 root root   18 27 oct.  00:05 /usr/lib64/libyaml-0.so.2 -> libyaml-0.so.2.0.5
-rwxr-xr-x 1 root root 123K 27 oct.  00:05 /usr/lib64/libyaml-0.so.2.0.5
lrwxrwxrwx 1 root root   18 27 oct.  00:05 /usr/lib64/libyaml.so -> libyaml-0.so.2.0.5
```

**Comment by ximion** [comment]
This is a bug in gobject-introspection in combination with Meson. You would need to update gobject-introspection to `>= 1.54` to make this work (unfortunately we can't easily check for versions of these binaries in Meson, although given this report I should really try to find a way).

If you can't update GIR to the bugfixed version and don't need introspection, you can also disable it with the respective flag (that's discouraged, but depending on what you want to do may work).
