### ISSUE TITLE
Leaks /etc/os-release fd to child processes

### ISSUE THREAD

**Issue by Vogtinator** [ximion/appstream#148]
This library is often loaded into application launchers. However, once as_distro_details_new is called, the fd never gets closed as O_CLOEXEC is not set as flag.
For instance, open a terminal from krunner and you'll see that fd 23 of /proc/self/fd is valid and points to /etc/os-release.

**Comment by ximion** [comment]
There is indeed a leak on the data input stream there (which I guess triggers this issue). Adjusting the flags might slo be a good idea.
