### ISSUE TITLE
Norwegian Bokmål uses incorrect language code

### ISSUE THREAD

**Issue by piotrdrag** [ximion/appstream#151]
It’s po/nb_NO.po now, and should be po/nb.po instead. I’d send a PR, but I don’t know how that would work with Weblate.

**Comment by ximion** [comment]
I don't know either, this has to be fixed in Weblate somehow, I guess - if the file is renamed in Git here, it will be added right back by Weblate as soon as someone touches it there.

**Comment by ximion** [comment]
Okay, I think I resolved this now, I hope nothing broke in the process :-)
Thanks for reporting the issue!
