### ISSUE TITLE
Validation complains about bugs.kde.org links

### ISSUE THREAD

**Issue by elvisangelaccio** [ximion/appstream#152]
To reproduce:

    git clone git://anongit.kde.org/ark.git
    appstreamcli validate ark/app/org.kde.ark.appdata.xml

It will print:

> W - org.kde.ark.appdata.xml:org.kde.ark.desktop:281
    Unable to reach remote location 
    'https://bugs.kde.org/enter_bug.cgi?format=guided&product=ark' - does it exist?

As you can see, the link does exist. This issue affects also other KDE apps btw.

**Comment by ximion** [comment]
This is because the KDE bug server isn't set up correctly to answer HEAD requests.
A workaround for this has already been added, see https://github.com/ximion/appstream/issues/145
