### ISSUE TITLE
FTBFS against meson-0.44.0 (or newer)

### ISSUE THREAD

**Issue by rdieter** [ximion/appstream#161]
Builds fine using meson-0.43, starting with meson-0.44.0 however, fails wrt po/ directory somewhere:

[3/5] /usr/bin/python3 /usr/bin/meson --internal msgfmthelper ../data/org.freedesktop.appstream.cli.metainfo.xml data/org.freedesktop.appstream.cli.metainfo.xml xml /home/rdieter/SCM/github.com/appstream/po --datadirs=/home/rdieter/SCM/github.com/appstream/data/
FAILED: data/org.freedesktop.appstream.cli.metainfo.xml 
/usr/bin/python3 /usr/bin/meson --internal msgfmthelper ../data/org.freedesktop.appstream.cli.metainfo.xml data/org.freedesktop.appstream.cli.metainfo.xml xml /home/rdieter/SCM/github.com/appstream/po --datadirs=/home/rdieter/SCM/github.com/appstream/data/
msgfmt: error while opening "/home/rdieter/SCM/github.com/appstream/po/zh_TW.po/noc.po/ncs.po/nca.po/nja.po/nsl.po/neu.po/npl.po/nen_GB.po/nfi.po/npt.po/nhu.po/nlt.po/nckb.po/nnl.po/nda.po/ngl.po/nko.po/nuk.po/ngd.po/nes.po/nar.po/nsr@latin.po/nnb_NO.po/nsk.po/nid.po/ntr.po/nit.po/nsv.po/nru.po/nfr.po/npt_BR.po/nde.po/nzh_CN.po/nsr.po" for reading: Not a directory

Or is this a meson bug/regression?

**Comment by ximion** [comment]
I am pretty sure this is a Meson regression, but I haven't had the time yet to debug the issue. The problem started to appear with Meson 0.44, all previous Meson versions are fine.
The issue is reported at Meson upstream as https://github.com/mesonbuild/meson/issues/2845

**Comment by ximion** [comment]
Hah! This is actually a bug in Meson as well as a bug in AppStream. The AppStream one is a bit more severe though.
Patch will happen in a minute.
