### ISSUE TITLE
Extend requirements to include HW specs

### ISSUE THREAD

**Issue by joaquimrocha** [ximion/appstream#163]
It would be very useful to have a way to specify some important HW requirements for apps. For example, in machines that have only 1GB of memory, it is very important to tell the user which games may not run very well in their machines. Hence, `memory` is a very important entity to be added.

I thought CPU could also be important, but as previously pointed out by @ximion , it may be difficult to express the different values that each CPU has. So maybe for now we just add the memory spec.

**Comment by ximion** [comment]
I potentially want this feature to be part of a more versatile system for AppStream components to express requirements on the system they are supposed to run on, which would also address a couple of other feature requests.

I will post a proposal for that soon to get some feedback. There is also always the option to make a specific tag to define hardware requirements, depending on the outcome the discussion (the more generic proposal would widen the scope of AppStream significantly, and I am not sure if we want that).

**Comment by ximion** [comment]
AppStream 0.12.0 contains a `recommends` as well as a `required` tag for components now, to set relations of the component to other stuff.
For the start, you can depend on memory size, kernel versions, modaliases and other components.
See the AsRelation class and the specification changes from 5bf623d0e0e70674922afcbb55d7176d6c7d65a7 (libappstream API additions in 6f789541ca733b110b95da4b2939b3f4be125000)

For the CPU dependencies, I don't know how to properly address those yet - but we can relatively easily add such a feature now.
