### ISSUE TITLE
Getting actual release information

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#164]
The documentation doesn't say so, but it would be interesting to ensure that the last of `as_component_get_releases()` is the currently shipped release.
If we expect a software center to sort them and figure it out, it should be explained in the documentation as well.

**Comment by ximion** [comment]
`as_component_get_releases` should actually sort the releases so the most recent one is at the top of the list.
I thought I implemented that, but from a quick look at the code it doesn't look like that feature is there. I'll add it.
