### ISSUE TITLE
cli: validation of urls fails by default when run offline

### ISSUE THREAD

**Issue by decathorpe** [ximion/appstream#174]
When running the validation tool with default settings without internet connection, it chokes on validation of URLs (of course). This shouldn't be a fatal error (except maybe when `--pedantic` or `--net` is passed?). For example, this default behaviour prevents running upstream tests (`meson test`, or `make check`, etc.) during fedora package builds.

**Comment by ximion** [comment]
Can you please specify what happens when you run the tool? Does it throw errors, or does it hang?

**Comment by decathorpe** [comment]
That's exactly my point: I can't pass the `--nonet` flag without having to modify upstream's test definitions (in CMake or meson) downstream - which defeats the whole point of wanting to run the original upstream tests ...
For example, running `meson test` just times out after 30 seconds while validating an .appdata.xml file - it looks like appstreamcli hangs without internet access.

**Comment by ximion** [comment]
I think this really should be addressed in some way in the respective upstream projects to pass `--nonet` if needed.
I can however, to make this easier to address for distributions and in case upstream always wants this enabled on their CI and doesn't want to provide a specific option to disable it, add an environment variable to disable network access as well.
