### ISSUE TITLE
Add "Terms & Conditions" link

### ISSUE THREAD

**Issue by cassidyjames** [ximion/appstream#188]
Some applications, i.e. Google Chrome, require the user to accept terms and conditions before using the software. While we have support for proprietary licenses, I think terms and conditions are separate and distinct.

**Comment by ximion** [comment]
This is in the works already: https://lists.freedesktop.org/archives/appstream/2018-April/000244.html

**Comment by ximion** [comment]
Implemented in AppStream 0.12.1, refer to https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-agreement
