### ISSUE TITLE
Supporting LibreOffice language packs

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#191]
Installing libreoffice in your own language is hard. There possibly is other projects with the same problem.

To install it properly the user needs to know to install a random package with his localisation data.

Would it be possible to expose this information through AppStream so software centers can suggest to install the language packs when available?

https://bugs.kde.org/show_bug.cgi?id=393878

**Comment by ximion** [comment]
Yes, that's not something we can do in AppStream though.

LibreOffice needs a metainfo file for its products, as well as one metainfo file per language pack of type `localization`. The format of which is described in the specification: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Localization.html

A software center can the just fetch the localization components that extend the installed software components on the system and install those automatically.

**Comment by ximion** [comment]
Yes, that's not something we can do in AppStream though.

LibreOffice needs a metainfo file for its products, as well as one metainfo file per language pack of type `localization`. The format of which is described in the specification: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Localization.html

A software center can the just fetch the localization components that extend the installed software components on the system and install those automatically.

This is really not something AppStream can help mit, it's rather up to LibreOffice and/or the respective distributors to provide the right metadata.

**Comment by aleixpol** [comment]
Correct, will reach out to LO.
