### ISSUE TITLE
Support empty content_rating tag

### ISSUE THREAD

**Issue by bilelmoussaoui** [ximion/appstream#202]
OARS now supports empty content_rating tag instead of having to write none for everything. The tests fail with appstreamcli and not with appstream-util.

**Comment by ximion** [comment]
Already fixed in the upcoming release via https://github.com/ximion/appstream/commit/774cb2902360c7d6bc50310ac59f5d9ad4381cb0

**Comment by bilelmoussaoui** [comment]
Thanks! Should have checked the recent commits before creating a new issue!
