### ISSUE TITLE
nesting description nodes allowed or not?

### ISSUE THREAD

**Issue by apachelogger** [ximion/appstream#210]
in a kde appdata we had the following:

```
  <description>
    <p>
      KCalc has everything you would expect from a scientific calculator, plus:
      <ul>
        <li>Trigonometric functions, logic operations and statistical calculations</li>
        <li>A results stack which enables convenient recall of previous calculation results</li>
        <li>Precision is user-definable</li>
        <li>The display allows cut and paste of numbers</li>
        <li>The display colors and font are configurable, aiding usability</li>
        <li>The use of key-bindings make it easy to use without a pointing device</li>
      </ul>
    </p>
  </description>
```

That is: `<ul>` nested inside `<p>`.

Appstream validated that fine via `appstreamcli validate` but people have raised concern over the correctness of this in particular WRT localization. The appstream documentation's examples seem to always close the `p` node before starting a list node. At the same time I cannot find any concrete information that would suggest this type of nesting is not allowed.

So, is it correct that `<p><ul/></p>` validates as correct?

If not I am guessing the validation should get refined a bit.

(background: https://markmail.org/thread/ewarmwjcojp43qqt)

**Comment by ximion** [comment]
> So, is it correct that <p><ul/></p> validates as correct?

Short answer: No. Nested listings in `<p/>` tags are not allowed, and the validator really should catch that.
I wonder how AppStream would actually parse such a tag... I guess currently the nested `<ul/>` would just silently be ignored.
I'll look into refining the validator check, unless someone is faster than me with a PR (might take me a few days to get to it).
Thank you for raising this issue!
