### ISSUE TITLE
Installing a package with invalid metadata breaks appstream system-wide.

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream#211]
After updating to 0.12.3 I noticed that 'appstreamcli search' no longer worked, it only returned "Some components are invalid. See debug output for details". The debug output showed the line "WARNING: Ignored component 'org.kde.choqok.desktop': The component is invalid.". And indeed after uninstalling choqok 'appstreamcli search' started working again without touching the appstream index.
I find it surprising that simply installing a package with invalid metadata can break appstream system-wide, when the appstream index itself is correct. It should simply ignore the invalid file (as the debug log says, by the way)

I've bisected it to 5161c4b05a6da2080cddae25fc74647b454b860e

**Comment by ximion** [comment]
I originally wanted to resolve this by adjusting `appstreamcli` to not fail hard on cache loading errors, but eventually opted for still failing hard, but only if there was a large amount of components being recognized as invalid (at least 10% of the total amount of components).
This may get some improvements in future to be less strict about data in the pool, but still complain on issues so they aren't silently ignored.

**Comment by ximion** [comment]
Looks like Choqok need a summary:
```
E - org.kde.choqok.appdata.xml:org.kde.choqok.desktop
    The component is missing a summary (<summary/> tag).

Validation failed: errors: 1, pedantic: 1
```
