### ISSUE TITLE
Document how to take 16:9 screenshots of apps

### ISSUE THREAD

**Issue by har9862** [ximion/appstream#218]
The documentation says that "[screenshots should have a 16:9 aspect ratio](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info)", but it's not clear how to actually make app screenshots with this aspect ratio on Linux.

There used to be a [Gnome extension](https://extensions.gnome.org/extension/736/screenshot-window-sizer/), but the extension has not been updated in 5 years and do not work with later versions of Gnome. It's also not a option for other environments.

If aspect ratio 16:9 is preferable, please update the documentation with some guidance on how this can be done so that we can start update the many outdated/suboptimal screenshots. Ideally using some environment agnostic method.

**Comment by ximion** [comment]
Well, the easiest way is to crop the screenshot later, or pay attention to the window geometry and/or rectangle sizes of the screenshot tool.
I am not aware of any screenshot tool which does let you choose any aspect ratio (and tbh, this does not make too much sense).

I think the ideal way here would be to take a screenshot and then pad the resulting window screenshot with the desktop environment's default background to be in the correct aspect ratio.
But I actually have not seen any software do this in the wild...
@hughsie Do you have some input on this?

In any case, this is not a hard requirement for screenshots, but merely a recommendation to make things look nice and consistent-ish.

**Comment by hughsie** [comment]
> @hughsie Do you have some input on this?

The screenshot extension has been built into gnome-shell iteself for several years.

**Comment by ximion** [comment]
Does that extension allow to set an aspect ratio?
(The thing I am after is whether we should give advice in the quickstart document on how to achieve the right aspect ratio, and if so with which tools)

**Comment by cassidyjames** [comment]
Recommending specific methods or tools for a screenshot is just gonna get hairy, as it quickly becomes, "If you're on GNOME, do this, install this app from this place, use this specific function… if you're on KDE… if you're on elementary OS…"

I think it's better to focus on the requirements themselves than try to dictate specific workflows for achieving the requirements. Just my two cents!

**Comment by ximion** [comment]
@cassidyjames In the specification: Absolutely. On the explanatory document however, if we can give any specific recommendation, we might as well do so.
But it looks like we might not be able to do that here.

**Comment by hughsie** [comment]
it's `Ctrl+Alt+Shift+S` i.e. https://blogs.gnome.org/hughsie/2013/10/08/how-to-take-169-screenshots/

**Comment by ximion** [comment]
Maybe I can just add that information in an "If you use GNOME" infobox to the quickstart guide.

**Comment by fedelibre** [comment]
> Well, the easiest way is to crop the screenshot later, or pay attention to the window geometry and/or rectangle sizes of the screenshot tool.
> I am not aware of any screenshot tool which does let you choose any aspect ratio (and tbh, this does not make too much sense).

gnome-shell screenshot feature has the [Shift+Prt Scrn shortcut to take a screenshot of an area you select](https://help.gnome.org/users/gnome-help/stable/screen-shot-record.html.en).
If this area could be forced to be in a certain aspect ratio set in Dconf, it would be perfect.
I may try filing a feature request to gnome-shell...

The extension mentioned before, even if it works in current GNOME (I haven't tested it but some say it's not working anymore), is not ideal because IIUC it resizes *the whole window*, but you often want to take screenshots of a selected area of the window.

**Comment by fedelibre** [comment]
>  I may try filing a feature request to gnome-shell...

https://gitlab.gnome.org/GNOME/gnome-shell/issues/1890

**Comment by fedelibre** [comment]
> There used to be a [Gnome extension](https://extensions.gnome.org/extension/736/screenshot-window-sizer/), but the extension has not been updated in 5 years and do not work with later versions of Gnome. It's also not a option for other environments.

The new link is https://extensions.gnome.org/extension/881/screenshot-window-sizer/ and it works on GNOME 3.32.
It's still under development within [gnome-shell-extensions](https://gitlab.gnome.org/GNOME/gnome-shell-extensions).

Still not an option for other environments.

**Comment by ximion** [comment]
If you find a good way to do this, can you create a PR against AppStream adding these instructions to the quick start guide for app developers?
That would be pretty useful, and easy to find for people.

**Comment by AlexB67** [comment]
> If you find a good way to do this, can you create a PR against AppStream adding these instructions to the quick start guide for app developers?
> That would be pretty useful, and easy to find for people.

+1
Hello, 

I am lost with this on Fedora 31 and new to this , trying to get it to work appstream validate fails. 

I made 16:9 screenshots, following the instructions best as I could in several places, but to no avail. appstream-uitl validate --verbose is useless in this case as it does tell what is wrong at all. Some Some better debug info wouldn't go astray here !!

I simply get this

(appstream-util:30474): As-DEBUG: 19:54:16.558: Adding file-invalid '<screenshot> failed to load [https://github.com/AlexB67/TCalc/tree/master/data/screenshots/TCalc-window.png]'
(appstream-util:30474): As-DEBUG: 19:54:16.558: checking https://github.com/AlexB67/TCalc/tree/master/data/screenshots/graphs-window.png
(appstream-util:30474): As-DEBUG: 19:54:17.156: Adding file-invalid '<screenshot> failed to load [https://github.com/AlexB67/TCalc/tree/master/data/screenshots/graphs-window.png]'
FAILED:
• file-invalid          : <screenshot> failed to load [https://github.com/AlexB67/TCalc/tree/master/data/screenshots/TCalc-window.png]
• file-invalid          : <screenshot> failed to load [https://github.com/AlexB67/TCalc/tree/master/data/screenshots/graphs-window.png]
Validation of files failed

The links are valid but it is failing nevertheless. screens are with transparent background and png format and 1600:900 resolution.

If I remove the screens validate is okay on everything else, though it complains I must have at least one screenshot, so I can't win.

Any tips why this may be ?

Best regards.

**Comment by ximion** [comment]
@AlexB67 This is unrelated to this issue, also appstream-util isn't even a tool developed by this project (use `appstreamcli validate` instead).
Nevertheless, asutil is correct here, you are not linking images but GitHub HTML pages as "images", which is wrong(tm).

What you want is an URL like https://raw.githubusercontent.com/AlexB67/TCalc/master/data/screenshots/TCalc-window.png and https://raw.githubusercontent.com/AlexB67/TCalc/master/data/screenshots/graphs-window.png which links to the actual image, not a webpage.

**Comment by AlexB67** [comment]
Hi,
Sorry thanks for the reply, I replied in the wrong place when I had several tabs open but it was too late I realised .. my bad. l'll try it out later though :)

Cheers.

**Comment by AlexB67** [comment]
Thank you people, yes, that was really dumb of me and I can't believe I overlooked that. 
Problem Solved.

**Comment by Calinou** [comment]
For KWin users, you can already set the window to an exact size:

1. Focus the window.
2. Press <kbd>Alt + F3</kbd>, look int the top-left corner and open **More Actions > Configure Special Window Settings…**
3. In the window that appears, check **Size**, change **Do Not Affect** to **Apply Now** and enter the desired size like `1600,900` (the highest recommended resolution).
4. Click **OK** to confirm.

Note that this applies to the "real" window size including its window borders. If you don't want to include window borders (e.g. for a game), go to the **Appearance & Fixes** tab, check **No titlebar and frame**, then change **Do Not Affect** to **Apply Now** and check **Yes** besides the dropdown.

I don't think GNOME's window managers or Xfwm have an equivalent to this feature though.

**Comment by ximion** [comment]
The 16:9 recommendation is now even less strict, so I think this issue is sort of dealt with.
For further improvements on the [Quickstart Guide](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps), I will happily merge any PRs that add information on how to achieve something like high-quality screenshots on popular desktop environments.
