### ISSUE TITLE
Weblate does not add me to po header

### ISSUE THREAD

**Issue by scootergrisen** [ximion/appstream#219]
I have translated some strings on Weblate but for some reason my username does not get added to the header in the po file.
And if i upload a po file with a changed header it does not accept the changes i made to the header.

**Comment by ximion** [comment]
It looks like it does add you, as far as I can see: `Last-Translator: scootergrisen <scootergrisen@gmail.com>`
It also points to the Weblate page with the translation history.
In any case, there is nothing I can change about it - if this an issue with the Weblate software itself, reporting it to their bugtracker at https://github.com/WeblateOrg/weblate/issues would certainly help.
If there is something I can do, please feel free to open another bug against AppStream!

**Comment by scootergrisen** [comment]
I mean the first lines with comments in the po file beginning with "# ".
Last-Translator: will be overwritten when someone else changes a string.

Some files have "# Translators:" in the header which might be from Transifex.
Seems like the names that are there are from 2017 and before.
So im guessing the translations was on Transifex at some point.
Some files have "FIRST AUTHOR <EMAIL@ADDRESS>".

If i download translation file for Weblate it self on https://hosted.weblate.org/ the translators names are there in the comments.

The website says:

    Weblate 3.7 release is currently scheduled on 16th June, all translations completed by then will be included. 

So maybe i just wait a little until the server is updated and see if there is a change.
Right now it says Weblate 3.7-dev at the bottom.

**Comment by ximion** [comment]
Looks like this feature is actually an addon to Weblate... I enabled it now, let's see how the result looks like.

**Comment by scootergrisen** [comment]
It works.
