### ISSUE TITLE
POT string indentation

### ISSUE THREAD

**Issue by scootergrisen** [ximion/appstream#220]
For some reason the strings are indented in https://github.com/ximion/appstream/blob/master/po/appstream.pot

    msgid   ""
    msgstr  "Project-Id-Version: appstream\n"
            "Report-Msgid-Bugs-To: appstream@lists.freedesktop.org\n"
            "POT-Creation-Date: 2019-01-26 17:14+0100\n"
            "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
            "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
            "Language-Team: LANGUAGE <LL@li.org>\n"
            "Language: \n"
            "MIME-Version: 1.0\n"
            "Content-Type: text/plain; charset=UTF-8\n"
            "Content-Transfer-Encoding: 8bit\n"
    
    #: tools/appstream-cli.c:146
    #, c-format
    msgid   "'%s' command"
    msgstr  ""
    
    #: src/as-category.c:168
    msgctxt "Category of Graphics"
    msgid   "3D Graphics"
    msgstr ""

I suggest using the ... way im used to :smile_cat: in lack of better words.

    msgid ""
    msgstr ""
    "Project-Id-Version: appstream\n"
    "Report-Msgid-Bugs-To: appstream@lists.freedesktop.org\n"
    "POT-Creation-Date: 2019-01-26 17:14+0100\n"
    "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
    "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
    "Language-Team: LANGUAGE <LL@li.org>\n"
    "Language: \n"
    "MIME-Version: 1.0\n"
    "Content-Type: text/plain; charset=UTF-8\n"
    "Content-Transfer-Encoding: 8bit\n"
    
    #: tools/appstream-cli.c:146
    #, c-format
    msgid "'%s' command"
    msgstr ""
    
    #: src/as-category.c:168
    msgctxt "Category of Graphics"
    msgid "3D Graphics"
    msgstr ""

**Comment by ximion** [comment]
Why do indented strings (or not) matter? People load the files into their favourite translation tool anyway, or use a web-based translator. It's also easy to ignore.
Just from looking at it, having the unlocalized and the localized versions on top of each other even makes sense to me, and since I did nothing to enforce this behavior, I think this might be xgettext's default.
If you want this changed, a patch and a rationale on why this should be changed would be useful.

**Comment by scootergrisen** [comment]
For consistency between pot/po files.
Guess "--indent" have been used for creating the pot fil.
The po files are not used indentation. Just the pot file.
Where is the command that creates the pot file?
