### ISSUE TITLE
Maybe remove translations from Transifex

### ISSUE THREAD

**Issue by scootergrisen** [ximion/appstream#221]
https://github.com/ximion/appstream/blob/master/README.md says to use Weblate.

    You can help translating AppStream via Weblate.

But i notice Transifex have https://www.transifex.com/freedesktop/public/ and Zanata have https://fedora.zanata.org/project/view/appstream-glib?dswid=-1566

I'm guessing the translations used to be a one place and have moved and the old place still have the translations.

To avioid confusing for translators i suggest to remove the old stuff if they are in fact unused.
I dont know when they are lock or contain work that needs to be used.

**Comment by ximion** [comment]
That Zanata link is for a different project, the Transifex repository existed for a while when Freedesktop projects were mostly using Transifex for localization.
It looks like someone disabled the Transifex repo for AppStream over there now, so I think I can close this issue here.
