### ISSUE TITLE
0.12.6 test failures on Ubuntu

### ISSUE THREAD

**Issue by jbicha** [ximion/appstream#222]
appstream 0.12.6 fails to build on Ubuntu because of test failures:

https://launchpad.net/ubuntu/+source/appstream/0.12.6-1

**Comment by ximion** [comment]
Oh wow, what happened there? Nearly every test that reads or writes AppStream data failed.
The same code tests fine on the CI, and also ran fine on Debian during the build process.
The weirdest thing is that XML results are somehow suddenly showing YAML output and vice versa.

**Comment by ximion** [comment]
I've fixed a potential diff output confusion when tests fail in parallel, but that's not the cause of this problem here.
Can you reproduce the issue locally?

**Comment by jbicha** [comment]
Yes, more specifically, it looks like the issue is triggered by glib 2.59.

**Comment by ximion** [comment]
Hmm, from the changelog there at least is no super obvious change in GLib that could have triggered this.

**Comment by jbicha** [comment]
Does this help?

https://gitlab.gnome.org/GNOME/tracker/commit/c58f7aa419e2

**Comment by ximion** [comment]
Ah yeah, that change... - I was actually quite confident AppStream wasn't depending on GHashTable ordering, but that actually would explain the test failures.
I'll have to run the tests locally with a recent GLib though to find all the problems.

**Comment by robert-ancell** [comment]
https://github.com/ximion/appstream/pull/223

**Comment by ximion** [comment]
Those are fully fixed for a while now, and will soon be in a long overdue release.
