### ISSUE TITLE
Appdata: be more specific about the ID

### ISSUE THREAD

**Issue by bilelmoussaoui** [ximion/appstream#227]
Currently, 
the documentation doesn't clearly mention that the app-id in the AppData file is not anyhow related to the application ID that should be used internally. This leads to a misunderstanding from my part and updating the ID of some GNOME apps to remove `.desktop` suffix from the ID that was moved to the launchable tag. 

A lot of other GNOME contributors/developers didn't know there was a difference between the Application ID and the Appstream ID. See the discussion here https://gitlab.gnome.org/GNOME/geary/merge_requests/203

I think we could improve the documentation of the ID tag and clearly mention that both are not related anyhow and the later is used only in GNOME Software/KDE Discover and so on.

**Comment by bilelmoussaoui** [comment]
This was addressed here #226

**Comment by ximion** [comment]
I think the specification actually mentions this particular thing already. Also, we call the ID component-ID or AppStream ID in all documents, to avoid confusion ;-)
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic talks about the naming rules for a component-ID without mentioning .desktop files even once, so this shouldn't create confusion.
And https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps just shows how to model an ID after the .desktop filename if there is any.

The additional clarification on changing existing IDs from #226 will definitely be added though.
