### ISSUE TITLE
Link to bug tracker/project page inside the spec itself

### ISSUE THREAD

**Issue by kparal** [ximion/appstream#234]
Hello, we had a long discussion at https://github.com/hughsie/appstream-glib/issues/302 regarding some parts of the AppStream spec, and the major hurdle for me was that I didn't know where to request spec adjustments/clarifications. This bug tracker is only mentioned at
https://www.freedesktop.org/wiki/Distributions/AppStream/
but if you search for the spec online, you're likely to arrive directly at
https://www.freedesktop.org/software/appstream/docs/
And on that page, there are only 4 names with direct emails, but no link to a project page/bug tracker etc.

Can you please add a link to this github bug tracker or the project page on freedesktop to that initial spec page (or some header/footer)? That would make much easier for people to contribute or file issues.

Thank you!

**Comment by ximion** [comment]
That's probably a good idea.
I added that information to the specification's abstract.
