### ISSUE TITLE
link to latest release?

### ISSUE THREAD

**Issue by bam80** [ximion/appstream#238]
Can find link to the latest release, as described here:
https://help.github.com/en/articles/linking-to-releases

PS:
for now, we have to build Discover flatpak with master AppStream, which is probably not best idea:
https://binary-factory.kde.org/view/Flatpak/job/Discover_flatpak/86/execution/node/22/log/

**Comment by ximion** [comment]
AppStream doesn't really use Github for releases. Releases are published at Freedesktop.org: https://www.freedesktop.org/software/appstream/releases/
You can use that directory to get the latest release (e.g. Debian's uscan can fetch it from there).

> for now, we have to build Discover flatpak with master AppStream, which is probably not best idea:

Depends - by having the master branch you may find problems earlier, before they hit a release.

**Comment by bam80** [comment]
>  Releases are published at Freedesktop.org: https://www.freedesktop.org/software/appstream/releases/

If only there were symbolic link to latest release or something..


> Depends - by having the master branch you may find problems earlier, before they hit a release.

Well, I guess that flatpak repo is for testing Discover app itself, not AppStream. So it questionable.
https://phabricator.kde.org/source/flatpak-kde-applications/browse/master/org.kde.discover.json
