### ISSUE TITLE
Can't build with upstream LMDB

### ISSUE THREAD

**Issue by Vogtinator** [ximion/appstream#239]
LMDB does not ship either pkg-config nor CMake files by itself, so building fails.

See also the discussion in the commit adding LMDB as dependency: https://github.com/ximion/appstream/commit/358e9394631b87797f56dcb7e09e459b4044e631#commitcomment-33867125

**Comment by Vogtinator** [comment]
Tried myself, seems to be as simple as this:

```
-lmdb_dep = dependency('lmdb')
+lmdb_dep = meson.get_compiler('c').find_library('lmdb')
```

Would need some refinement like using this only as a fallback though, but I'm not fluent in meson myself.

**Comment by ximion** [comment]
Thanks for reporting this as a proper issue :-)
This should be fixed via https://github.com/ximion/appstream/commit/653bae3c9e511caa723332873c700529fea18c19 now, give it a try!
