### ISSUE TITLE
glibc, README.md and launchable tag

### ISSUE THREAD

**Issue by ccoupe** [ximion/appstream#242]
Hi,  I'm using Mint 18.1 and trying to parse the metadata with appstreamcli. It doesn't like the 'launchable' tag in the xml. Research suggest this is because my repo's appstream is too old (0.10.6). I cloned the appstream repo to build and
```txt
      meson.build:63:0: ERROR:  Invalid version of dependency, need 'glib-2.0' ['>=2.54'] found '2.48.2'.
```
The README needs to be updated with this value.  I'm not going to update my system to match -  I like to use an older system to build my project with.  It looks like a dead-end for metadata in my appimages.

**Comment by ximion** [comment]
FWIW, GLib != glibc, those are different things - so if you find a newer version as a backport, you may try to update anyway.
That being said, you may consider fetching an AppStream release <= 0.12.5 from https://www.freedesktop.org/software/appstream/releases/ and try building that instead.
That may work for your case.

**Comment by ximion** [comment]
On a second, closer look: Isn't Mint 18.x based on Ubuntu Bionic (18.04)? That one has AppStream 0.12.0-3 in its repositories by default, and also contains GLib 2.56, so it should easily be able to build even the most recent version of AppStream.

**Comment by ccoupe** [comment]
0.12.0  needs a higher glibc. AppStream 0.11.7  has warnings from meson and ninja fails early.  0.12.0 has gobject-introspection version problems (wants 1.54).  0.11.1 has cmake issues.  This is not a hole I want to dig deeper.

upgrading Mint or building in a VM, chroot, docker or vagrant is possible. and I'll consider it and using appImage metadata when I have nothing better to do.  I really want to like AppImage because it seemed less intrusive and easier than flatpack or snap. It's not easier, for me.
