### ISSUE TITLE
Top-level “Author” or “Developer” component

### ISSUE THREAD

**Issue by cassidyjames** [ximion/appstream#244]
In AppCenter, we've been discussing adding a developer page (https://github.com/elementary/appcenter/issues/148) where we show some information about a dev like an avatar, website, contact info, etc. and then all of their apps in the store. While we can currently do some string matching between the RDNNs and/or the developer field on individual apps, it doesn't provide a way to get any more information about the developer.

Would it make sense to have a new top-level developer component in AppStream that could be downloaded and cached alongside the apps' metadata, giving distros, app stores, etc. a place to provide more rich information about the developers behind the apps?

**Comment by hughsie** [comment]
My gut instinct is that this information doesn't belong in AppStream -- it's about describing components (i.e. apps) rather than companies or people. I think an *ID* for a developer would make sense perhaps, but not everything that comes with that, e.g. a photo, company, email address etc.

**Comment by ximion** [comment]
Indeed, what @hughsie said. I found myself in need of a developer/author ID multiple times now though, and toyed around with something like this:
```xml
<creator id="acme_inc">
  <name>ACME Inc.</name>
</creator>
```
Reason for this layout is that we need the `name` to be translatable, and I want to avoid having an `id` tag anywhere else but at the toplevel for the component-ID. This layout would also allow for adding designer/other specific creator names (as requested in https://github.com/ximion/appstream/issues/168 ) if we ever decide to have those in the future, while preserving one creator ID per component.
(I haven't really fleshed out this idea yet, though)

**Comment by cassidyjames** [comment]
The problem with the above approach is the deduplication that would be required to support a modern app store approach of having a developer page showcasing all of their apps. And how does that substantially differ from the existing `developer_name` tag?

But if a top-level approach doesn’t make sense, we can just implement this ourselves with a JSON server or something, and just rely on the RDNN and/or existing `developer_name` tags to match the developer info to the apps' appstream data.

(In case folks browsing here are not familiar, here's an example of a developer page from the Google Play store):

![image](https://user-images.githubusercontent.com/611168/62147221-4ef44700-b2b4-11e9-90b5-9b57809bd698.png)

**Comment by ximion** [comment]
Well, I think specifying developer info pages is out of scope for AppStream, but as you may have noticed, the `creator` tag has an `id` property to specify a non-translatable, hopefully unique ID to group all apps belonging to one vendor together. That would make you not rely on strange heuristics when associating apps and developers.

**Comment by ximion** [comment]
![developers](https://github.com/ximion/appstream/assets/417468/d0fe93b9-4944-47c3-8c12-5f92beee58ea)

**Comment by ximion** [comment]
![developers](https://github.com/ximion/appstream/assets/417468/68abceee-83ae-407e-ba16-0dbeb88d71eb)

You can now use this:
```xml
<developer id="freedesktop.org">
  <name>FreeDesktop.org Project</name>
</developer>
```
This gives a unique ID for the developer, as well as a human-readable name (and it's even extensible, if we ever need to extend it).
