### ISSUE TITLE
release date should accept all ISO 8601 dates

### ISSUE THREAD

**Issue by klausenbusk** [ximion/appstream#245]
appstream does not currently accept `2019-07` as a valid release date (`<release> has no timestamp`), but according to the spec it should be valid: `The date property can have any time in ISO 8601 format as its value and should be present for every release`.

**Comment by ximion** [comment]
What the specification actually means here is that a ISO 8601 "complete date" is required, with at least by-day granularity. That means you need to have at least a year, moth and day information in there.
I clarified that in the specification, and also added a check for this to the validator, so  `appstreamcli validate` will now throw a warning about this issue.
Your error message looks like you were using appstream-util from the appstream-glib project, which with this spec change is likely already fine and doesn't need a separate bug report.

Thank you for noticing this issue!
