### ISSUE TITLE
Typo "XDG Manu Specification"

### ISSUE THREAD

**Issue by rffontenelle** [ximion/appstream#248]
There is a typo in "XDG Manu Specification" (should be "menu"). [Spotted and commented](https://hosted.weblate.org/translate/appstream/translations/pl/?checksum=50cee093b666b565) by @piotrdrag .

This affects [src/as-validator-issue-tag.h](https://github.com/ximion/appstream/blob/666bb956eceb08995ffb0100de5f7473876816fa/src/as-validator-issue-tag.h#L584) and [po/gl.po](https://github.com/ximion/appstream/blob/711f53cdf84729dd9f64f232dc411b2d16083956/po/gl.po#L1028) (which was translated with the typo).

**Comment by ximion** [comment]
Can you submit a PR to fix this?
Otherwise I'll deal with this typo later today.

**Comment by ximion** [comment]
Resolved via https://github.com/ximion/appstream/pull/249
