### ISSUE TITLE
appstream-util validate should fail for unsupported HTML tags

### ISSUE THREAD

**Issue by sonnyp** [ximion/appstream#251]
Only `<p/>`, `<ul/>`, `<ol/>`, `<em/>` and `<code/>` are supported in the [description tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description).

When other tags are present, `appstream-util validate` should fail.

**Comment by ximion** [comment]
`appstream-util` is a tool from a different project, appstream-glib, not from this project.

If I validate with `appstreamcli`, invalid markup is complained about:
```bash
$ appstreamcli validate org.example.TestApp.metainfo.xml
E: org.example.TestApp:101: description-para-markup-invalid pre

Validation failed: errors: 1
```
So, please report this issue against appstream-glib: https://github.com/hughsie/appstream-glib/issues

**Comment by sonnyp** [comment]
https://github.com/hughsie/appstream-glib/issues/322
