### ISSUE TITLE
AppStream collection YAML

### ISSUE THREAD

**Issue by jakobjakobson13** [ximion/appstream#253]
Dear developers,

in a recent [pull request](https://github.com/flathub/org.freedesktop.Sdk.Extension.golang/pull/13#discussion_r312656986) the build of a flatpak image failed because the AppStream collection was saved as a `yaml` file and not as a `json` file.
Was this a bug in the configuration of their [build workers](https://github.com/flathub/org.freedesktop.Sdk.Extension.golang/pull/13) or is AppStream just not able to handle AppStream collections in yaml formats even though the [documentation](https://www.freedesktop.org/software/appstream/docs/sect-AppStream-YAML.html) says otherwise?

Regards

**Comment by TingPing** [comment]
Even if the tooling functions Flathub is not interested in using YAML for it.

**Comment by ximion** [comment]
@jakobjakobson13 `JSON` is not used in AppStream at all anywhere, I guess you mean XML?
While a YAML version of AppStream exists and is fully supported and used by distributions like Debian and Ubuntu, it doesn't mean that a system or distribution can't limit what it ships.
Debian permits only the YAML version, while Fedora permits only the XML version in their archives.
The same applies for Flatpak: While the libappstream library will happily read YAML or XML with no problems, the *system* that is Flatpak is perfectly fine in restricting the format it supports to XML-only.
Does that clarify things?

**Comment by jakobjakobson13** [comment]
> Even if the tooling functions Flathub is not interested in using YAML for it.
> 
Sorry, back in that pull request I had the impression that it was surprising that the yaml file did not work.

> Surely you realize a PR just blindly changing file formats with the comment "No tests have been done." is just... rude? Its a waste of everybodies time for useless churn.
> 
> (Ironically; Sorry for being off-topic here.)
>
I get your point and I won't do it again. I just wanted to be cautious and emphasize that even the build process worked, I did not check the functionality of  package on my pc. Soryy.

**Comment by jakobjakobson13** [comment]
> @jakobjakobson13 `JSON` is not used in AppStream at all anywhere, I guess you mean XML?
> While a YAML version of AppStream exists and is fully supported and used by distributions like Debian and Ubuntu, it doesn't mean that a system or distribution can't limit what it ships.
> Debian permits only the YAML version, while Fedora permits only the XML version in their archives.
> The same applies for Flatpak: While the libappstream library will happily read YAML or XML with no problems, the _system_ that is Flatpak is perfectly fine in restricting the format it supports to XML-only.
> Does that clarify things?

Yes, thanks.

**Comment by TingPing** [comment]
> Sorry, back in that pull request I had the impression that it was surprising that the yaml file did not work.

It was surprising YAML was a supported format at all I think. Anyway I didn't mean to come off too upset.
