### ISSUE TITLE
Typo "The given values is"

### ISSUE THREAD

**Issue by rffontenelle** [ximion/appstream#256]
`The given values is not an identifier for a desktop environment as registered with Freedesktop.org.`

(from [src/as-validator-issue-tag.h, line 393](https://github.com/ximion/appstream/blob/ca01976e248e2a3a8fa52ffb5bf2347d1ac132b7/src/as-validator-issue-tag.h#L393), last changed by PR #250)

"... values is ..."  seems to be a typo. Should it be "... values **are** ..."? Or maybe "The given values **are** not identifier**s**"?

**Comment by ximion** [comment]
Even simpler: This should be the singular form all the way, it's just one value ;-)
Thanks for noticing!
