### ISSUE TITLE
Categories link outdated

### ISSUE THREAD

**Issue by dgcampea** [ximion/appstream#263]
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-categories
links to http://standards.freedesktop.org/menu-spec/latest/apa.html which is 404.
New link should be: https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by ximion** [comment]
Indeed it is, but I do actually wonder whether Freedesktop should fix this as well. The old URLs were used for reference in a lot of places, and having them suddenly break is pretty bad form.

**Comment by tintou** [comment]
This issue is now fixed, standards.freedesktop.org now redirects to specifications.freedesktop.org
