### ISSUE TITLE
news-to-metainfo: elements within Translations header are omitted

### ISSUE THREAD

**Issue by fedelibre** [ximion/appstream#270]
After reading [your interesting blog post](https://blog.tenstral.net/2020/03/maintain-release-info-easily-in-metainfo-files.html/comment-page-1#comment-341381), I started experimenting with news-to-metainfo command.

I had some headaches initially to guess the format of NEWS file, in particular the one (not two!) space indentation required by bulletted lists. GNU did not set any standard format, right?  I mean,  there's no link to point people to?

Anyway, I'm writing to complain about a weird behaviour, probably a bug. The following string in NEWS

```
Translations:
 - Updated dutch and italian translations.
 - Added esperanto.
```

is converted into

```
<p>This release updates translations.</p>
```

Why is it ignoring the items in the list?
How can I specify which languages have been updated or added?

**Comment by ximion** [comment]
> I had some headaches initially to guess the format of NEWS file, in particular the one (not two!) space indentation required by bulletted lists. GNU did not set any standard format, right? I mean, there's no link to point people to?

Sadly no, BUT we could create that ;-) I see no reason why we shouldn't specify that in the AppStream spec as auxiliary format - PRs for the documentation are very welcome on this (I might have a look at this myself at some point, but I am currently a bit busy with porting the specification to another doc generator).
For the spacing, maybe `appstreamcli` should simply support one or two spaces. I'll have a look at that.

As for the conversion of the "translations" section: This was adopted from GNOME behavior, as a lot of people tend to create very long lists of languages under that section that aren't interesting to people who read the release information.
I do see that this is surprising though... I wonder whether this behavior should be made configurable.

**Comment by fedelibre** [comment]
Actually, I'm fine with the idea of stripping translations details in the metainfo files. I just wanted to be sure it was intended.

Allowing arbitrary indentation in NEWS is a good idea, thanks for the quick fix.

I would keep this issue open as a reminder to include all this information in the doc.
I may send a PR when I find some spare time.

**Comment by ximion** [comment]
Very good, thank you!
