### ISSUE TITLE
An property for "Mobile Compatiabilty"

### ISSUE THREAD

**Issue by PizzaLovingNerd** [ximion/appstream#274]
Hello, I was wondering if AppStream could add a property for Mobile Compatibility or something along those lines. Right now, Software Centers such as GNOME Software and KDE Discover have no way to know if an Application is mobile compatible. So on OSes like PureOS, PostmarketOS and Plasma Mobile, it's hard to tell what works on mobile. Adding a mobile compatible property could help fix this issue to help Linux Phones become mainstream.

**Comment by cassidyjames** [comment]
This should be solvable with the existing (albeit relatively new) mobile input controls stuff: https://github.com/ximion/appstream/pull/265

App stores on mobile form factors could use that information to decide if apps are "mobile compatible" or not based on their hardware and/or software platform.

**Comment by ximion** [comment]
Indeed. We had a really long discussion on the mailinglist a while back, but the quintessential result is that the question of "what is a mobile device?" simply cannot be answered in a universal way.
AppStream does provide information about input controls now, so software centers can know whether an app supports touch input an pass judgement on whether the app should be shown on a mobile device based on that.

In future I am also not opposed to adding screen-size range information into the mix, but that will need some careful evaluation and planning. In the meanwhile, the touch input field may already be useful :-)

**Comment by ximion** [comment]
Indeed. We had a really long discussion on the mailinglist a while back, but the quintessential result is that the question of "what is a mobile device?" simply cannot be answered in a universal way.
AppStream does provide information about input controls now, so software centers can know whether an app supports touch input an pass judgement on whether the app should be shown on a mobile device based on that.

In future I am also not opposed to adding screen-size range information into the mix, but that will need some careful evaluation and planning. In the meanwhile, the touch input field may already solve your issue for many (most?) applications :-)

**Comment by PizzaLovingNerd** [comment]
Maybe instead add an "adaptive" property on whether or not an application can adapt to fit on a smaller phone or tablet screen, rather than if touch works.

**Comment by cassidyjames** [comment]
That's still unclear. Adaptive… how? More measurable properties could be minimum supported size and optionally maximum supported size which would give you better data about fitting onto a phone-sized display. 

But adding any properties is also more work for developers, and if developers don't add the data, it's minimally useful in the end.

**Comment by PizzaLovingNerd** [comment]
Yeah, a minimum window size property would be a good idea, and since building Linux apps is a relatively new thing, and pretty much all Linux mobile apps for Phosh are in active development, than only they would have to mark the minimum window size property. All of the other ones could not be shown in GNOME Software, Discover, etc on mobile phones.

**Comment by ximion** [comment]
We have https://github.com/ximion/appstream/issues/285 to track the screen-size thing explicitly. Combined with the already existing input control constraints, this should allow software components to use a feature-based approach to defining what range of devices they want to support.
It will take a bit of time for the display properties stuff to mature and be implemented though.
