### ISSUE TITLE
Validate vs docs: `<em>` in `<description>`

### ISSUE THREAD

**Issue by marcusmueller** [ximion/appstream#278]
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description says that `<em>` is valid in `<description>`. `appstreamcli validate` (0.12.7) begs to differ.

Without a machine-readable scheme, it's not clear who's right.

**Comment by ximion** [comment]
This is not a bug - `code` and `em` are only supported since AppStream 0.12.8 (released ~1y ago), so you'll need to upgrade to at least that version (ideally though to 0.12.11, the latest release).

**Comment by marcusmueller** [comment]
@ximion wouldn't that imply that the "applies to appstream 0.12" headline in the docs is insufficiently specific?

**Comment by marcusmueller** [comment]
@ximion by the way, can't find a CHANGELOG that describes that; I've neither been able to find the commit from the commit messages (`git log --summary v0.12.10..v0.12.11`) that adds that?

**Comment by ximion** [comment]
> @ximion wouldn't that imply that the "applies to appstream 0.12" headline in the docs is insufficiently specific?

It applies to the 0.12 series (which doesn't make any breaking changes - that said, breaking changes of the spec are very unlikely at this point anyway). Now that DAPS is used for building the docs, we could probably add the full version somewhere as well.

> @ximion by the way, can't find a CHANGELOG that describes that; I've neither been able to find the commit from the commit messages (`git log --summary v0.12.10..v0.12.11`) that adds that?

https://github.com/ximion/appstream/blob/master/NEWS#L158

**Comment by marcusmueller** [comment]
@ximion  thanks!!

**Comment by ximion** [comment]
> `git log --summary v0.12.10..v0.12.11`

This was added in 0.12.8, so you could have found it via  `git log --summary  v0.12.7..v0.12.11` - but that's a ton of changes to go through, the NEWS file is much easier (that one contains only the highlights, without stuff like typo fixes).
