### ISSUE TITLE
appstream disagrees over the sparkleshare id

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#281]
When I use the file from the distro (i.e. normal behaviour) I get:
```
$ appstreamcli search sparklesh
Identifier: org.sparkleshare.SparkleShare [desktop-application]
Name: SparkleShare
```

But if I parse the file like we do to import flathub's appstream.xml, I get `org.sparkleshare.SparkleShare.desktop` when calling AppStream::Component::id().

I don't seem to be able to attach files here, but it can be read easily at `/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml`.

Any idea why where the .desktop postfix would be coming from?

**Comment by aleixpol** [comment]
The problem seems to be that flathub somehow adds a .desktop postfix to the package for some reason:
```
<component type="desktop">
    <id>org.sparkleshare.SparkleShare.desktop</id>
...
```

**Comment by ximion** [comment]
Jup, I just checked - not an AppStream issue, but yet another case of Flathub changing a *unique* AppStream ID to something different for absolutely no reason. Grrr! ;-)

**Comment by aleixpol** [comment]
It seems like upstream added the .desktop, maybe appstream is removing it?
https://github.com/hbons/SparkleShare/commit/e0c4e972d0b52ef71b0fafe6fb33511e429af955
https://github.com/flathub/org.sparkleshare.SparkleShare/issues/5

**Comment by ximion** [comment]
> It seems like upstream added the .desktop, maybe appstream is removing it?
> [hbons/SparkleShare@e0c4e97](https://github.com/hbons/SparkleShare/commit/e0c4e972d0b52ef71b0fafe6fb33511e429af955)
> [flathub/org.sparkleshare.SparkleShare#5](https://github.com/flathub/org.sparkleshare.SparkleShare/issues/5)

No, it doesn't: Download the upstream release packaged in Debian, http://deb.debian.org/debian/pool/main/s/sparkleshare/sparkleshare_3.28+git20190525+cf446c0.orig.tar.xz and look at the ID in SparkleShare/Linux

And the commit you show shows upstream *removing* the .desktop suffix, as they should ;-)

**Comment by barthalion** [comment]
That change never has been released. Unless Debian is now upstream developer of SparkleShare?

**Comment by ximion** [comment]
> That change never has been released. Unless Debian is now upstream developer of SparkleShare?

Apparently SparkleShare hasn't had an upstream release for more than two years, but has an active upstream. It's quite common for distributions to package a Git snapshot with some added testing and QA in these cases, in most events to fix a long list of bugs present in the old release but fixed in Git master (best solution here would be if upstream would just make another release ^^).

**Comment by aleixpol** [comment]
I guess the problem then is that they changed their id without adding a provides with the former one anyway.

**Comment by ximion** [comment]
I think the most important issue is that there wasn't a release for more than two years, so the improvements and changes, including the ID one, just aren't getting to all users.
Not adding the provides entry for the old ID is a very minor thing compared to that issue to me ^^ (AppStream will not automatically merge old/new IDs, that entry will be used however to combine ratings & reviews. And currently required everyone to play fair and not take over IDs they don't own, which is something I really don't like)
