### ISSUE TITLE
usr/bin/appstreamcli: symbol lookup error: /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time

### ISSUE THREAD

**Issue by Lateralus138** [ximion/appstream#282]
Hello, you've been helping me on Twitter and I've got the other problems fixed (I'm pretty sure) after upgrading to 20.04 , but I have a new error in `appstreamcli` when using the `appimagetool` trying to compile my project.

Error:
```Bash
 $ appimagetool mcchunkgetv2.AppDir
appimagetool, continuous build (commit 20ea487), build 2117 built on 2020-02-18 05:18:18 UTC
Using architecture x86_64
/home/flux/python/projects/crossplatform/mcchunckgetv2/src/linux/appimage/mcchunkgetv2.AppDir should be packaged as MC_Chunk_Get_V2-x86_64.AppImage
AppStream upstream metadata found in usr/share/metainfo/io.github.lateralus138.mc_chunk_get_v2.appdata.xml
Trying to validate AppStream information with the appstreamcli tool
In case of issues, please refer to https://github.com/ximion/appstream
/usr/bin/appstreamcli: symbol lookup error: /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
Failed to validate AppStream information with appstreamcli
 Error: 1
```

![AppStreamCLI Error](https://raw.githubusercontent.com/Lateralus138/MC-Chunk-Get-V2/master/images/appstreamcli_error.png)

**Comment by ximion** [comment]
This looks like an AppImage bug - apparently a different version of libsoup is used at runtime compared to what AppStream was compiled with (likely appimagetool messes with LD_LIBRARY_PATH and doesn't reset that when calling `appstreamcli`). Maybe @probonopd knows more.

**Comment by Lateralus138** [comment]
Ok thanks and sorry to bother with this.

**Comment by probonopd** [comment]
Try appimagetool from https://github.com/probonopd/go-appimage. It is not exporting `LD_LIBRARY_PATH` anymore.
