### ISSUE TITLE
as_validate_has_hyperlink gives false positives

### ISSUE THREAD

**Issue by cassidyjames** [ximion/appstream#283]
`as_validate_has_hyperlink` causes validation to fail if I even mention the stand-alone string `ftp://` in my release notes—without any actual hostname, which I did for my browser since I now handle protocols. :)

https://github.com/ximion/appstream/blob/dd557bf2275f74c51fec0a0a8d60385029a741d3/src/as-validator.c#L447-L464

See: https://github.com/cassidyjames/ephemeral/issues/260#issuecomment-702435783

**Comment by ximion** [comment]
Fun! :-) Looks like we may need a regular expression here then (although I also could do some string expression fun, which *may* be faster). In any case, definitely a false-positive validation error, thanks for reporting it!
