### ISSUE TITLE
strange compare-versions result in version 0.12.11

### ISSUE THREAD

**Issue by peutch** [ximion/appstream#288]
Hi,

Using gnome-software (Ubuntu and Debian), some packages (currently openjdk-11-*) were sorting strangely in 'Downgrade' what seems for me an 'Upgrade'. Then I checked using the command line:

$ appstreamcli compare-versions 11.0.9.1+1-0ubuntu1 11.0.9+11-0ubuntu2
11.0.9.1+1-0ubuntu1 << 11.0.9+11-0ubuntu2
$ appstreamcli compare-versions 11.0.9.1 11.0.9
11.0.9.1 >> 11.0.9

I suspect that this is also related to:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/935
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/876

Thanks

**Comment by ximion** [comment]
That's likely unrelated, as GNOME Software doesn't use libappstream - it does look strange regardless though...

**Comment by peutch** [comment]
Thanks!
Sure and it is not clear to me what is used in the case of GNOME Software between appstream-util/libappstream-glib8 and appstream/libappstream.

Do you mean also that this (runtime?) dependency is not necessary:
$ LANG=C apt depends gnome-software
gnome-software
  Depends: appstream
...?

(cf. https://packages.debian.org/unstable/gnome-software)

**Comment by peutch** [comment]
Right same trouble with appstream-util:
$ appstream-util vercmp 11.0.9.1+1-0ubuntu1 11.0.9+11-0ubuntu2
11.0.9.1+1-0ubuntu1 < 11.0.9+11-0ubuntu2
$ appstream-util vercmp 11.0.9.1 11.0.9
11.0.9.1 > 11.0.9

**Comment by ximion** [comment]
On Debian, GNOME Software actually needs both: appstream-glib (with libappsteam-glib) by GNOME Software directly, and AppStream's `appstreamcli` for some Debian-specific plumbing shared across all software centers.
But this confusion may be over at some point in the future, with GNOME Software switching to libappstream: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1097

For the matter at hand, AppStream is using RPMs version comparison algorithm (unlike appstream-glib), and I am surprised that it doesn't handle the plus sign well.
I will have a look :-)

**Comment by ximion** [comment]
With the version comparison rewrite, `appstreamcli` returns correct results now:
```shell
$ appstreamcli vercmp 11.0.9.1+1-0ubuntu1 11.0.9+11-0ubuntu2
11.0.9.1+1-0ubuntu1 >> 11.0.9+11-0ubuntu2
```
