### ISSUE TITLE
Broken vala bindings (again)

### ISSUE THREAD

**Issue by ricotz** [ximion/appstream#289]
due to https://github.com/ximion/appstream/commit/b52858bff55d358f925b8e64bab77b953067f248

There was a lengthy discussion regarding those annotations, see https://github.com/ximion/appstream/pull/214 and https://github.com/ximion/appstream/pull/208

If python is actually iterating over the elements of a `GPtrArray` to free them then this is wrong. It should be advised to use the available GLib API.

**Comment by tintou** [comment]
I raised this issue to [GObject Introspection](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/305) and there is a lack of annotation for this. The current way of dealing with is is to use `g_ptr_array_set_free_func (ptrarray, NULL);` before returning the GPtrArray…
See [how GNOME Builder is doing this](https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/master/src/libide/io/ide-gfile.c#L418) when returning a GPtrArray

**Comment by ximion** [comment]
I can't remove the free function, as this would break the C API.
Wow, this sucks... Can't either Vala, Python or GIR be fixed to address this?

**Comment by ricotz** [comment]
As a mitigation you can add a metadata file for vala to tweak the generated vapi.

**Comment by ximion** [comment]
That may be the best temporary fix...
At the moment it seems like I can choose between breaking all C users of libappstream, breaking Appcenter via Vala bindings, or breaking Python applications with the previous change that made Vala work (as reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974107 ).

**Comment by ximion** [comment]
How would I have to change the Vala metadata to fix this for Vala? I would like to go this route for the next release (scheduled for Monday), and maybe find a more permanent solution later.
Unfortunately, there doesn't seem to be a workaround for Python.
