### ISSUE TITLE
as-enums-types.h installed to wrong path

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream#291]
The as-enums-types.h header is installed to ${prefix}/appstream. This doesn't look right.

**Comment by ximion** [comment]
It's not... And found right after a release, of course :-P

**Comment by antonio-rojas** [comment]
well, that's when I build stuff :)

**Comment by ximion** [comment]
Yeah, but me and other people build this thing way more often, and there is a whole CI pipeline dedicated to it *and* this code received review in a PR...
Oh well, sometimes you have bad luck :-D
