### ISSUE TITLE
Metainfo file '../data/org.freedesktop.appstream.cli.metainfo.xml' does not exist.

### ISSUE THREAD

**Issue by bigon** [ximion/appstream#295]
Hello,

On [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=appstream&arch=hurd-i386&ver=0.13.1-2&stamp=1608599656&raw=0), appstream FTBFS with the following error:

```
[58/171] /<<PKGBUILDDIR>>/obj-i686-gnu/tools/appstreamcli news-to-metainfo --limit=6 ../data/../NEWS ../data/org.freedesktop.appstream.cli.metainfo.xml data/nol10n_withrelinfo_org.freedesktop.appstream.cli.metainfo.xml
FAILED: data/nol10n_withrelinfo_org.freedesktop.appstream.cli.metainfo.xml 
/<<PKGBUILDDIR>>/obj-i686-gnu/tools/appstreamcli news-to-metainfo --limit=6 ../data/../NEWS ../data/org.freedesktop.appstream.cli.metainfo.xml data/nol10n_withrelinfo_org.freedesktop.appstream.cli.metainfo.xml
Metainfo file '../data/org.freedesktop.appstream.cli.metainfo.xml' does not exist.
ninja: build stopped: subcommand failed.
```

I'm not too sure what's happening here as it builds fine on all other architectures

**Comment by ximion** [comment]
Very weird... Maybe `appstreamcli news-to-metainfo` crashes, but such an event would be logged... And an output file would be written in any case. So, I guess this is one of the cases which can only be investigated with direct access to the OS/arch for testing.

**Comment by ximion** [comment]
Is this still an issue?

**Comment by bigon** [comment]
Yes it's still an issue with [0.14.4](https://buildd.debian.org/status/fetch.php?pkg=appstream&arch=hurd-i386&ver=0.14.4-1&stamp=1625945764&raw=0)

**Comment by bigon** [comment]
Apparently 0.14.5 now successfully build on hurd-i386

https://buildd.debian.org/status/fetch.php?pkg=appstream&arch=hurd-i386&ver=0.14.5-1&stamp=1630703538&raw=0

Not exactly sure what changed
