### ISSUE TITLE
Allow for Apache-2.0 License in metainfo

### ISSUE THREAD

**Issue by awarnke** [ximion/appstream#297]
Hello,

Currently, there is an error report for project https://tracker.debian.org/pkg/crystal-facet-uml 

stating
"
metainfo-license-invalid
The MetaInfo file does not seem to be licensed under a permissive license. 
"
but Apache-2.0 should be pemissive enough (see http://spdx.org/licenses/ ):

  <name>crystal-facet-uml</name>
  <metadata_license>Apache-2.0</metadata_license>
  <project_license>Apache-2.0</project_license>
see https://github.com/awarnke/crystal_facet_uml/tree/master/installation_linux

Could you allow this type of License-information?

Kind Regards
Andreas

**Comment by awarnke** [comment]
Checking issue #195  i guess i start understanding the bug:
Only the <metadata_license>MIT</metadata_license> needs to be adapted, not the <project_license>Apache-2.0</project_license> ?
The Error message seems to state this - maybe it helps making this more clear in the error message text?

**Comment by awarnke** [comment]
I see that you need the MIT License for this file.

Is it possible to provide the metainfo.xml under two licenses:
MIT for appstream purposes
and Apache-2.0 to avoid the lintian-checker bugs due to mismatches between metainfo.xml and debian/copyrights ?

cu
Andreas

**Comment by ximion** [comment]
This does sound like a Lintian bug!

So, the `project_license` is what the project, its code and data are actually licensed under, the `metadata_license` is what the *MetaInfo file only* is licensed under.. I think this may actually have been addressed in Lintian by now :-)

**Comment by awarnke** [comment]
Thank you for checking. My current setup seems to work:

  <metadata_license>CC0-1.0</metadata_license>
  <project_license>Apache-2.0</project_license>

**Comment by ximion** [comment]
> My current setup seems to work

Yes, this is how it's meant to be :-)
Thank you for updating that metadata!
