### ISSUE TITLE
Typo in coollection?

### ISSUE THREAD

**Issue by rffontenelle** [ximion/appstream#300]
https://github.com/ximion/appstream/blob/8ce62d2de0c13ee7b0a87a958906b843a078009c/tools/appstream-cli.c#L463

Should it be "collection"?

**Comment by ximion** [comment]
Jup, should definitely be `collection` - it's also cool though :-P

**Comment by rffontenelle** [comment]
cool typo, bro

**Comment by ximion** [comment]
Sadly though, it had to go :-P
Thanks for finding & reporting the issue!
