### ISSUE TITLE
Validate false positive

### ISSUE THREAD

**Issue by gunnarhj** [ximion/appstream#308]
Hi!

```
$ appstreamcli --version
AppStream version: 0.14.1

$ appstreamcli validate /usr/share/metainfo/emoji-picker.appdata.xml
E: org.freedesktop.ibus.engine.typing_booster.emoji_picker:17: web-url-expected
     
     https://raw.githubusercontent.com/mike-fabian/ibus-typing-booster/master/icons/64x64/ibus-typing-booster.png

Validation failed: errors: 1
```
The URL is valid as far as I can tell.

![Typing Booster](https://raw.githubusercontent.com/mike-fabian/ibus-typing-booster/master/icons/64x64/ibus-typing-booster.png)

What am I missing?

**Comment by ximion** [comment]
Can you attach the metadata? I guess there are some spaces or tabs interfering here, but AppStream should strip these away.

**Comment by gunnarhj** [comment]
Sure, it's line 17.

[emoji-picker.appdata.xml.gz](https://github.com/ximion/appstream/files/6036631/emoji-picker.appdata.xml.gz)

**Comment by gunnarhj** [comment]
I can add that it didn't complain a couple of months ago, so I suspect it is some kind of regression.

**Comment by ximion** [comment]
Jup, this was broken in the 0.14.1 release. It's resolved now, unfortunately there is no easy workaround for you.
Fortunately though, AppStream 0.14.2 will likely be released next week.
Thank you very much for reporting this issue!
