### ISSUE TITLE
l10n: small nick-pick in .pot

### ISSUE THREAD

**Issue by MingcongBai** [ximion/appstream#31]
So hi...

I've noticed this when doing zh_CN l10n work on AppStream. And the small flaw can be found here:

https://github.com/ximion/appstream/blob/master/po/appstream.pot#L61

As it says:

```
#, c-format
msgid   "Can not copy '%s': File does not have a 'metainfo.xml' or '.appdata.xml' extension."
msgstr  ""
```

Notice that of `metainfo.xml` and `.appdata.xml`, one has a dot at the front while the other doesn't.

**Comment by ximion** [comment]
Things like this need to be fixed in the code - I did that with the comment above.
Thanks for noticing this and reporting the issue!
