### ISSUE TITLE
appstream-generator doesn't accept dual-licensed metadata

### ISSUE THREAD

**Issue by City-busz** [ximion/appstream#323]
Evince specifies `GPL-2.0+ or GFDL-1.3-only` as [metadata license](https://gitlab.gnome.org/GNOME/evince/-/blob/master/org.gnome.Evince.appdata.xml.in#L21), but it's [not accepted by appstream-generator](https://appstream.debian.org/sid/main/issues/evince.html) as a permissive license. Since the metadata is dual-licensed and one of them is permissive, it should be accepted by appstream-generator.

Tested with appstream 0.14.3 and appstream-generator 0.8.4.

**Comment by ximion** [comment]
The `metadata_license` tag does not accept a license expression, and actually even only a list of accepted licenses.
This should likely be made even more clear in the specification (https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license) as well as the explanation of the appstream-generator issue tag.

**Comment by City-busz** [comment]
So it must be fixed in the evince package by removing `GPL-2.0+` from `metadata_license`? I requested it from the developers, but they said that the metainfo file is reported as valid by `appstreamcli validate`. You can see their comment here:
https://gitlab.gnome.org/GNOME/evince/-/merge_requests/346#note_1135950

**Comment by ximion** [comment]
Oh, that is indeed not okay - looks like a bug in appstream-generator then...
