### ISSUE TITLE
mailto: URLs in <contact> should not be deprecated with the given reasoning

### ISSUE THREAD

**Issue by marcusmueller** [ximion/appstream#331]
> In the past, mailto: URL schemas to link to email addresses were also supported for this URL type. It is recommended to not use them in new metadata, as they provide poor usability on most systems when users click on such a link and no local email client is configured. 

Not offering the user a good experience when clicking on the *appropriate* information on how to contact an author or project is not a shortcoming of the metadata, but of the GUI frontend. 

There's enough projects out there with no website or a single author; enforcing metadata linking to something that is *not* actually the way to contact the author just because it's hard to do right in the GUI isn't the right choice here!

**Comment by ximion** [comment]
Developers can easily set up a Mastodon-Account/Forum/GitHub-Page, etc. rather than making a public email address available.

If we bring such a method of contact back, then in the form of a `creator` tag, where something like an email can be attached in a different way.

**Comment by marcusmueller** [comment]
@ximion 

> Developers can easily set up a Mastodon-Account/Forum/GitHub-Page, etc. rather than making a public email address available.

I'm sorry, this is a nonsense argument, the GNU Radio mailing list has some > 3000 subscribers, and beginner questions on there are going to be answered in minutes to hours. **Nobody** moves a community or a standard way of contacting becasuse an appstream definition says "email is soooo 2000s".

**Comment by marcusmueller** [comment]
FYI: I need to raise this on the fedora-devel mailing list, because they are intensely talking about appstream metadata validation right now, and for many packages Email *is* the only form of contact. It's also the *one* platform all devs can agree on; I'll include you in BCC, @ximion, I think anything else would be unfair.

**Comment by ximion** [comment]
> GNU Radio mailing list has some > 3000 subscribers

Then point users to https://wiki.gnuradio.org/index.php/MailingLists as contact URL? That explanatory page will help them a lot to get started.

**Comment by marcusmueller** [comment]
Hey sorry for being so harsh there, but that was but an example. You're right, GNU Radio is large enough to have a landing page, and thank you for looking it up. You went beyond the necessary there.

Still, for many smaller applications, having an email address is just the *honest* answer, even if it's not convenient. I care a lot about these use cases, because I'd like metadata to be correct, not just "pretty". (That by the way is also why you find me asking for schemata and such.)
