### ISSUE TITLE
Is there a difference between libappstream version and the standard version

### ISSUE THREAD

**Issue by tintou** [ximion/appstream#340]
The [documentation stands](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#id-1.4.4.4.6.1) that it is currently version 0.9
Does it mean that there is a difference between this repository release and the specification?

**Comment by ximion** [comment]
No, the major.minor version of this repository *is* the specification release, and the C library should implement the respective version fully. What you found is probably either a string-replace oversight, or we thought we would switch to 1.0 sooner back then...
It's corrected now, thanks for noticing!
