### ISSUE TITLE
news-to-metainfo: ignore description

### ISSUE THREAD

**Issue by fedelibre** [ximion/appstream#350]
This is a feature request: what about adding a `--no-description` switch  so that the script will generate only a `<release>` tag (with version, date, type) and ignore the actual release notes?

This would be useful for those projects that want to keep the metainfo small and simple. No description in metainfo means also less work for translators.

**Comment by ximion** [comment]
I'm against that, as it makes release metadata less useful and user-friendly.
However, I think this subcommand could grow a flag `--translate=all|none|last` to mark all, none or just the last few releases as translatable.
Projects which want a simple metainfo file can run appstreamcli during the build process, like AppStream itself does ;-)

**Comment by fedelibre** [comment]
I guess it's [here](https://github.com/ximion/appstream/blob/master/data/meson.build#L10).

Ok, it sounds good. Feel free to change the title of this issue.

**Comment by ximion** [comment]
You can now run appstreamcli like this:
`appstreamcli news-to-metainfo ./NEWS --limit=10 --translatable-limit=3`
This will limit the overall list of added releases to 10, and mark only the latest 3 as translatable. The annoying thing is that this may actually cause translations of older entries to be removed from your translation templates, and therefore already translated past-entries being removed too, unless their data was already merged into the XML.
So, to get the full advantage of this, some more clever tooling around it is probably required.
