### ISSUE TITLE
as_license_is_free_license() classifies strings like "MIT License" as non-free

### ISSUE THREAD

**Issue by CecilHarvey** [ximion/appstream#359]
This is used by some of the third-party packages, like the official RPM package of microsoft's powershell, which is MIT licensed.

It might be better to ignore the token "License" itself rather than considering the word "License" itself as non-free.

**Comment by ximion** [comment]
This is not a bug, as long as "MIT License" is the string you are trying to check. The parameter to this function *must* be a SPDX license ID or expression, so only "MIT" would be considered valid.
See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license for the specification entry and https://spdx.org/licenses/ for a list of valid license IDs.
