### ISSUE TITLE
as_pool_build_search_tokens strips off last character

### ISSUE THREAD

**Issue by robert-ancell** [ximion/appstream#361]
The following program:
```c
   g_autoptr(AsPool) pool = as_pool_new ();
   g_auto(GStrv) tokens = as_pool_build_search_tokens (pool, "evince");
   for (guint i = 0; tokens[i] != NULL; i++) {
      g_printerr ("%s\n", tokens[i]);
   }
```

Prints out `evinc`, which seems to indicate the last character is being dropped from search terms.

**Comment by robert-ancell** [comment]
FYI @pwithnall - I noticed this in gnome-software and followed it to appstream.

**Comment by pwithnall** [comment]
(Note that @robert-ancell [might not be available for the next week](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1471#note_1280378) to follow up on this)

**Comment by pwithnall** [comment]
This is likely the result of stemming (`as-stemmer.c`)

**Comment by ximion** [comment]
I agree, and since AppStream caches stemmed tokens, this would be expected
behaviour...
Unless of course stemming is inconsistent, which it shouldn't be.

Philip Withnall ***@***.***> schrieb am Fr., 1. Okt. 2021,
13:06:

**Comment by pwithnall** [comment]
@robert-ancell did you notice this as the result of a misbehaviour in gnome-software, or just coincidentally?

**Comment by ximion** [comment]
@robert-ancell I think that really depends on the description of GS' plugin API: Are the plugins supposed to get preprocessed (and thereby stemmed) search tokens, or are they supposed to get the raw input submitted by the user?
I think an argument could be made for both, the former is more efficient, the latter is more flexible as some plugins may want their own stemming.
In any case, this isn't an issue in AppStream, that pretty much works as intended as we do want stemmed search terms.
