### ISSUE TITLE
Error while updating Arch Linux Package

### ISSUE THREAD

**Issue by nowshed-imran** [ximion/appstream#365]
I filed a [bug](https://bugs.archlinux.org/task/72909) report in Arch Linux, but the maintainer said it is an upstream issue.

This is the error I got while updating:
```
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating the appstream cache...

** (appstreamcli:8448): WARNING **: 14:30:07.123: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

** (appstreamcli:8448): WARNING **: 14:30:07.123: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.
✔ Metadata cache was updated successfully.
(3/3) Cleaning pacman cache...
```
Making a report, in case it's a bug.

**Comment by ximion** [comment]
This is just a warning about broken AppStream metadata - there's nothing we can do about this here (except for, well, not warn about it and just throw out broken data silently...).
Can you report this against Flatpak or appstream-glib and CC me to the new issue? Thanks!

If this *does* exit with an error code and breaks updates in any way, please feel free to reopen this issue, as this should only be a warning and must not interrupt anything.

**Comment by ximion** [comment]
See also https://github.com/flatpak/flatpak/issues/4642

**Comment by nowshed-imran** [comment]
I solved it by deleting `flatpak` folder in the `/var` partition.

**Comment by arrowmaster** [comment]
> (except for, well, not warn about it and just throw out broken data silently...).

This needs to be silently dropped. These messages are breaking aptitude on Debian and require blindly (because the UI is now garbled) exiting and reopening aptitude every time they appear.
