### ISSUE TITLE
Some icons are wrongly rescaled

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream#375]
Since commit c57909568f0ffa568da251102a0403fed936a43c, many icons are wrongly rescaled when indexing metadata, and they take only the first quarter of the canvas. This affects most gnome application icons, for instance the ones from https://archlinux.thaller.ws/extra/os/x86_64/evolution-3.42.2-1-x86_64.pkg.tar.zst

Before c57909568f0ffa568da251102a0403fed936a43c:
![pre](https://user-images.githubusercontent.com/11243355/148586330-e00fd369-8e2d-40a9-8f7c-37a3d9203744.png)

After c57909568f0ffa568da251102a0403fed936a43c:
![post](https://user-images.githubusercontent.com/11243355/148586346-57d106f8-d11c-43e9-89e2-45178e98408c.png)

librsvg is at 2.52.5

**Comment by heftig** [comment]
I think you shouldn't `cairo_scale` the surface in the path that uses the viewport, as that already takes care of rescaling the svg.
