### ISSUE TITLE
<keywords>

### ISSUE THREAD

**Issue by apachelogger** [ximion/appstream#389]
It might make sense to add keywords (aka tags) into the metadata. Previously with the 1:1 mapping of desktopfile-appdata file we were kind of able to infer relevant tags from the desktop file, but since we can now have multiple launchables that doesn't necessarily work anymore. Yet I think it would make sense to provide the ability to set keywords for a component such that it may be more easily searched for. This is pretty much 100% analogous to the Keywords entry of the desktop entry spec. This would also improve reuse of appstream data to feed into the window store metadata (which too does have a keyword system).

```
<keywords>
<keyword>partitioning</keyword>
<keyword lang=de>partitionierung</keyword>
</keywords>
```

or some such

**Comment by ximion** [comment]
Like https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-keywords ? ;-)
I will need to check whether this works for metainfo files, but I am pretty sure it does already and just needs to be formally advertised in the specification, and appstream-compose needs to learn how to merge keywords properly (or just prefer the ones in a metainfo file if there's also some available in the desktop-entry file)

**Comment by apachelogger** [comment]
Exactly like that! :)

**Comment by JakobDev** [comment]
The Keyword tag is [already be used on Flathub](https://github.com/search?l=XML&q=org%3Aflathub+%3Ckeyword%3E&type=Code), so it makes sense to add it to the Appstream Standard.

**Comment by ximion** [comment]
This has been part of AppStream since its first draft, but just hasn't been documented for metainfo files yet.
