### ISSUE TITLE
`Pool::search` leaks memory

### ISSUE THREAD

**Issue by easyteacher** [ximion/appstream#391]
When repeating calling [the function](https://invent.kde.org/plasma/plasma-workspace/-/blob/d2f948ec20b3ed03a60f95ee2bcd5228c3593cef/runners/appstream/appstreamrunner.cpp#L163), the krunner process's memory consumption keeps getting larger and larger. The leak is gone when commenting out the function.

Heaptrack result: [heaptrack.tar.gz](https://github.com/ximion/appstream/files/8313896/heaptrack.tar.gz)

> Information for package libAppStreamQt2:
> ----------------------------------------
> Repository     : unstable-kde-frameworks
> Name           : libAppStreamQt2
> Version        : 0.15.1-ku.84.1
> Arch           : x86_64
> Vendor         : obs://build.opensuse.org/KDE:Unstable
> Installed Size : 274.1 KiB
> Installed      : Yes
> Status         : up-to-date
> Source package : AppStream-0.15.1-ku.84.1.src
> Upstream URL   : https://www.freedesktop.org/software/appstream/docs/
> Summary        : Qt5 bindings for AppStream

**Comment by easyteacher** [comment]
The leak should exist elsewhere.

**Comment by ximion** [comment]
So, you closed the issue because the leak isn't in AppStream?
(AFAIK there is no memory leak, because I profiled this a lot last year, but on the other hand there's always a chance that one was introduced since the last manual analysis and asan didn't catch it automatically)
