### ISSUE TITLE
appstreamcli validate complains about an URL returning 302

### ISSUE THREAD

**Issue by heirecka** [ximion/appstream#394]
Noticed with klickety's autotests which involve appstream cli validate (https://build.kde.org/job/Applications/view/Everything%20-%20stable-kf5-qt5/job/klickety/job/stable-kf5-qt5%20SUSEQt5.15/50/console):

```
W: org.kde.ksame.desktop:106: url-not-reachable
19:59:10           https://docs.kde.org/?application=klickety&branch=stable&path=ksame_mode.html -
19:59:10           Unexpected status code: 302
```

As far as I know it's a valid response and obviously useful to keep stable URLs over time.

**Comment by heirecka** [comment]
This happens again, most likely due to 51b97d0f0e44d7fce334be78a0881a7366b03a9a.

Should I open a new issues, or is this fine here?

**Comment by ximion** [comment]
Please file a new issue and attach a testcase so we can attempt to reproduce this issue! :-)
