### ISSUE TITLE
<languages> tag

### ISSUE THREAD

**Issue by JakobDev** [ximion/appstream#396]
While looking at the [AppStream Data of Flathub](https://hub.flathub.org/repo/appstream/x86_64/appstream.xml.gz) I found the <languages> tag multiple times, but is it not mentioned in the documentation. Is this Tag undocumented or is it just a older Tag that is no longer used?

**Comment by ximion** [comment]
It is part of AppStream catalog data, so, auto-generated: https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-languages
