### ISSUE TITLE
Validation ignores double values in Relations

### ISSUE THREAD

**Issue by JakobDev** [ximion/appstream#399]
Considering you have this in the Appstream:
```xml
<supports>
    <control>pointing</control>
</supports>
<requires>
    <control>pointing</control>
</requires>
```

The documentation says to supports:

> Installation on systems without the given control may still be permitted, but the software may not be easily usable.

The documentation says to requires:

> the software installer should refuse to install the software on devices which do not have at least one of the input methods.

So this above example means, that the installation is pretermitted and not pretermitted, which doesn't make any sense. So this should be invalid. But appstreamcli validate doesn't see a problem. It only prints a warning, that control should not be used in requires.

I think the validation should fail, when a entry (not only controll) appears in more than one relation blocks.

**Comment by ximion** [comment]
Indeed! There's so many things validate can check for though, that it will always be incomplete.
Patches welcome for this :-)

**Comment by JakobDev** [comment]
I'm not a C programmer and I have almost no experience in it, so unfortunately I can't write the patch.

**Comment by ximion** [comment]
That's fine, I will get to it eventually :-)
