### ISSUE TITLE
-DVAPI=ON fails with No rule to make target when using make %{?_smp_mflags}

### ISSUE THREAD

**Issue by Mailaender** [ximion/appstream#40]
```
[   91s] Scanning dependencies of target vapi
[   91s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/AppStream-0.9.2/build'
[   91s] make -f contrib/vapi/CMakeFiles/vapi.dir/build.make contrib/vapi/CMakeFiles/vapi.dir/build
[   91s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/AppStream-0.9.2/build'
[   91s] make[2]: *** No rule to make target 'src/AppStream-1.0.typelib', needed by 'contrib/vapi/appstream.vapi'.  Stop.
```

**Comment by ximion** [comment]
That's a weird issue, especially since the CI builds with `-DVAPI=ON`...
Could you paste the full log somewhere and link it here, and could you maybe also try this with a more recent version of AppStream? (maybe even Git master)

**Comment by Mailaender** [comment]
You can see the full build log when clicking on the red failed at https://build.opensuse.org/package/show/home:Mailaender:branches:X11:Pantheon/AppStream

**Comment by ximion** [comment]
```
[   79s] CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
[   79s]   CMake 3.1.0 or higher is required.  You are running version 2.8.11.2
```
=> You need a more recent cmake (on !Tumbleweed)...

Apart from that, could you build with a more recent version of AppStream (0.9.5 is current), and check if that issue is still present? The cause is the vapigen step being ordered before the GIR typelib is built, so building without parallel-make will also make this issue disappear (that's only a workaround, of course).

**Comment by Mailaender** [comment]
If I build with only one parallel thread in `make`, it works.

**Comment by ximion** [comment]
Can you please check if that issue is really gone in Git master / with that patch?

**Comment by Mailaender** [comment]
Fix confirmed.
