### ISSUE TITLE
metainfo-to-news: Change text output format to be Markdown

### ISSUE THREAD

**Issue by pwithnall** [ximion/appstream#405]
A lot of projects use Markdown formatting for their NEWS file now, since it’s human-readable, but also well defined as machine readable, and is rendered automatically when viewed online in GitHub or GitLab.

It would be useful if `appstreamcli metainfo-to-news` outputted valid Markdown, either by changing what the `text` format outputs, or adding a new `markdown` output format.

The main issue I’ve noticed with the existing text format is that the underline for the header is `~~~~~~` rather than the [`======` or `------` stipulated by Markdown](https://www.markdownguide.org/basic-syntax/#alternate-syntax). I’m not sure if any other changes in the formatting would be required to make it valid Markdown.

**Comment by ximion** [comment]
> [Markdown is] well defined as machine readable

That's quite the statement given the huge amount of different styles and interpretations, depending on which Markdown flavor you have ^^

But having this would indeed make sense, possibly even as default. `appstreamcli metainfo-to-news` already has a `--format` flag anyway, so adding a Markdown option should be possible.
The only thing I do remember that would need to be changed is indeed the tilde to some other header separator, but while we're at it, adding `###` to sections to render them properly may also be useful.
The only question is whether `news-to-metainfo` should also be able to read the new Markdown format. I think the answer to that question is yes, but it will make this task a bit more annoying to implement ;-)

**Comment by pwithnall** [comment]
Thank you!
