### ISSUE TITLE
Allow tagging screenshots as mobile

### ISSUE THREAD

**Issue by pwithnall** [ximion/appstream#410]
As suggested in [an issue filed against gnome-software](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1697), it would be slightly useful if screenshots in a metainfo file could have an attribute which indicates whether they’re of the full-size application, or of its smaller mobile UI.

If that information was present, we could prioritise showing the screenshots of the mobile version of an app, when gnome-software is running on a mobile device.

We can’t reliably work this out from the existing screenshot metadata, as smaller (pixel-wise) screenshots might be of dialogues or things which aren’t the main window in mobile mode.

This would only be useful for adaptive apps, and people can always scroll through the screenshots to find mobile ones, so it’s not a particularly urgent feature request.

**Comment by JakobDev** [comment]
There is no need to specify when a Device is mobile or not in the Appstream specification. Just specify that a Screenshot can have a mobile variant. The Appcenters could use e.g. the Shell to determine if it's mobile or not. If you use e.g. Plasma mobile, you have most likely a mobile device. If you are using the normal Plasma Desktop, you have most likely a Desktop device.

**Comment by pwithnall** [comment]
> There is no need to specify when a Device is mobile or not in the Appstream specification. Just specify that a Screenshot can have a mobile variant. The Appcenters could use e.g. the Shell to determine if it's mobile or not. If you use e.g. Plasma mobile, you have most likely a mobile device. If you are using the normal Plasma Desktop, you have most likely a Desktop device.

Yes, that’s what I had in mind.

The only addition to the spec needed here (I think) is something like `component_size="{xsmall,small,medium,..}"` on `<screenshot/>` elements. The value/semantics of the attribute should probably match whatever gets decided in #335, for all the same reasons as the decision making there.

**Comment by ximion** [comment]
I wonder how much this overlaps with the screenshot environment proposal (https://github.com/ximion/appstream/issues/304) - if the environment is `plasma:mobile` or `gnome:phosh` we'd kind of have the information already.
If we need to go even more detailed here, a screenshot would need to be coupled to a `display_length`: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-relations-display_length
But the human-readable names are deprecated, as nobody can agree on what they actually mean and the some GNOME designers found them not useful.
So, in that case we'd need to couple the `screenshot` (or just the screenshow `image`s?) to a `display_length` which would be any integer value. With that, I think we would be fairly accurate, but I think setting that value correctly will be quite a challenge for anybody writing metadata!

**Comment by ximion** [comment]
No. AppStream has no definition of what "mobile" is, and I really don't want to maintain one. And telling software center authors to "figure it out yourself" without any clear guidance will just lead to more problems down the road, with software centers interpreting the same thing differently and upstream authors confused as to what kind of screenshot they should actually put there to look good everywhere, and issues like how to prevent tablet UIs being shown on phones.
Believe me, we've done something like that in the past already and it was terrible. I'd rather discuss a little longer and find a declarative way for this, rather than doing a thing quickly that looks straightforward at first glance but will cause problems later (at which point we can't easily remove it anymore).

**Comment by JakobDev** [comment]
I think mobile is when programs run in mobile mode. This is currently bound to the Window size. You can see that when resizing some Gnome and KDE programs. At a specific size (I don't know a number), the Layout completely changes to a mobile Layout with a bottom bar. I don't know if this size is the same on all Apps. Currently the Software Centers of the 2 Mayor DEs KDE and Gnome have a mobile mode. So whats with this definition: If the Software Center itself in mobile mode, it should show the mobile Screenshots.

**Comment by sidt4** [comment]
FYI https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1697#note_1837659

**Comment by cahfofpai** [comment]
What is currently the suggested way to detect whether a screenshot is "mobile"? I would like to have a way to detect phone screenshots.

With the current / proposed ways (environment, screenshot size, aspect ratio or a combination of them) I see a few problems:
* only "Plasma Mobile" is registered (see https://github.com/ximion/appstream/blob/main/data/desktop-style-ids.txt), it lacks all the other mobile environments (Phosh, GNOME Mobile, SXMO, Lomiri, maybe more)
* a mobile environment does not guarantee that it is run on phones, as a mobile environment could also be run on other form factors (e.g. tablets, laptops, desktop computers)
* phone screenshots should not include window decorations, as the apps are always fullscreen
* at least some mobile compatible applications behave differently depending on the system / environment (e.g. the env var QT_QUICK_CONTROLS_MOBILE enables mobile controls if set to 1)

Here you can see the difference in the app menu of Kontrast when QT_QUICK_CONTROLS_MOBILE is set to 1:

![Screenshot_20241029_213151](https://github.com/user-attachments/assets/b42e4849-1d96-48ad-b729-0899863c0b4e)
