### ISSUE TITLE
Add Form-Factors to `appstreamcli make-desktop-file`

### ISSUE THREAD

**Issue by jsparber** [ximion/appstream#415]
See: https://adrienplazas.com/blog/2020/10/15/specify-form-factors-in-your-librem-5-apps.html

Related: https://github.com/ximion/appstream/issues/400#issuecomment-1126212382

**Comment by jsparber** [comment]
Actually, I'm not sure how to move forward on this, since we have the appropriate information now in appstream, but AFAIK the `.desktop` file entire is still needed.

**Comment by ximion** [comment]
Is it needed? Can't the DE simply get the required information from the metainfo file, or is there a reason why we want to duplicate the information in a desktop-entry file?

**Comment by jsparber** [comment]
I filled an issue against Phosh https://gitlab.gnome.org/World/Phosh/phosh/-/issues/817

**Comment by jsparber** [comment]
This can be closed since in future we will use metainfo file https://gitlab.gnome.org/World/Phosh/phosh/-/merge_requests/950
