### ISSUE TITLE
Where to add app screenshots?

### ISSUE THREAD

**Issue by agron2017** [ximion/appstream#416]
I would like to add a few screenshots and maybe even some videos to a few apps like audacity, cantata, vivaldi but there is no information as where to find the database, or xml files for such entries.
I initially asked on Manjaro Linux forum but the directed me here to appstream.

**Comment by ximion** [comment]
You indeed need to add this data to the upstream projects. Each project is managing their own data and is in full control of that, AppStream just defines how that data should look like.

If you are just interested in a list of metadata and screenshots, Flathub as well as distributions such as Debian generate that data from the upstream-provided files: https://appstream.debian.org/sid/main/metainfo/index.html
