### ISSUE TITLE
please consider renaming the master branch to main

### ISSUE THREAD

**Issue by juhp** [ximion/appstream#417]
These days it is considered good form and practice to call the principal branch of a project `main`.

This is rather easy to do particularly in github: almost a "1-click" operation in the project Settings.
Of course it may also need a few small `s/master/main/g` changes to a few files too, but should be straightforward enough.

It is not urgent, but please do consider if you could kindly make this change, thanks!

**Comment by ximion** [comment]
It breaks existing tools using this repository, is a workflow disruption and has zero benefits - except for consistency now that so many other projects have switched, and consistency is something I value a lot.

So, I'll likely do that switch when AppStream 1.0 releases, as that will be a pretty huge breaking change anyway, and it would make sense to do all of these at once and have people adjust their scripts :-)

**Comment by ximion** [comment]
Done :-)
