### ISSUE TITLE
What does the 'metainfo-filename-cid-mismatch' error signify?

### ISSUE THREAD

**Issue by quyykk** [ximion/appstream#435]
While building an AppImage it failed because of `metainfo-filename-cid-mismatch`. But what does the error mean? There is zero documentation on this anywhere. I tried to read the AppStream spec, but couldn't find anything that would explain this error.

Thanks!

**Comment by quyykk** [comment]
Found it, for all those coming from search engines: The `<id>` tag should be the name of the file: `<id>.appdata.xml` (or metainfo).

**Comment by ximion** [comment]
Yes. In case you are unsure about an error, you can also always pass `--explain` to get a verbose explanation: `appstreamcli validate --strict --explain <filename>`
