### ISSUE TITLE
Missing mimetypes information

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#44]
I was trying to make use of mimetypes from Discover UI, then I found it's not offered for any of the assets.

I'm not sure if it's actually no application offering it (then we should find out how to get them to) or whether it's the distribution not gathering the information properly.

**Comment by ximion** [comment]
Hmm, that information is definitely available.
Did you try with `appstreamcli` to get the information? E.g. `appstreamcli get org.kde.gwenview.desktop --details` shows it for me.

**Comment by aleixpol** [comment]
```
$ appstreamcli get org.kde.gwenview.desktop --details
Identifier: org.kde.gwenview.desktop [desktop]
Name: Gwenview
Summary: A simple image viewer
Package: gwenview
Homepage: http://gwenview.kde.org/
Icon: gwenview_gwenview.png
Description: 
  
        Gwenview is a fast and easy to use image viewer for KDE.
      
  
  Features:
   • Supports simple image manipulations: rotate, mirror, flip, and resize
   • Supports basic file management actions such as copy, move, delete, and others
   • Functions both as a standalone application and an embedded viewer in the Konqueror
  web browser
   • Can be extended using KIPI plugins.
Sample Screenshot URL: http://kde.org/images/screenshots/gwenview.png
Project Group: KDE
License: GPL-2.0+
Categories: Graphics, Viewer, Photography, 
```

**Comment by ximion** [comment]
Looking at the Archlinux metadata, it doesn't have mime information.
Could be a bug in appstream-generator, on Arch's side or in the libappstream XML writing code.
I suspect the latter right now.
