### ISSUE TITLE
can you suply a patch to be able to build with meson 0.59.4?

### ISSUE THREAD

**Issue by adcdam** [ximion/appstream#446]
what new feature has that needs version 0.62?

**Comment by eli-schwartz** [comment]
The project started requiring 0.62 in commit 8275d655477e40f12622f1819ed8f5fcdb9058b8 -- the description of that commit says a bit about what new features it was interested in.

**Comment by ximion** [comment]
It's mostly to get rid of tons of helper scripts and work around bugs related to XML translations in Meson.
So we need `install_symlink`, `i18n.itstool_join`, `fs.is_file` (and the whole filesystem module), the changed `i18n.gettext` semantic (with its return types complete) and probably more that I forgot.
So, backporting it would actually by super annoying, which was the reason for the version bump in the first place.
