### ISSUE TITLE
`appstreamcli validate` can’t be used on components with merge="append"

### ISSUE THREAD

**Issue by pwithnall** [ximion/appstream#455]
I’d like to validate [this file](https://gitlab.gnome.org/pwithnall/gnome-app-list/-/blob/main/org.gnome.Apps.Featured.xml) in CI. Its components are of the form:
```
  <component merge="append">
    <id>app.drey.Dialect</id>
    <custom>
      <value key="GnomeSoftware::FeatureTile">True</value>
    </custom>
  </component>
```

I [believe that’s valid](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#spec-asxml-tags).

However, when I run `appstreamcli validate --no-net ./org.gnome.Apps.Featured.xml` on it, I get a lot of errors of the form:
```
E: app.drey.Warp:~: component-summary-missing
E: org.gnome.DejaDup:~: component-summary-missing
E: com.github.geigi.cozy:~: component-summary-missing
E: com.github.hugolabe.Wike:~: component-name-missing
```

I assume I wouldn’t get these errors if the components had something to merge into, but since I’m validating this file on its own, rather than after composing with other AppStream files, there is nothing to merge the components into.

Would it be possible to elide errors about missing required elements (apart from `<id>`, which is [always required](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#spec-asxml-tags)) for components with `merge="append"` please? Or have I misunderstood how merging works (which is entirely possible)?

**Comment by ximion** [comment]
No, this should work exactly as you describe, the only tag that must be present for merge components is `<id/>` - so this is just the validator not validating correctly (I think it did have support for this a while back though, so maybe it broke and simply was never fixed since validating merge components is ultra-rare. Nevertheless, it's a bug that should be fixed.)

I'm currently travelling but can have a look on the weekend or next week :-)

**Comment by pwithnall** [comment]
Aha, OK, good to know that it’s meant to be supported. Getting it fixed would be nice, but from my point of view it’s a fairly low priority bug, so please don’t feel pressured to fix it soon. Unfortunately I don’t have time to look into it myself, sorry

**Comment by ximion** [comment]
It is low-priority, but also an easy fix, and changes like these take a long time to percolate through the ecosystem, so it's nice to have it resolved with the next release so people can start to rely on it (although admittedly for this feature the number of projects that need it will probably be below 5 ^^)
Should be fixed now, thank you for the detailed issue report!
