### ISSUE TITLE
Translations in Weblate being updated and translations lost

### ISSUE THREAD

**Issue by rffontenelle** [ximion/appstream#460]
Just in this morning I updated pt_BR translation in Weblate (from 85% went 100%), and while translating I proposed #459. Now, after having that MR merged, my translations went back to 85%, and the untranslated strings show the "Has been translated" check (means Weblate found a previous translation in its Translation Memory).

I'd like to suggest to review the configurations for the AppStream project in Weblate.

**Comment by ximion** [comment]
Looks like there was some collision between the Git repo copies, but it resolved itself... At the moment, Weblate says everything is fine, so I hope that's accurate.
Hopefully it will stay this way, sorry for the issue! Please reopen this issue report in case the issue isn't resolved!
