### ISSUE TITLE
url element and lang attribute

### ISSUE THREAD

**Issue by van-de-bugger** [ximion/appstream#462]
Is `lang` attribute allowed for `url` element?

For example if a project have localized homepage (or help page):

```
    <url type="homepage">http://example.org/en/home.html</url>
    <url type="homepage" lang="es">http://example.org/es/home.html</url>
    <url type="help">http://example.org/en/home.html</url>
    <url type="help" lang="es">http://example.org/es/home.html</url>
```

In such a case, appstreamcli 0.15.5 issues warnings:

    W: example:74: url-redefined homepage
    W: example:76: url-redefined help

Using `xml:lang` instead of plain `lang` does not help to avoid warnings. What is wrong with localized homapages, help, and other urls (donate, faq, bugtracker, etc)?

**Comment by ximion** [comment]
> Is `lang` attribute allowed for `url` element?

No. If it were, the specification would mention it.
We expect websites to just auto-redirect to localized pages based on the web browser locale.
