### ISSUE TITLE
Re-think device compatibility via controls and device_length

### ISSUE THREAD

**Issue by darkdragon-001** [ximion/appstream#481]
Currently both properties define _restrictions_ on compatibility. For a fully compatible device, there is currently no way to differentiate between _not set_ and _fully compatible_ which makes a huge difference in my opinion.

Since one is usually interested in _compatibility_, maybe it makes sense to merge `requires`, `recommends`, `suggests` into a single `compatible`. This will make it also make the logic to filter out incompatible apps much easier while optionally keeping apps with unknown compatibility.

**Comment by ximion** [comment]
This has been discussed to death before...
 * We do not want to define a "works on mobile" parameter, because what "mobile" is is constantly changing, so defining requirements on the device makes a lot more sense
 * If no restrictions are set, compatibility is "undefined", which historically means "assume works on desktops with big screens and mouse & keyboard only"
 * If you want to define compatibility with a certain piece of hardware without restricting installability, use the `supports` tag, that's what it's for (and where for example any `control` item should go now, unless you want to prohibit software installation on e.g. any device without touch screen).

**Comment by darkdragon-001** [comment]
I need a rating algorithm for https://linuxphoneapps.org/ which is given users information about the mobile compatibility such that they can choose the most fitting one app to install on their device.

Could you draft an algorithm which will convert the `controls` and `display_length` AppStream properties to 0 to 5 stars mobile compatibility rating since this is what the user actually cares about?

**Comment by ximion** [comment]
Sure, this would fit the project's goals very well. We also already have `as_relation_is_satisfied` to check if a relation is satisfied on the current system, so a feature like this would complement it.

We do however not give some kind of rating, it's more a binary "runs" or "runs not" and an additional textual hint of "also provides the following X components that are present on your system".
But I don't think it's hard to devise an algorithm that scores that. The primary issue is that once again we need to define what "mobile" would even be (is a tablet mobile? Is a phablet mobile? Is a folding phone a mobile device? At which laptop size do those become "mobile" and not "desktop" anymore?).

**Comment by darkdragon-001** [comment]
On the website, we don't have this information about the current system. Also as mobile, we are currently counting what most people perceive as smartphones (tablets will come later). It is also not important to cover every edge case but instead give people a rough estimate which apps to try first. Instead of thinking about defining screen sizes, it might be much more helpful to have the information that a developer is developing and testing this application for smartphones (something likes Purisn's form factor). This will also mean the developer will adapt to trends in the market like changing screen sizes and is therefore much more valuable imo than defining arbitrary screen sizes. I am struggling exactly with these questions like screen sizes and unset properties meaning desktop or just not incompatible with anything. That's why I am interested in a detailed suggestion about an algorithm instead of abstract "should be easy".

**Comment by ximion** [comment]
The patch resolves this issue, by making AppStream provide default facilities to calculate a "compatibility score" for given hardware. The given hardware may be the current system (or any real system) or a preset configuration for a bunch of chassis types, like handsets.

That way, you can filter out phone-compatible apps fairly easily, using Python code like this:
```python
import gi
gi.require_version('AppStream', '1.0')
from gi.repository import AppStream

pool = AppStream.Pool()
pool.load()

sysinfo_tmpl = AppStream.SystemInfo.new_template_for_chassis(AppStream.ChassisKind.HANDSET)

cpts = pool.get_components().array()
for cpt in cpts:
    score, _ = cpt.get_system_compatibility_score(sysinfo_tmpl)
    if score > 50:
        print('[{:3d}%]: {}'.format(score, cpt.get_id()))
``` 

While writing this is found that there's actually very few apps that declare metadata correctly for this, so a feature like this was indeed badly needed. I will add some more convenience stuff to `appstreamcli` in follow-up commits, to make this easier for metadata authors to understand, and to analyze their app for compatibility locally.

**Comment by ximion** [comment]
You can now also use 
``` 
appstreamcli check-syscompat --details ./tests/samples/syscompat/org.example.phoneapp.metainfo.xml
```
on any MetaInfo file or component-ID to check it against the chassis template systems and get a quick overview over which chassis types your app will likely show up on / be considered to be able to run on.
