### ISSUE TITLE
Better definition of control

### ISSUE THREAD

**Issue by JakobDev** [ximion/appstream#487]
The <control/>tag has a problem. the documentation says the following:

> This item type can be used to indicate support for or require certain ways a user can control the software.

This sound easy at first look, but let's take a look at Emulators e.g. [Dolphin](https://dolphin-emu.org). The Emulator is there to play Video Games, so it supports of course a gamepad. to do that. You can map your Keyboard Keys to play the Games, but it is not a good experience compares to a Gamepad. In other words: It is recommend to use a Gamepad. But there's a Problem: While it is recommend to use a Gamepad to play the Games itself, the Emulator itself can not controlled with a Gamepad. If you want to do things like opening a Game or changing the Config, it can not be done with a Gamepad. That means, if you try to build a Linux based TV console that should be controlled by only using a Gamepad, you can't use Dolphin. To which value should we set `gamepad` here?

Now let's take a look at [RetroArch](https://www.retroarch.com) in comparison. t can be fully controlled with a Gamepad. You don't need a Mouse and Keyboard at all.

How should we set the `gamepad` tag to indicate, that it is highly recommend to use a Gamepad with both, but only RetroArch can be fully controlled with a Gamepad?

**Comment by ximion** [comment]
For Dolphin:
```xml
<requires>
    <control>keyboard</control>
</requires>
<supports>
    <control>pointing</control>
    <control>gamepad</control>
</supports>
```

For RetroArch:
```xml
<supports>
    <control>keyboard</control>
    <control>pointing</control>
    <control>gamepad</control>
</supports>
```

I don't think we can ever make this suit all complexities, unless be embed a script file or some human language text. But the current solution is good enough to give people a rough idea as to what they can expect.
