### ISSUE TITLE
`appstreamcli validate --pedantic --no-net` reports missing screenshots even though they exist at the given URLs and even though the `--no-net` option is given

### ISSUE THREAD

**Issue by mike-fabian** [ximion/appstream#494]
Original bug report here: https://bugzilla.redhat.com/show_bug.cgi?id=2171887

appstream-0.16.1-1.fc38.x86_64

https://download.copr.fedorainfracloud.org/results/mfabian/ibus-typing-booster/fedora-rawhide-x86_64/05549617-ibus-typing-booster/build.log.gz

fails with 

+ appstreamcli validate --pedantic --no-net /builddir/build/BUILDROOT/ibus-typing-booster-2.21.4-1.fc39.x86_64//usr/share/metainfo/emoji-picker.appdata.xml /builddir/build/BUILDROOT/ibus-typing-booster-2.21.4-1.fc39.x86_64//usr/share/metainfo/typing-booster.appdata.xml
emoji-picker.appdata.xml
  E: org.freedesktop.ibus.engine.typing_booster.emoji_picker:18: screenshot-image-source-missing
emoji-picker.appdata.xml
  E: org.freedesktop.ibus.engine.typing_booster.emoji_picker:18: screenshot-image-source-missing
typing-booster.appdata.xml
  E: org.freedesktop.ibus.engine.typing_booster:22: screenshot-image-source-missing
✘ Validation failed: errors: 3
error: Bad exit status from /var/tmp/rpm-tmp.edFYrs (%check)
    Bad exit status from /var/tmp/rpm-tmp.edFYrs (%check)

But the files `appstreamcli validate --pedantic --no-net` complains about **do** have screenshot sources:

https://github.com/mike-fabian/ibus-typing-booster/blob/main/emoji-picker.appdata.xml

contains:

```xml
  <screenshots>
    <screenshot type="default">
      <image type="source" xml:lang="en">
        https://mike-fabian.github.io/ibus-typing-booster/images/emoji-picker.png
      </image>
      <caption>Emoji Picker screenshot</caption>
    </screenshot>
  </screenshots>
```

https://github.com/mike-fabian/ibus-typing-booster/blob/main/typing-booster.appdata.xml

contains:

```xml
  <screenshots>
    <screenshot type="default">
      <image type="source" width="956" height="233" xml:lang="en">
      https://mike-fabian.github.io/ibus-typing-booster/images/typing-emoji-and-context-sensitive-completion.png
      </image>
      <caption>Typing Booster screenshot</caption>
    </screenshot>
    <screenshot>
      <video container="webm" codec="vp9" xml:lang="en">
        https://mike-fabian.github.io/ibus-typing-booster/videos/overview-demo-setup-use-typing-booster-emoji-picker.webm
      </video>
      <caption>Typing booster demo video</caption>
    </screenshot>
  </screenshots>
```

These screenshots are given as URLs, and they point to existing files.

But I think because of the `--no-net` option `appstreamcli validate` should not try to validate these at all.

**Comment by ximion** [comment]
That is because of the `xml:lang="en"` language specifiers - there *must* be one image in the default locale, and there *can* be some translated ones, but having only translated images is not okay.
The error message is quite confusing indeed though...

**Comment by ximion** [comment]
Oh, and `--no-net` means we will not connect to the internet, but anything that can be validated offline still will be.

**Comment by mike-fabian** [comment]
> Oh, and `--no-net` means we will not connect to the internet, but anything that can be validated offline still will be.

I understood that, but I misunderstood the error message. I thought `screenshot-image-source-missing` meant that the file https://mike-fabian.github.io/ibus-typing-booster/images/emoji-picker.png does not exist. But it does exist and I wondered why it tried to verify the existence of that remote file at all because I had given the `--no-net` option to avoid checks needing Internet access.

So I just misunderstood the error message. Thank you for pointing out that I just need to remove the `xml:lang="en"`.

**Comment by ximion** [comment]
> I understood that, but I misunderstood the error message.

Yeah, the message is not ideal in this case. If in doubt, you can always pass `--explain` to `appstreamcli validate` as well and get a detailed description of what the error actually is. I am leaving this bug open as a reminder to improve the error message :-)

> Use appstreamcli not appstream-util. The latter is unmaintained.

That is correct - maybe @hughsie know if that should be updated and how :-)
That webpage could also link to https://www.freedesktop.org/software/appstream/metainfocreator/#/ for an easier way to create metadata, if you don't want to read much documentation.
