### ISSUE TITLE
Two tests started to fail with 0.16.2

### ISSUE THREAD

**Issue by heirecka** [ximion/appstream#495]
They passed with 0.16.1

```
8/9 as-test_qt                      FAIL            0.02s   exit status 1
>>> LD_LIBRARY_PATH=/var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/_build/qt/:/var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/_build/src/ MALLOC_PERTURB_=247 /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/_build/qt/tests/as-test_qt
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
********* Start testing of PoolReadTest *********
Config: Using QtTest library 5.15.9, Qt 5.15.9 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 13.1.0), exherbo unknown
PASS   : PoolReadTest::initTestCase()
FAIL!  : PoolReadTest::testRead01() Compared values are not the same
   Actual   (cpts.size()): 21
   Expected (20)         : 20
   Loc: [../AppStream-0.16.2/qt/tests/asqt-pool-test.cpp(66)]
PASS   : PoolReadTest::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 8ms
********* Finished testing of PoolReadTest *********
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

9/9 as-test_pool                    FAIL            0.27s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/_build/src/ MALLOC_PERTURB_=51 /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/_build/tests/as-test_pool /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
TAP version 13
# random seed: R02S09bbc19c4f57b46faf92f94ceeae9a82
1..8
# Start of AppStream tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
# DEBUG: run AsPool:load
# DEBUG: Not pruning cache: Default paths were changed.
# DEBUG: run AsPool:load_catalog_data
# DEBUG: Searching for XML data in: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/samples/catalog/xml
# DEBUG: Reading: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/samples/catalog/xml/limba_6375db4bb7186c39a4860544884575f7.xml
# DEBUG: Reading: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/samples/catalog/xml/merges.xml
# DEBUG: Reading: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/samples/catalog/xml/foobar-1.xml
# DEBUG: Reading: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/samples/catalog/xml/suggestions.xml
# DEBUG: Reading: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/work/AppStream-0.16.2/tests/samples/catalog/xml/lvfs-gdpr.xml
# DEBUG: Merged data for '[2] system/package/os/links2.desktop/*' <<- '[2] system/*/as-testsuite/links2.desktop/*'
# DEBUG: Merged data for '[2] system/package/os/kiki.desktop/*' <<- '[2] system/*/as-testsuite/kiki.desktop/*'
# DEBUG: Merged data for '[2] system/package/os/literki.desktop/*' <<- '[2] system/*/as-testsuite/literki.desktop/*'
# DEBUG: Storing cache data for section: system:C-97627993973a92d7c59dc6aa8658c0c5
# DEBUG: Writing cache file: /var/tmp/paludis/build/dev-libs-appstream-0.16.2/temp/as-test-cache-dummy/OH7T41/C-97627993973a92d7c59dc6aa8658c0c5.xb
# DEBUG: run AsPool:get_components_by_id
# DEBUG: Querying `components/component/id[lower-case(text())=?]/..` in system:C-97627993973a92d7c59dc6aa8658c0c5
not ok /AppStream/PoolRead - ERROR:../AppStream-0.16.2/tests/test-pool.c:332:test_pool_read: assertion failed (result->len == 0): (1 == 0)
Bail out!
stderr:
**
ERROR:../AppStream-0.16.2/tests/test-pool.c:332:test_pool_read: assertion failed (result->len == 0): (1 == 0)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

```

**Comment by ximion** [comment]
Works just fine on our CI: https://github.com/ximion/appstream/actions/runs/4812488432

Is there anything unusual about your environment?

**Comment by heirecka** [comment]
Not that I am aware of. I'm guessing it may caused by some newer dependency, considering the tests pass for Debian. Unfortunately the tests seem to fail to build for Fedora at all, which may be closer to my setup.

Anything I could look for in particular?

**Comment by ximion** [comment]
Fedora failures are just due to a bug in GCC 13, if you compile with less pedantic settings (omit `-Dmaintainer`), it works just fine. 
Instructions how to reproduce this environment would be helpful...

**Comment by heirecka** [comment]
If you have some CPU cycles to build a few deps, which are not included in the container:

docker pull exherbo/exherbo_ci
docker run -it bash
Inside the container:
chgrp paludisbuild /dev/tty
cave resolve repository/desktop -x
cave resolve appstream -x

will build 0.16.1

To build 0.16.2
pushd /var/db/paludis/repositories/desktop/
git mv packages/dev-libs/appstream/appstream-0.16.{1,2}.exheres-0
git commit -a -m "appstream: Version bump to 0.16.2"
cave resolve appstream -x

**Comment by ximion** [comment]
Hmm, I can reproduce this with your commands, but if I run the tests in that container directly, the issue does not occur.
Is there a way to enter the exact build environment that cave resolve seems to create?

**Comment by ximion** [comment]
I tried to `export` the environment and apply it to the surrounding container, which did work, but I still can't reproduce the issue outside of what `cave resolve` does.
Is there anything besides environment variables (syscall filtering? other sandboxing?) that `cave` does? This issue is extremely odd...

**Comment by krop** [comment]
FTR, I see the same failures in openSUSE with different archs / compiler versions (GCC  7 & 13).

meson is invoked with `/usr/bin/meson setup --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-suse-linux -Dqt=true -Dcompose=true -Dvapi=true -Ddocs=false -Dapidocs=false -Dstemming=false`

and compiler flags are the same as usual: `-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g`

**Comment by ximion** [comment]
Is there anyway I can reproduce that build environment somehow to poke around in it and see why it might be failing?

**Comment by heirecka** [comment]
Oh, sorry I seem to have missed the notification and thanks for poking!

> I tried to `export` the environment and apply it to the surrounding container, which did work, but I still can't reproduce the issue outside of what `cave resolve` does. Is there anything besides environment variables (syscall filtering? other sandboxing?) that `cave` does? This issue is extremely odd...

Yes, there's a ptrace-based sandbox, which can be disabled by exporting PALUDIS_DO_NOTHING_SANDBOXY=1. But that doesn't seem to be the cause.

**Comment by krop** [comment]
> Is there anyway I can reproduce that build environment somehow to poke around in it and see why it might be failing?

Only if you have an account on build.opensuse.org.
then:
```
osc co home:krop:branches:KDE:Frameworks5 AppStream
osc build openSUSE_Factory x86_64
```

**Comment by ximion** [comment]
> > Is there anyway I can reproduce that build environment somehow to poke around in it and see why it might be failing?
> 
> Only if you have an account on build.opensuse.org. then:
> 
> ```
> osc co home:krop:branches:KDE:Frameworks5 AppStream
> osc build openSUSE_Factory x86_64
> ```

Will that build locally and do I can an environment that I can get a shell in to run binaries, compile code and maybe even run gdb?
Running this on Debian still fails, I got as far as `Can't locate Build.pm in @INC (you may need to install the Build module) (@INC contains: /usr/lib/build /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /usr/lib/obs/service/source_validators/helpers/spec_query line 10.`, but maybe I ran rpmbuild the package manually - but not sure if that would be enough to reproduce this.

**Comment by krop** [comment]
I built it locally and tried running the tests manually.

as-test_pool crashes after complaining about datadir:

```
abuild@yuuko:~/rpmbuild/BUILD/AppStream-0.16.2/x86_64-suse-linux/tests> ./as-test_pool
**
ERROR:../tests/test-pool.c:1049:main: 'datadir' should not be NULL
Bail out! ERROR:../tests/test-pool.c:1049:main: 'datadir' should not be NULL
Aborted (core dumped)

```

**Comment by krop** [comment]
running the test in valgrind doesn't help and gdb doesn't give more clues
```
ERROR:../tests/test-pool.c:332:test_pool_read: assertion failed (result->len == 0): (1 == 0)
not ok /AppStream/PoolRead - ERROR:../tests/test-pool.c:332:test_pool_read: assertion failed (result->len == 0): (1 == 0)
Bail out!

Thread 1 "as-test_pool" received signal SIGABRT, Aborted.
0x00007ffff7a20a7c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install liblzma5-debuginfo-5.4.3-1.1.x86_64
(gdb) bt
#0  0x00007ffff7a20a7c in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff79cf226 in raise () at /lib64/libc.so.6
#2  0x00007ffff79b7897 in abort () at /lib64/libc.so.6
#3  0x00007ffff7dfeeee in g_assertion_message (domain=<optimized out>, file=0x555555565f63 "../tests/test-pool.c", line=<optimized out>, func=<optimized out>, message=<optimized out>) at ../glib/gtestutils.c:3450
#4  0x00007ffff7e65398 in g_assertion_message_cmpnum
    (domain=domain@entry=0x0, file=file@entry=0x555555565f63 "../tests/test-pool.c", line=line@entry=332, func=func@entry=0x5555555665c0 <__func__.0> "test_pool_read", expr=expr@entry=0x555555565fae "result->len == 0", arg1=1, cmp=cmp@entry=0x555555565fab "==", arg2=0, numtype=105 'i') at ../glib/gtestutils.c:3509
#5  0x0000555555561350 in test_pool_read () at ../tests/test-pool.c:332
#6  0x00007ffff7e63bee in test_case_run (tc=0x55555557d170) at ../glib/gtestutils.c:3114
#7  g_test_run_suite_internal (suite=suite@entry=0x55555557d270, path=path@entry=0x0) at ../glib/gtestutils.c:3209
#8  0x00007ffff7e639e3 in g_test_run_suite_internal (suite=suite@entry=0x55555557ccc0, path=path@entry=0x0) at ../glib/gtestutils.c:3228
#9  0x00007ffff7e64102 in g_test_run_suite (suite=suite@entry=0x55555557ccc0) at ../glib/gtestutils.c:3308
#10 0x00007ffff7e64188 in g_test_run () at ../glib/gtestutils.c:2415
#11 0x000055555555b9ad in main (argc=<optimized out>, argv=<optimized out>) at ../tests/test-pool.c:1077
```

(test is run in a local chroot reproducing our build environment)

**Comment by ximion** [comment]
So, this issue randomly appeared in one of Debian's containers, so I had a nice opportunity to reproduce it. And I am puzzled that this bug didn't show up more prominently years ago...

Can you please test the attached patch and see if the issue goes away for good?

**Comment by heirecka** [comment]
It does indeed. Thank you very much!

**Comment by ximion** [comment]
Neat, I'll backport it to the 0.16.x branch then :-)
Thank you for reporting the issue!
