### ISSUE TITLE
Invalid file is reported as valid

### ISSUE THREAD

**Issue by JakobDev** [ximion/appstream#498]
[This file](https://codeberg.org/JakobDev/jdReplace/src/commit/fe8112ec870e9cab8a7e35806e35a73b26911d7e/deploy/page.codeberg.JakobDev.jdReplace.metainfo.xml) contains a typo in Line 16
```xml
<caption>The Window</caption>>
```
It has a `>` to much. But `appstreamcli` says the file is valid.

**Comment by ximion** [comment]
Weird... That means libxml2 parses this without any issues!

**Comment by ximion** [comment]
Unfortunately, this needs to be addressed (efficiently, at least) in libxml2, I don't think working around it in AppStream is a good idea...
At least we do set the parser to strict mode now when validating, which hopefully should make it catch more issues - except this one...
