### ISSUE TITLE
Compose is confused by IDs with trailing .desktop

### ISSUE THREAD

**Issue by barthalion** [ximion/appstream#500]
We have deployed libappstream-enabled flatpak-builder to Flathub today and we're observing some apps fail our poor man's icon check. It affects apps that use trailing `.desktop` in the ID field, such as [Exodus](https://github.com/flathub/io.exodus.Exodus/blob/master/io.exodus.Exodus.appdata.xml) and [labplot](https://github.com/KDE/labplot/blob/master/org.kde.labplot2.appdata.xml). The compose commands fails to find either the desktop or icon file so the final catalogue doesn't contain it.

Example build: https://buildbot.flathub.org/#/builders/5/builds/5598

**Comment by barthalion** [comment]
```
FB: Running: appstreamcli compose --prefix=/ --origin=io.exodus.Exodus --media-baseurl=https://dl.flathub.org/media --media-dir=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-C690oM/files/share/app-info/media --result-root=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-C690oM/files --data-dir=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-C690oM/files/share/app-info/xmls --icons-dir=/srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-C690oM/files/share/app-info/icons/flatpak '--components=io.exodus.Exodus,io.exodus.Exodus.desktop' /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-C690oM/files
Only accepting components: io.exodus.Exodus, io.exodus.Exodus.desktop
Processing directory: /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-C690oM/files
Composing metadata...
Success!
```

Please note we needed to add desktop-suffixed variant explicitly like here: ` '--components=io.exodus.Exodus,io.exodus.Exodus.desktop'`. This does look like a bug as historically ID was the desktop file name.

**Comment by ximion** [comment]
Very odd, there is code that will search for icons/desktop files based on heuristics using the component-ID... I wonder whether this is some kind of capitalization issue.

I'll have to play around with that a bit.

**Comment by ximion** [comment]
I can't reproduce this for Exodus - but I did have to move its metainfo file into the `metainfo` directory (from the `appdata` directory) for anything to be processed at all. But then, everything worked just fine, and the desktop-entry file was definitely found.

@barthalion You are using AppStream 0.16.2, right?

**Comment by barthalion** [comment]
Yeah, we bundle 0.16.2 at https://github.com/flathub/org.flatpak.Builder/blob/master/org.flatpak.Builder.json#L408, although the runtime itself ships 0.15.6. May it be something, somewhere gets confused?

**Comment by barthalion** [comment]
The full procedure to reproduce this build failure would be something along this:

```
git clone https://github.com/flathub/io.exodus.Exodus
cd io.exodus.Exodus
flatpak run org.flatpak.Builder --verbose --user --sandbox --force-clean --repo=repo --install-deps-from=flathub --default-branch=localtest --install --bundle-sources builddir io.exodus.Exodus.json
zgrep "<icon type=\\"remote\\">" builddir/*/share/app-info/xmls/io.exodus.Exodus.xml.gz ||  test -f builddir/*/share/app-info/icons/flatpak/128x128/io.exodus.Exodus.png
```

**Comment by ximion** [comment]
Is there a way to switch `appstreamcli compose` to verbose mode when building like this?

**Comment by barthalion** [comment]
I'm afraid not, but I will quickly patch it.

**Comment by ximion** [comment]
I'm running your command, but it seems stuck at `Installing runtime/org.freedesktop.Sdk/x86_64/22.08` for 20min now... I'll give it some more time.

**Comment by barthalion** [comment]
```
** (appstreamcli:33): DEBUG: 02:05:03.372: run appstreamcli: compose
Only accepting components: io.exodus.Exodus, io.exodus.Exodus.desktop
Processing directory: /home/bpiotrowski/.cache/flatpak-builder/rofiles/rofiles-NYc4gw/files
Composing metadata...
** (appstreamcli-compose:33): DEBUG: 02:05:03.386: No media export directory set, but icon 128x128@1 is set for remote delivery. Disabling remote for this icon type.
** (appstreamcli-compose:33): DEBUG: 02:05:03.386: No media export directory set, but icon 128x128@2 is set for remote delivery. Disabling remote for this icon type.
** (appstreamcli-compose:33): DEBUG: 02:05:03.386: No media export directory set, but screenshots are supposed to be stored. Disabling screenshot storage.
** (appstreamcli-compose:33): DEBUG: 02:05:03.386: Will use temporary directory '/tmp/as-compose_w6Dazq' and delete it after this run.
** (appstreamcli-compose:33): DEBUG: 02:05:03.388: Creating contents index for directory: /home/bpiotrowski/.cache/flatpak-builder/rofiles/rofiles-NYc4gw/files
** (appstreamcli-compose:33): DEBUG: 02:05:03.396: Index done for directory: /home/bpiotrowski/.cache/flatpak-builder/rofiles/rofiles-NYc4gw/files
** (appstreamcli-compose:33): DEBUG: 02:05:03.396: Looking for metainfo files in: /share/metainfo
** (appstreamcli-compose:33): DEBUG: 02:05:03.396: Processing: /share/metainfo/io.exodus.Exodus.metainfo.xml
** (appstreamcli-compose:33): DEBUG: 02:05:03.397: Reading: /share/applications/io.exodus.Exodus.desktop
** (appstreamcli-compose:33): DEBUG: 02:05:03.412: Saving icon: /home/bpiotrowski/.cache/flatpak-builder/rofiles/rofiles-NYc4gw/files/share/app-info/icons/flatpak/64x64/io.exodus.Exodus.desktop.png
** (appstreamcli-compose:33): DEBUG: 02:05:03.425: Saving icon: /home/bpiotrowski/.cache/flatpak-builder/rofiles/rofiles-NYc4gw/files/share/app-info/icons/flatpak/128x128/io.exodus.Exodus.desktop.png
(appstreamcli-compose:33): GLib-GIO-DEBUG: 02:05:04.116: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
** (appstreamcli-compose:33): DEBUG: 02:05:05.084: Removing temporary directory '/tmp/as-compose_w6Dazq'
Success!
```

```
~/d/f/io.exodus.Exodus master• ❱ zcat builddir/files/share/app-info/xmls/io.exodus.Exodus.xml.gz | grep '<icon'
    <icon type="cached" width="64" height="64">io.exodus.Exodus.desktop.png</icon>
    <icon type="cached" width="128" height="128">io.exodus.Exodus.desktop.png</icon>
    <icon type="stock">io.exodus.Exodus</icon>
```

**Comment by ximion** [comment]
So... This looks fine, doesn't it? Or am I completely misunderstanding the issue?

**Comment by barthalion** [comment]
The problem here is that the `.desktop` part of the ID is not correctly stripped for icon filename. It shouldn't be `io.exodus.Exodus.desktop.png`, the ID is `io.exodus.Exodus`.

**Comment by barthalion** [comment]
Admittedly, the exported icons seem fine here with a local Exodus build, so maybe it's just an issue of consistency to always use the same ID everywhere. Will need to poke around further when I get to "the office".

**Comment by ximion** [comment]
> The problem here is that the `.desktop` part of the ID is not correctly stripped for icon filename.

Ah! Sorry, I completely missed the point of this issue report then at first and was looking into the wrong thing entirely 🙃

> so maybe it's just an issue of consistency to always use the same ID everywhere

Exactly, the compose tool always uses the component-ID verbatim as icon filename, because messing around with it generally causes issues and namespace collisions (there is apps like `com.spotify.desktop` if I recall correctly, where the last component legitimately is "desktop" and has nothing to do with a desktop-entry file.

We could potentially add a hack to compose which adjusts naming just for the icons, but I'd need to run some tests to see if that would break anything else (I think it might confuse `appstream-generator`, but I'd have to check).

Would it be a large issue to have Flathub check for the exact match of component-ID + .png/.svg? What problems doe this currently cause, is it just a sanity check failing that could be adjusted, or is there more issues to be expected down the line?

**Comment by barthalion** [comment]
Yeah, let's close it. I think we're fine with the relaxed check on our end, as the compose command seems more thorough than ours ever was.
