### ISSUE TITLE
compose: Provide a switch to use absolute URLs instead of media_baseurl

### ISSUE THREAD

**Issue by barthalion** [ximion/appstream#505]
[A comment](https://github.com/flatpak/flatpak-builder/pull/517#issuecomment-1610292586) in the neighbouring repository mentions a knob that would allow avoiding `media_baseurl` when `--media-baseurl` and `--media-dir` are used. We would like to use that for Flathub to keep backwards compatibility with distributions using too old appstream-glib/libappstream to understand `media_baseurl`  attribute, but it's at least undocumented, or not available with CLI.

**Comment by razzeee** [comment]
FYI, this is one of the issues we need to have solved to migrate flathub (again)

**Comment by ximion** [comment]
Sorry, I had a bit too much to do the past months, currently working through the task backlog.

Looks like this feature is actually implemented, but completely unusable / broken (as most people don't seem to want their software stores to callout to random websites).

I'll have a look if there's a sensible way to implement this :-)

**Comment by ximion** [comment]
This patch ^ adds this feature to compose.
I also backported it to the stable series, at it is fairly small and self-contained (even though it's a new feature).
