### ISSUE TITLE
[Feature request] add link to the build manifest for flatpak etc

### ISSUE THREAD

**Issue by endim8** [ximion/appstream#506]
This would allow software like Gnome Software to link and display the manifest for users, like on the flathub site: https://flathub.org/en-GB/apps/com.github.rafostar.Clapper.
this would allow users to inspect the manifest, and report flatpak/manifest specific issues more easily.

Example manifest link:https://github.com/flathub/com.github.rafostar.Clapper

this was requested in gnome software a week ago: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2216

also see: https://github.com/flatpak/flatpak/issues/5463

**Comment by JakobDev** [comment]
[This is already possible](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines#manifest-location)

**Comment by endim8** [comment]
ohh! perfect, thank you :)
