### ISSUE TITLE
quickstart docs unclear about releases/provides tag

### ISSUE THREAD

**Issue by cbm755** [ximion/appstream#51]
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

`4.1.4. Suggested metadata file contents`

`You may choose to add these tags as well, if you need them. `

Ok so "I may".  I'm not sure if I "need them" or not, so I read further...

````
<releases/>
    The application metainfo should at least provide one <releases/> tag
````
Now its "I should".

The  `<provides>` tag is similarly unclear to me.

**Comment by ximion** [comment]
Jup, it's definitely a "can be added" not a "must be present". We do recommend the tags though.

**Comment by ximion** [comment]
The wording should be more clear now - please check if this makes sense to you :-)

**Comment by cbm755** [comment]
> The application metainfo may at least provides one 

This sounds awkward, and `provides` should not have an s.

Is this better?

`The application metainfo may include a single <code>&lt;releases/&gt;</code> tag...`

(unless there is a common reason to have more than one?!)

**Comment by ximion** [comment]
Yes, there must never be more than one `<releases/>` tag, in fact. It may have multiple `release` subnodes though.

**Comment by cbm755** [comment]
> Yes, there must never be more than one |<releases/>| tag, in fact. It
> may have multiple |release| subnodes though.

Good, but your update implies more than one ok.  You have my suggested 
wording...

**Comment by ximion** [comment]
> Good, but your update implies more than one ok
Since this isn't the actual specification, but a supplementary document, I think this is fine. Changing "one" to "a single" would make sense, but having the former is also okay, IMHO. It isn't confusing.

**Comment by cbm755** [comment]
> The application metainfo may at least provides one 

But this this sentence is not parse-able:  delete "at least" and drop the "s" from provide.
