### ISSUE TITLE
symlink with wrong argument order

### ISSUE THREAD

**Issue by hsitter** [ximion/appstream#513]
https://github.com/ximion/appstream/blob/bb5487753930220295fafb731f90420aeb64f6de/src/as-distro-extras.c#L380

I may be going insane but I'm seeing this with a build from main:

```
414505 symlink("/var/lib/swcatalog/yaml/archive.neon.kde.org_unstable_dists_jammy_main_dep11_Components-amd64.yml.gz", "/var/lib/apt/lists/archive.neon.kde.org_unstable_dists_jammy_main_dep11_Components-amd64.yml.gz") = -1 EEXIST (File exists)
```

which seems the wrong way around given the manpage

```
int symlink(const char *target, const char *linkpath);
       symlink() creates a symbolic link named linkpath which contains the string target.
```

**Comment by ximion** [comment]
Yes, looks like https://github.com/ximion/appstream/commit/808326a35895ea7b343eef3b5a9e67928c4af99d broke this.
