### ISSUE TITLE
Would be nice, but I don't intend to add a JSON parser or JSON writer dependency to AppStream, and switching libyaml to JSON mode would be quite a pain to implement reliably.

### ISSUE THREAD

**Issue by Mrrthorng** [ximion/appstream#521]
Would be nice, but I don't intend to add a JSON parser or JSON writer dependency to AppStream, and switching libyaml to JSON mode would be quite a pain to implement reliably.
So this feature isn't super likely to be added any time soon...

_Originally posted by @ximion in https://github.com/ximion/appstream/issues/449#issuecomment-1354041649_

**Comment by ximion** [comment]
Not a separate bug, please reply to issues instead of filing new ones :-)
