### ISSUE TITLE
add meson option to skip docs

### ISSUE THREAD

**Issue by alex-tee** [ximion/appstream#523]
I don't need the stuff in docs/ for my build and it adds extra requirements like xsltproc. It should be controlled via a meson option like "-Dbuild-manual=true/false"

**Comment by ximion** [comment]
https://github.com/ximion/appstream/blob/main/meson_options.txt#L42 (`-Ddocs=false`)

Manual pages will always be built though, those are part of the interface which we always want to have available, especially since many distributions require them.

**Comment by alex-tee** [comment]
okay let's close this then. still not sure what is needed to build them but it doesn't affect me. i'll use my fork until someone packages this on homebrew/msys2
