### ISSUE TITLE
question for appstream on rebornos aka arch linux.

### ISSUE THREAD

**Issue by DOOMMARINE117** [ximion/appstream#535]
i was told arch linux devs wont fix appstream no package found error.

so is appstream really need now on arch? how to remove them if i dont them? 

no package found error, can it be solved?

**Comment by ximion** [comment]
I do not understand what you mean. Which error, when does it happen, in which program?
In general though, if it's an issue with Arch itself, it is for Arch to resolve.

**Comment by DOOMMARINE117** [comment]
> I do not understand what you mean. Which error, when does it happen, in which program? In general though, if it's an issue with Arch itself, it is for Arch to resolve.

![IMG_20231004_193349](https://github.com/ximion/appstream/assets/64376960/197e8dec-8a63-4204-9e12-a54b1fba6d33)


I tried asking. But, they won't fix it for some reason. I'm guessing too difficult to fix.

**Comment by DOOMMARINE117** [comment]
oh, it first happen right after the first sets of updates right after you first install arch distro. i foundout it was related too appstream.

**Comment by ximion** [comment]
> I tried asking. But, they won't fix it for some reason. I'm guessing too difficult to fix.

Do you have a link to the bug report?
This doesn't look like an issue with AppStream, it simply looks like you don't have any metadata.

**Comment by DOOMMARINE117** [comment]
> > I tried asking. But, they won't fix it for some reason. I'm guessing too difficult to fix.
> 
> Do you have a link to the bug report? This doesn't look like an issue with AppStream, it simply looks like you don't have any metadata.

metadata? oh, that would explain it. sorry for the late reply. was busy today shopping, lol.

where do i find the bug report?

**Comment by ximion** [comment]
> where do i find the bug report?

Didn't you say you reported this issue?

> metadata? oh, that would explain it. 

AppStream does nothing if it doesn't have any metadata available to parse, and that needs to be provided by your distributor or a repository such as FlatHub.

**Comment by DOOMMARINE117** [comment]
> > where do i find the bug report?
> 
> Didn't you say you reported this issue?
> 
> > metadata? oh, that would explain it.
> 
> AppStream does nothing if it doesn't have any metadata available to parse, and that needs to be provided by your distributor or a repository such as FlatHub.

yes, i did. it also seems to be a common issue too as well. many others reported it as well. i did it via discord. others reported it via forums and etc. not many managed to figured it out. 

where on flathub do i find the metadata?

**Comment by ximion** [comment]
> where on flathub do i find the metadata?

If you have Flatpak installed, it is downloaded automatically.

> i was told arch linux devs wont fix appstream no package found error.

Do you have a bug report against Arch for that? I know AppStream works just fine on Arch...
Also, which application is your screenshot from?

**Comment by DOOMMARINE117** [comment]
> > where on flathub do i find the metadata?
> 
> If you have Flatpak installed, it is downloaded automatically.
> 
> > i was told arch linux devs wont fix appstream no package found error.
> 
> Do you have a bug report against Arch for that? I know AppStream works just fine on Arch... Also, which application is your screenshot from?

yeah, i have flatpak installed. 

thats weird it works fine. some reason on mine it doesnt work well. even on the updates when you click on the pacmac manager. when you go to the updates, it glitches out.

**Comment by DOOMMARINE117** [comment]
![IMG_20231005_192024](https://github.com/ximion/appstream/assets/64376960/cf125262-88b0-4be0-9c8c-e2e6f6d8fed6)

**Comment by ximion** [comment]
I still have no idea what the bug is and what the application is that you are trying to run, and which other issue you have reported that was "rejected by Arch".

AppStream is a middleware library that has no GUI and just provides services to other applications. So I don't think your issue is in the right place here...
