### ISSUE TITLE
Component::Kind  is out-of sync with AsComponentKind

### ISSUE THREAD

**Issue by Sodivad** [ximion/appstream#540]
https://github.com/ximion/appstream/commit/bf115d6aaa3e8b7c583c6891f1f827f841429084 reordered AsComponentKind
but did not touch  AppStream::Component. 

This is a problem because internally they are cast into each other causing wrong results in AppStreamQt.

I was wondering if Component::Kind should also be reordered to match or the enum reordering should be undone as it is generally not ABI compatible and causing problems as seen here.

**Comment by ximion** [comment]
Eww, that should not have happened, thank you for noticing and filing this bug report!

**Comment by ximion** [comment]
Eww, that should not have happened, thank you for noticing and filing this bug report! Maybe this should have had some tests on the Qt side...
