### ISSUE TITLE
Don't allow summaries ending with punctuation

### ISSUE THREAD

**Issue by razzeee** [ximion/appstream#542]
While working on the quality guidelines, it was raised, that we should try to check for some of these automatically.

Especially this one https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#no-weird-formatting-1

So not allowing a summary like `My summary.` or `My summary!`, but allowing `My summary` would be a simple start

**Comment by ximion** [comment]
This is already implemented. Check out the `summary-has-dot-suffix`/`name-has-dot-suffix` issue tags. Those are info priority as they are just cosmetic, but if you want to make them fatal, you can either run `appstreamcli` with the `--pedantic` flag, making all info-type issues fatal, or you can selectively make just these tags fatal by passing `--override=summary-has-dot-suffix=warning,name-has-dot-suffix=warning` to `appstreamcli validate`.
