### ISSUE TITLE
Detect screenshot transparency

### ISSUE THREAD

**Issue by razzeee** [ximion/appstream#544]
Hey,

I'm currently looking at our screenshots and the mix of screenshots is kind of unfortunate.

Status quo seems to be:
1. Screenshots have no shadow and basically start at 0,0 (games, full screen apps)
2. Screenshots have shadows and therefore a (semi)transparent border around them (as we recommend in https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#include-window-shadow-and-rounded-corners )

This makes it very hard to mix screenshots and show both cases in a similar size.

Here is an example of a game screenshot https://dl.flathub.org/repo/screenshots/io.jor.bugdom2-stable/1248x702/io.jor.bugdom2-7f1f5de472c36059518ff387c0d5f988.png and  one with shadows https://dl.flathub.org/repo/screenshots/io.github.diegopvlk.Dosage-stable/1248x702/io.github.diegopvlk.Dosage-abf810d4ef91a16c02ff7c12cfaf19f4.png

I think generating some more metadata would be helpful if possible. That way I would know, if it's a game and I need to round the corners trim the screenshot and add some shadow.

Not sure how possible this is and what exactly we need, so let's discuss this. I would think getting metadata for each corner coordinate would be the most flexible solution.

**Comment by Alexander-Wilms** [comment]
Why not require all screenshots to have no shadow? App stores can then add one if so desired.

I don't think people would actually add the pixel coordinates for the window corners of each screenshot.

**Comment by razzeee** [comment]
> Why not require all screenshots to have no shadow? App stores can then add one if so desired.
> 
> I don't think people would actually add the pixel coordinates for the window corners of each screenshot.

Problem is, when you say you want a screenshot of a window you get the shadow, unless it is fullscreen. And if people start doing fullscreen screenshots, the content is too small to be visible at a glance in those screenshots.

The idea was to detect those coordinates, as the boarder should be the only place in a screenshot, that uses transparent pixels.

**Comment by ximion** [comment]
@razzeee What is preventing you from detecting that in the screenshot image (or its thumbnail) itself?

AppStream does have guidelines for screenshots, see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info , but tbh, I think we might just as well give up on that and anything that can not be automatically determined. Nobody will do that work. Changing the screenshot tool behavior is probably the best thing that can be done.

There's also many apps which have multiple windows, or things like https://flathub.org/apps/com.uploadedlobster.peek which just don't fit in any category.

So, I think the easiest thing to do would be to have the software center detect whether the image has an alpha channel, and if it has one, don't draw a shadow, and if it doesn't have one, the do draw a shadow.

**Comment by razzeee** [comment]
That would mean that only flathub benefits from it, as the part I can affect is too far down the pipeline.

And we would also need to layout some stuff differently, according to where the borders are. I can later show some Screenshots of the new tooling in flathub. 

Stuff like peek doesn't pass the validation anyway and wouldn't be something we would try to layout in that way. Still it would be nice to get them into a usable format.

**Comment by Alexander-Wilms** [comment]
> Problem is, when you say you want a screenshot of a window you get the shadow, unless it is fullscreen. And if people start doing fullscreen screenshots, the content is too small to be visible at a glance in those screenshots.

KDE's spectacle just got the option to omit the shadow: https://pointieststick.com/2023/10/27/these-past-2-weeks-in-kde-wayland-color-management-the-desktop-cube-returns-and-optional-shadows-in-spectacle/

Anyway, automating this does sound better than relying on everyone to follow the guidelines.
This seems to work for removing semitransparent shadows:
`convert imagein.png -channel alpha -threshold 80% +channel -trim +repage imageout.png`

![imagein](https://github.com/ximion/appstream/assets/3226457/cd0d004c-3d6e-4265-a4b6-59579c556636)
![imageout](https://github.com/ximion/appstream/assets/3226457/35709fc8-0d4f-4d2f-b4e3-8402c347835b)

**Comment by razzeee** [comment]
Impressed how good this works. Only the last image seems to loose some quality, but that might be me making stuff up.

I think if we have the option, we would even want it without shadows, as every app store can then add the shadows (or whatever) how they like it. The other way around would be harder.

**Comment by Alexander-Wilms** [comment]
Maybe https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info could recommend taking screenshots without shadows and without maximizing the window and explain how to take them.

And additionally, `appstream-compose` could have a flag to remove shadows from screenshots.

Not sure if one would want to check whether the first `convert `command works with all screenshots or if it'd be easier to just submit new screenshots without a shadow upstream if one happens to notice that something looks broken.

**Comment by razzeee** [comment]
> Maybe [freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) could recommend taking screenshots without shadows and without maximizing the window and explain how to take them.

As far as I know, that's not possible on gnome. At least with window selection (which you need for correctly rounded corners)

**Comment by razzeee** [comment]
> One disadvantage I noticed is that rounded corners are no longer antialiased after removing the shadow, though that's not very noticeable if the screenshot is scald down a bit.

Unfortunatly it seems like this is a deal breaker

**Comment by razzeee** [comment]
> So, I think the easiest thing to do would be to have the software center detect whether the image has an alpha channel, and if it has one, don't draw a shadow, and if it doesn't have one, the do draw a shadow.

As far as I can tell now,  it's even worse. As GTK4 seems to have different shadow/transparent borders then GTK3 and probably then KDE or whatever toolkit. Additional to that we have apps without transparency.

So I guess the only way to try to position most screenshots in a nice way, I'll need to detect the amount of transparent pixels from the middle of each border.

**Comment by razzeee** [comment]
Let's close for now, as it's very hard to find a good solution.
