### ISSUE TITLE
Screenshot with xml:lang

### ISSUE THREAD

**Issue by sabriunal** [ximion/appstream#549]
- LC_ALL=C appstreamcli --version: AppStream version: 0.16.2
- OS: Ubuntu 23.10

Hello, when I check the following XML, it appears to be valid. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>com.rafaelmardojai.Blanket</id>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-3.0-or-later</project_license>
  <name>Blanket</name>
  <summary>Listen to ambient sounds</summary>
  <description>
    <p>Improve focus and increase your productivity by listening to different ambient sounds</p>
  </description>
  <url type="homepage">https://github.com/rafaelmardojai/blanket</url>
  <developer_name translatable="no">Rafael Mardojai CM</developer_name>
  <update_contact>email_AT_rafaelmardojai.com</update_contact>
  <content_rating type="oars-1.1" />
  <launchable type="desktop-id">com.rafaelmardojai.Blanket.desktop</launchable>
  <translation type="gettext">blanket</translation>
  <screenshots>
    <screenshot type="default">
      <image type="source">https://raw.githubusercontent.com/rafaelmardojai/blanket/master/brand/screenshot-1.png</image>
    </screenshot>
    <screenshot>
      <image type="source">https://raw.githubusercontent.com/rafaelmardojai/blanket/master/brand/screenshots/ru/screenshot-1-ru.z.png</image>
    </screenshot>
  </screenshots>
</component>

```

LC_ALL=C appstreamcli validate --verbose --explain com.rafaelmardojai.Blanket.metainfo.xml.in 

? Validation was successful: pedantic: 4

According to [Freedesktop Documents](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots), I can specify a screenshot for another language with a slight change, something like this: **image type="source"** to **image type="source" xml:lang="ru"**. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>com.rafaelmardojai.Blanket</id>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-3.0-or-later</project_license>
  <name>Blanket</name>
  <summary>Listen to ambient sounds</summary>
  <description>
    <p>Improve focus and increase your productivity by listening to different ambient sounds</p>
  </description>
  <url type="homepage">https://github.com/rafaelmardojai/blanket</url>
  <developer_name translatable="no">Rafael Mardojai CM</developer_name>
  <update_contact>email_AT_rafaelmardojai.com</update_contact>
  <content_rating type="oars-1.1" />
  <launchable type="desktop-id">com.rafaelmardojai.Blanket.desktop</launchable>
  <translation type="gettext">blanket</translation>
  <screenshots>
    <screenshot type="default">
      <image type="source">https://raw.githubusercontent.com/rafaelmardojai/blanket/master/brand/screenshot-1.png</image>
    </screenshot>
    <screenshot>
      <image type="source" xml:lang="ru">https://raw.githubusercontent.com/rafaelmardojai/blanket/master/brand/screenshots/ru/screenshot-1-ru.z.png</image>
    </screenshot>
  </screenshots>
</component>
```

LC_ALL=C appstreamcli validate --verbose --explain com.rafaelmardojai.Blanket.metainfo.xml.in 

However, I encountered the following error.

> E: com.rafaelmardojai.Blanket:21: screenshot-image-source-missing
> A screenshot must have at least one image of type `source`.
> ? Validation failed: errors: 1, pedantic: 4

**Comment by ximion** [comment]
That is because your screenshot does not have an untranslated source image (without locale) - it must have that in order to be considered valid.

The error could probably be a bit clearer, I think you weren't even the first person to wonder about this...

**Comment by sabriunal** [comment]
In addition to the validation error, I'm curious if this usage is valid, or if there's a recommended way to use localized screenshots. If you could kindly provide an example, that would be greatly appreciated!

**Comment by ximion** [comment]
> I'm curious if this usage is valid

No, that's why you get a validation error ;-) The screenshot localization works just like string localization in that you need to provide the same image, but in a different language.

So, the valid XML for your example would be this:
```xml 
<screenshot type="default">
  <image type="source">https://raw.githubusercontent.com/rafaelmardojai/blanket/master/brand/screenshot-1.png</image>
  <image type="source" xml:lang="ru">https://raw.githubusercontent.com/rafaelmardojai/blanket/master/brand/screenshots/ru/screenshot-1-ru.z.png</image>
  <caption>The default screen (or a better caption, or none)</caption>
</screenshot>
``` 
This assumes of course that the two screenshots show the same thing. You can not add a screenshot that appears only for one locale and is not visible on any others, currently (there always has to be a default, unlocalized/English image in it as well)

**Comment by sabriunal** [comment]
Thank you very much! With this trick, we can enhance the software center screenshots.
