### ISSUE TITLE
[homebrew] cannot find gi-docgen for 1.0.0 release build

### ISSUE THREAD

**Issue by chenrui333** [ximion/appstream#555]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  Build-time dependency gi-docgen found: NO (tried pkgconfig, framework and cmake)
  
  docs/api/meson.build:5:15: ERROR: Dependency "gi-docgen" not found, tried pkgconfig, framework and cmake
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6841704038/job/18602874169
relates to Homebrew/homebrew-core#154003

**Comment by ximion** [comment]
Well, is `gi-docgen` installed and in PATH? ;-)

**Comment by ximion** [comment]
Well, is `gi-docgen` installed and in PATH? ;-)
The project can be found here: https://gitlab.gnome.org/GNOME/gi-docgen
