### ISSUE TITLE
Retry curl operations on error

### ISSUE THREAD

**Issue by bbhtt** [ximion/appstream#557]
Various curl operations in appstream like downloading the screenshot can sometimes fail or timeout during the connect phase due to a slight network snag on the CI or on the target host server.

Usually that error will make a build fail (at least in flathub) and it might be costly to restart the whole build just because say the screenshot validation failed temporarily.

Will it be possible to add a retry mechanism such that it retries on
errors during the connect phase?
 
I think another possible solution would be to make the default timeout of 60s configurable.

**Comment by razzeee** [comment]
If this get's looked at, it might also be worth checking, if a low speed limit has been set. See https://github.com/flatpak/flatpak/pull/5520 as an example implementation.

**Comment by ximion** [comment]
Yeah, we should definitely have both by default :-)
