### ISSUE TITLE
How to build without libzstd

### ISSUE THREAD

**Issue by sulincix** [ximion/appstream#561]
I design minimal distribution. It does not have zstd .

https://github.com/ximion/appstream/commit/d080b17e68ab71cfe0012b5a7e541f1f75dab5da

this commit add zstd dependency. I think we should add disable options.

**Comment by ximion** [comment]
Is zstd really that large? Especially since it is depended on by so much stuff nowadays!
Since it's quite a bit faster, I expect zstd to actually become a non-disableable default, but for now we can temporarily make it optional.
