### ISSUE TITLE
1.0.0: `appstreamcli validate` flags content_attribute intense as wrong

### ISSUE THREAD

**Issue by dvzrv** [ximion/appstream#563]
Hi! :wave: 

I'm currently trying to build fractal 5 for Arch Linux to update the package.
I have started to run the tests as well and ran into a number of issues with `appstreamcli validate`.

It seems the below file fails validation, although according to OARS, this is correct:

```shell
appstreamcli validate --no-net org.gnome.Fractal.metainfo.xml
E: org.gnome.Fractal:172: content-attribute-value-invalid intense

✘ Validation failed: errors: 1, pedantic: 1
```

[org.gnome.Fractal.metainfo.xml.txt](https://github.com/ximion/appstream/files/13474537/org.gnome.Fractal.metainfo.xml.txt)

The problematic section seems to be:

```
  <content_rating type="oars-1.1">
    <content_attribute id="social-chat">intense</content_attribute>
    <content_attribute id="social-audio">intense</content_attribute>
  </content_rating>
```

Do you have any idea what is going wrong here or how I could fix this behavior?
Currently I can only remove the entire section for validation to succeed, or disable that validation altogether.

**Comment by ximion** [comment]
Thank you for the bug report! Looks like this has been broken for a really long time already, and not just for the `social-audio` ID. It probably even would have led to wrong item descriptions in software centers...

I've reviewed these and it's fixed now with the next bugfix release :-)

**Comment by dvzrv** [comment]
Thanks so much for the quick fix! :tada:
