### ISSUE TITLE
How can I solve unknown-tag developer error

### ISSUE THREAD

**Issue by sabriunal** [ximion/appstream#564]
Hello, I encountered an 'unknown-tag' error while attempting to validate metadata. I have tested this with appstream.cli 1.0.0 from Flathub.

```
  <developer id="gnome.org">
    <name>The GNOME Project</name>
  </developer>
```
Source: https://gitlab.gnome.org/GNOME/snapshot/-/blob/main/data/org.gnome.Snapshot.metainfo.xml.in.in?ref_type=heads#L101-103

**flatpak run org.freedesktop.appstream.cli --version**: 1.0.0

```
: @app-id@:101: unknown-tag developer
   Found invalid tag. Non-standard tags should be prefixed with `x-`. AppStream also provides the
   <custom/> tag to add arbitrary custom data to metainfo files. This tag is read by AppStream
   libraries and may be useful instead of defining new custom toplevel or `x-`-prefixed tags if you
   just want to add custom data to a metainfo file.
```

**Comment by sabriunal** [comment]
appstream 0.16.2-1 from Ubuntu 23.10.

Updated version not available yet (https://launchpad.net/ubuntu/+source/appstream)

But I've tested with the flatpak version of appstreamcli from Flathub. Do I also need locale package?

**Comment by sabriunal** [comment]
My mistake. I have an alias to run the command and it seems that I forgot to update the alias. I'm sorry. Thanks.

**Comment by ximion** [comment]
That explains it! Thanks for checking! :-)
