### ISSUE TITLE
Does appstream runtime depend on gperf?

### ISSUE THREAD

**Issue by nanonyme** [ximion/appstream#566]
As part of trying to bring appstream from flatpak Sdk to Platform, we're pulling gperf in as a dependency. I am trying to figure out exactly how and which part of gperf appstream depends on. Can you please help documenting? Is it a library or the executable?

**Comment by nanonyme** [comment]
Also, do appstream libraries or commands depend on gperf?

**Comment by ximion** [comment]
[Gperf](https://www.gnu.org/software/gperf/)  generates C code for [Perfect hash functions](https://en.wikipedia.org/wiki/Perfect_hash_function) which is compiled into AppStream.
There is no library in gperf. AppStream needs it to build only, so you can treat it like you do the Meson build system.
