### ISSUE TITLE
`appstreamcli compose` is no longer writing `developer_name`

### ISSUE THREAD

**Issue by JakobDev** [ximion/appstream#568]
The old `developer_name` tag was replaced with the new `developer` tag in version 1.0 This also means `appstreamcli compose` is no longer writing the `developer_name` tag.

Consider you have the following in your AppStream file:
```xml
<developer_name>Test</developer_name>
```
 `appstreamcli compose`  will convert this to:
```xml
<developer>
    <name>Test</name>
</developer>
```
This means that older versions of appstream can no longer read the developer name, as they don't know about the new tag. You should also write `developer_name` for know to keep it backwards compatible.

**Comment by ximion** [comment]
That is intended and won't be changed. AppStream 1.0 won't generate legacy metadata anymore.

Older versions can read both though, and 1.0 can read `developer_name`, so you should be covered in both directions. Just make sure you're up-to-date on the 0.16.4 stable series as well :-)
