### ISSUE TITLE
How can app handle unrelased release date in metada

### ISSUE THREAD

**Issue by ghost** [ximion/appstream#570]
I've noticed that some app developers use a metadata file to prepare release notes for versions that have not yet been released.

```
      <release version="3.1.0" date="2023-12-XX">
        <description translatable="no">
          <p>This is a minor release of Impression with a few small improvements.</p>
        </description>
      </release>
```

Of course, appstreamcli can't validate these dates.

```
W: @app-id@:68: invalid-iso8601-date 2023-12-XX
   The AppStream specification requires a complete, ISO 8601 date string with at least
   day-granularity to denote dates. Please ensure the date string is valid.
```

Could you offer me a way that developers can use a metadata file to prepare release notes without breaking validation?

**Comment by ximion** [comment]
We can potentially ignore the `date` requirement if the release `type` is `snapshot`, so if that is set, people can just leave out the date and add it once the release is ready...
