### ISSUE TITLE
launchable tag is not mandatory for desktop-applications in spec

### ISSUE THREAD

**Issue by bbhtt** [ximion/appstream#576]
https://github.com/ximion/appstream/commit/ad98bfd8db789c80507e82278d6d766acba4937c#diff-a3371891dafb978899dcc13eea2c3a592e8d04be9e2d1c8b1655ba4585edfaa9R526-R528 made it an error but spec still says "recommended"

https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html#tag-dapp-launchable

This makes compose in flatpak-builder fail.

If launchable is to be made an error for desktop-applications it should be made clear and mandatory in the spec I think.

**Comment by ximion** [comment]
That change you linked only made in an error in some circumstances...
It is so heavily recommended though, that we can probable make it a "must" instead of a "should" in the spec, to clarify. The tools that don't have a launchable intentionally and are desktop-apps are rare anyway (like WINE).

**Comment by bbhtt** [comment]
Yea that seems fine to me.

**Comment by ximion** [comment]
On second thought, making metadata of projects like WINE immediately invalid is also not okay.
But if `compose` can't obtain a valid category from any source, it will reject that component via the `no-valid-category` error. So a component (that has a GUI) should *always* have categories.
Is that somehow not working?

**Comment by bbhtt** [comment]
Yea, that's working. My issue is, it introduces an unexpected failure mode, because a lot of application maintainers aren't aware of compose or the process itself. So all they see is, they had categories in desktop file, but somehow something is not working and the build fails.

Anyways, Flathub made launchable mandatory through an override. That makes the process initially annoying because a lot of apps are missing it (almost every KDE app is missing it, so we had to add mass exceptions for now) but this should help in the long term, imo.

I can understand if you don't want to make the same recommendation in spec to accommodate more component types/applications.

**Comment by ximion** [comment]
> Yea, that's working.

I just tested this here and it worked fine - do you have a testcase for me, maybe?

For this issue, I could leave the wording as-is, but make the tag a validator warning that is overridable. So apps like WINE would have to override it, while everyone else would get it. WINE is special, but after looking for it, I found no other app like Wine. So, 99% of projects would benefit from a missing launchable being a warning, and if we let Wine override this, everyone should be happy...

**Comment by bbhtt** [comment]
> or this issue, I could leave the wording as-is, but make the tag a validator warning that is overridable. ...

Yea seems fine to me.

**Comment by ximion** [comment]
> > or this issue, I could leave the wording as-is, but make the tag a validator warning that is overridable. ...
> 
> Yea seems fine to me.

Actually this is already the case - `desktop-app-launchable-missing` is an error (and that one is emitted if there is no launchable tag and the component-ID also doesn't end with .desktop).
