### ISSUE TITLE
Doc: description of <icon> not consistent

### ISSUE THREAD

**Issue by buhtz** [ximion/appstream#588]
I am aware of to locations with <icon> is described

https://www.freedesktop.org/software/appstream/docs/chap-CatalogData.html#tag-ct-icon

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-icon

Their content is not consistent. e.g. Have a look at the "type" attribute.

**Comment by ximion** [comment]
Well, you are looking at two different data formats - one is shipped by stores like Flathub and distributions (catalog metadata) and the other is shipped by upstream projects (MetaInfo files).
So naturally, there are differences and not everything is allowed everywhere.

**Comment by buhtz** [comment]
I was not aware of that difference. I understand AppStream especially to be designed for not having such a difference.
