### ISSUE TITLE
Language attribute in <p> not working

### ISSUE THREAD

**Issue by buhtz** [ximion/appstream#589]
The doc tells me to put a language attribute in the p tag.
![image](https://github.com/ximion/appstream/assets/11861496/adbca8ac-5541-4272-bc48-2bc38e6584f5)

But appstreamcli validate gives me about it an error:

    app-description-required

It also do not work with `<p lang="en">`.
Only when doing `<p>` it works.

**Comment by ximion** [comment]
You do not need to put `lang="en"` in there, that is implied for the untranslated tag. And an untranslated tag *must* be present.

Usually you do not want to translate this manually anyway, but use e.g. `itstool` or `xgettext` instead.
