### ISSUE TITLE
Doc <description>: Unclear how to create a list

### ISSUE THREAD

**Issue by buhtz** [ximion/appstream#590]
The docu about the <description> tag is unclear to me. How can I create a list?

![image](https://github.com/ximion/appstream/assets/11861496/48d55edf-3cd0-4608-967e-9efd7c5d9bfe)

Not a list
![image](https://github.com/ximion/appstream/assets/11861496/798cf3bd-b4e5-4a89-ae83-31ed38fcbcfe)

**Comment by buhtz** [comment]
I see the problem. Markdown do not work. Got it.
Before that I used real HTML but even this didn't work.

```
</p>
  <ul>
      <li>First item</li>
      <li>Second item</li>
  </ul>
</p>
```

Other then the error of appstreamcli indicates the "ul" is not the problem but having the "ul" inside a "p" is the problem. No matter that this is W3C-valid HTML. Gnome-software and appstreamcli are not able to handle that well.

This works
```
  <ul>
      <li>First item</li>
      <li>Second item</li>
  </ul>
```

**Comment by ximion** [comment]
See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description
There is also an example at https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-example with some further information.

**Comment by ximion** [comment]
> No matter that this is W3C-valid HTML.

AppStream Metadata is neither HTML nor Markdown - the docs even specifically call this out to not expect HTML.

**Comment by buhtz** [comment]
Yes, do not expect HTML. That is why I tried Markdown which even doesn't work.
The doc do not "call" what the user should expect. The section should get rewritten to with this in mind.
But you closed it and it seems you do not treat this as a bug.

It was not a support question but a bug report about the documentation.

**Comment by ximion** [comment]
The documentation is clear - it is a specification though, so it also has to be concise. It is designed for implementers of the spec and as reference.
Apparently you expect a bit more examples, which is what documents like https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html are for, as well as the various pages software stores have made. Maybe you will like those more.
