### ISSUE TITLE
appstreamcli validate fails with an URL returning 302

### ISSUE THREAD

**Issue by heirecka** [ximion/appstream#597]
https://invent.kde.org/games/klickety/-/blob/master/src/org.kde.ksame.appdata.xml?ref_type=heads#L122 contains

`<url type="help">https://docs.kde.org/?application=klickety&amp;branch=stable&amp;path=ksame_mode.html</url>`. 

which appstreamcli validate complains about, although the links works everywhere else:

```
appstreamcli validate src/org.kde.ksame.appdata.xml
org.kde.ksame.appdata.xml
  W: org.kde.ksame.desktop:121: url-not-reachable
       https://docs.kde.org/?application=klickety&branch=stable&path=ksame_mode.html -
       Unexpected status code: 302
```

This happens with klickety's CI build, for example: https://invent.kde.org/games/klickety/-/jobs/1584822

I reported the (apparently) same issue in the past (https://github.com/ximion/appstream/issues/394). While it got fixed, I suspect https://github.com/ximion/appstream/commit/51b97d0f0e44d7fce334be78a0881a7366b03a9a caused it to regress again, at least from a cursory look.

**Comment by ximion** [comment]
Thank you for the report - this was a slightly different issue, but the fix is way better now and should cover all edge cases (hopefully...).

**Comment by heirecka** [comment]
Thanks for the quick fix!
