### ISSUE TITLE
appstream-0.8.4 missing all metadata (on fedora 23)?

### ISSUE THREAD

**Issue by rdieter** [ximion/appstream#6]
Subject says it all, not sure if it's fedora 23 or appstream-0.8.4 (or both) to blame here, but either way, neither muon-discover or appstreamcli seems to find anyting. :(

$ sudo appstreamcli refresh-index --force --verbose
** (appstreamcli:31236): DEBUG: Unable to determine screenshot service for distribution 'Fedora'. Using the Debian services.
** (appstreamcli:31236): DEBUG: Data did not change, no cache refresh needed.
** (appstreamcli:31236): DEBUG: Forcing refresh anyway.
** (appstreamcli:31236): DEBUG: Refreshing AppStream cache
** (appstreamcli:31236): DEBUG: An unknown component was found: webapp
** (appstreamcli:31236): DEBUG: ASXML-WARNING: Invalid component: [Component::devdocs-io.desktop]> name: Devdocs.io | package:  | summary: Easily view and search developer documentation
** (appstreamcli:31236): DEBUG: Removing old rebuild-dir from previous database rebuild.
AppStream cache update completed, but some metadata was ignored due to errors.

$ appstreamcli search kde
No component matching 'kde' found.

I'm hoping the debug output above may give some clues.  I'd really like to ship fedora 23 kde spin using muon, provided we can get it to work.

**Comment by rdieter** [comment]
from irc:

<ximion> &me can|t reproduce
<rdieter> fun
<ximion> rdieter: do you get results when you place the XML in /var/cache/app-info/xmls
<rdieter> copied /usr/share/app-info/xmls/fedora.xml* /var/cache/app-info/xmls/ , no change in behavior as far as I can tell

**Comment by ximion** [comment]
Resolved in https://github.com/ximion/appstream/commit/c09d1c1d6b75035ae617908ddcb81342cfdaad12
Thanks for reporting the issue and helping to debug it!
