### ISSUE TITLE
Creating icons bigger than 128px

### ISSUE THREAD

**Issue by razzeee** [ximion/appstream#602]
It seems like we still get max 128x128 icons with libappstream, even if there are svg sources etc

Is there anything else that needs to be setup to get 256px and others?

**Comment by ximion** [comment]
256px and bigger is simply currently not wired up, as nobody has a need for it (the spec allows it though).
What is the usecase for such gigantic icons in metadata? Having them would drastically increase download size...

**Comment by danirabbit** [comment]
We use 128px icons in AppCenter. Having support for HiDPI icons would be great :)

**Comment by ximion** [comment]
@danirabbit 128x128@2 icons should be generated (which is essentially 256x256px icons) - do you not have them?

**Comment by danirabbit** [comment]
It looks like we don't: http://flatpak.elementary.io/repo/appstream/x86_64/icons/

We're using [Flatpak Builder](https://github.com/flatpak/flatpak-github-actions). Maybe an issue there then?

**Comment by ximion** [comment]
According to the default policy of `appstreamcli compose`, 128x128@2 sized icons should be available as remote-type icons - which means they should be generated by default (see [compose/asc-icon-policy.c#L90](https://github.com/ximion/appstream/blob/main/compose/asc-icon-policy.c#L90)).

Maybe not everything was processed with appstreamcli yet?
Also, I don't think the icon policy can be customized with the CLI utility yet (you'd need to use the C/Python API), so I guess that would be a sensible addition (in case someone ever wants 1024x1024@2 icons...).

**Comment by razzeee** [comment]
The original mockup tobias did https://mastodon.social/@tbernard/111160489118966765 calls for a 256px icon

I do think we get @2 images

**Comment by ximion** [comment]
This would be an insane amount of data - keep in mind, we download those onto every machine...
We could have these ultra-large icons be remote-only though, but then we need to make sure they aren't committed (and of course, local software centers would hit a webserver to download the large icons).

**Comment by razzeee** [comment]
> This would be an insane amount of data - keep in mind, we download those onto every machine...

Screenshots are bigger, but I guess you are saying, that the icons are in the listings and every listing icon get's downloaded (every size?)?

**Comment by ximion** [comment]
I need to have a look at how Flatpak implements this, but for distributions every size is indeed downloaded locally on every machine, so the catalog of applications can be browsed offline and to alleviate privacy concerns.
So there is a huge tradeoff here.

I think Flatpak's implementation is similar, but I'd have to take a look again. AppStream does support fetching icons from remote sources, but that must be made explicit.
Screenshots on the other hand are never downloaded in advance, and only on-demand.

**Comment by ZVNexus** [comment]
> This would be an insane amount of data

Is a 256px icon really taking up that much space though?

Currently on my 4K 32" display 128px looks blurry depending on context, I scale at 150%.

**Comment by ximion** [comment]
> Is a 256px icon really taking up that much space though?

They do if you have 2000 of them (current amount of icons in the Debian archive. Higher resolution ones are "only" 1400, but that's still a lot!). All of them also need to be downloaded all the time (although with binary deltas, that download size can be reduced drastically).

**Comment by razzeee** [comment]
Can this be reopened? 

Talked with designers and we want at least 256 icons and also `@2` scale for those. Ideally we can configure that on our own.

**Comment by razzeee** [comment]
@pwithnall pinging you here as we spoke about this earlier

**Comment by pwithnall** [comment]
> @pwithnall pinging you here as we spoke about this earlier

Some notes about our conversation at GUADEC, for my own future reference:
 - I share Matthias’ concerns about storage/download size if we make larger icon sizes be generated and downloaded by default for all apps
 - One way to mitigate this would be to only generate the larger icon sizes for featured apps, not all apps; I think this fits in with the design, which needs the larger icon sizes for featured app banners
 - At some point, the aggregate storage/bandwidth requirements for providing multiple large icon sizes for each app will outweight the storage/bandwidth requirements for shipping SVG icons instead; at that point, we might want to encourage apps to switch to SVG so that everything is infinitely scalable
 - From a gnome-software perspective, the existing code should handle downloading 256x256 icons already, as long as they are advertised in the appstream

**Comment by razzeee** [comment]
> One way to mitigate this would be to only generate the larger icon sizes for featured apps, not all apps; I think this fits in with the design, which needs the larger icon sizes for featured app banners

On flathubs side, there is a pool of apps affected by this, but it only gets decided after the appstream was already written. We don't yet feed those back into a new appstream and I'm unsure if we even can.
