### ISSUE TITLE
Certain metainfo files are getting composed without any component type in catalogue data

### ISSUE THREAD

**Issue by bbhtt** [ximion/appstream#609]
Some BaseApps on Flathub provide a very minimal metainfo file. BaseApps are usually a bundled group of dependencies for something else and aren't actual apps, more like "tiny runtimes" for a app/group of apps.

Eg. https://raw.githubusercontent.com/flathub/io.qt.qtwebkit.BaseApp/69df83c4f7b36336df220153e7141db6da1cf81e/io.qt.qtwebkit.BaseApp.metainfo.xml

The metainfo has no type set, that's a bug from whoever wrote it, but somehow appstream is also composing them without at least a `type=generic` in catalogue data.

Currently we skip any validation for BaseApps because they aren't actual apps and half of the baseapps do not ship any metainfo file.

But the typeless catalogue data is making the Flathub website backend explode, by introducing a null value in the database table.

Can appstream at least put `type=generic` in them? This used to be the case with appstream-glib. 

I removed a bunch of metainfo files to stop backend from exploding but you can check the older entries of `io.qt.qtwebkit.BaseApp` in https://hub.flathub.org/repo/appstream/x86_64/appstream.xml.gz that were composed by as-glib

**Comment by ximion** [comment]
> Can appstream at least put `type=generic` in them?

It doesn't have to, this is a valid MetaInfo file. The `type` attribute is optional, and in its absence, a `generic` component is assumed.
This is a bug in your parser, not in AppStream.

**Comment by bbhtt** [comment]
> It doesn't have to, this is a valid MetaInfo file. 

That's what it does for a regular application metadata file. So why not here?

**Comment by ximion** [comment]
> > It doesn't have to, this is a valid MetaInfo file.
> 
> That's what it does for a regular application metadata file. So why not here?

Sorry, what? You mean a `type="desktop-application"` component turns into a generic component in composed metadata? That should never happen...

**Comment by bbhtt** [comment]
I seemed to have a loose memory of this application https://github.com/saturneric/GpgFrontend/blob/300b372df756e33dbcf65bbdf0f4bce03e42ec79/resource/appstream/com.bktus.gpgfrontend.appdata.xml#L2-L3 with a composed data of `type=generic` even if it didn't have a type in metainfo file.

**Comment by ximion** [comment]
Yes, but that is how this is supposed to be! A component without `type` **is** a generic component. This has been like this since AppStream was created.

**Comment by ximion** [comment]
> What's the difference between typeless and `type=generic`?

There is none. They are the same.

**Comment by bbhtt** [comment]
> A component without type is a generic component. 

So just to clarify, you are saying appstream differs from as-glib by not putting `type=generic` in the composed catalogue data?

If they are the same,  is there an issue in putting that explicitly in catalogue data?

**Comment by ximion** [comment]
> If they are the same, is there an issue in putting that explicitly in catalogue data?

It's more data added for no reason other than to make a broken parser happy, which is not a good enough reason for me (and in fact, might just break something else if changed).
The appstream-glib parser should parse both variants fine as well, as this has been like this for basically forever.

**Comment by bbhtt** [comment]
The case here never came up before, so nobody thought of handling it. Anyway, thanks. It'll be fixed in the backend one way or the other.

**Comment by ximion** [comment]
It's just a "if nothing else defined, assume `generic`" statement in your parser, so definitely shouldn't be too bad. And then it will be compatible with all AppStream data, no matter the source :-) (well, at least in this particular point ^^).

**Comment by bbhtt** [comment]
Yea, that's what I thought too and was asking questions for that.

**Comment by bbhtt** [comment]
https://github.com/flathub-infra/website/pull/2633 will fix backend
