### ISSUE TITLE
Appstream crashes with a short search

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#61]
```
$ appstreamcli search ka
**
ERROR:/home/apol/devel/frameworks/appstream/src/as-data-pool.c:1024:as_data_pool_search: assertion failed: (terms)
Aborted (core dumped)
```

`as_utils_search_token_valid` returns null if the string is too short. I'd say it's ok to restrict broad searches, but I'd rather limit it from the frontend.

**Comment by ximion** [comment]
Actually, we should IMHO just return everything for short searches, like we did previously (it's a nice way of telling the user "your search is too broad").

**Comment by ximion** [comment]
And fixed - this helps to improve the unit tests for searching :)
