### ISSUE TITLE
Screenshot environment

### ISSUE THREAD

**Issue by CarlSchwan** [ximion/appstream#611]
In https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots

there is an example with `environment="plasma-mobile"`

```
  <screenshot environment="plasma-mobile">
    <caption>The FooBar main window, but on Plasma Mobile</caption>
    <image type="source" width="1600" height="900">https://example.com/foobar/screenshot-1_plasma-mobile.png</image>
  </screenshot>
```

but unfortunately plasma-mobile is not in the authorized styles: https://github.com/ximion/appstream/blob/main/data/desktop-style-ids.txt

**Comment by ximion** [comment]
Yes. So, is this a request to add it to the available styles, or to change the example? ;-)

**Comment by 1Maxnet1** [comment]
> Yes. So, is this a request to add it to the available styles, or to change the example? ;-)

I just stumbled across the vary same issue. I would propose to add plasma-mobile as an environment. Screenshots of the mobile appearance of an application might be very different from what they would look on plasma, so in my opinion it makes sense to add it. Let me know, if you can use a little PR for that :)

**Comment by ximion** [comment]
A PR would be welcome (see [desktop-style-ids.txt](https://github.com/ximion/appstream/blob/main/data/desktop-style-ids.txt)). I guess the "mobile" is not a style, so it should indeed be `plasma-mobile` and not `plasma:mobile` (which would also allow `plasma-mobile:dark` later, I guess).

**Comment by razzeee** [comment]
This can be closed
