### ISSUE TITLE
Add a way to allow custom entries when using compose

### ISSUE THREAD

**Issue by tytan652** [ximion/appstream#613]
`appstreamcli compose` does not seem to provide a way to not strip out custom entries.

For context, Flathub requires [`flathub::manifest`](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#manifest-location) custom entry for direct upload but the compose is done by `flatpak−builder`.

So maybe a way to add `ASC_COMPOSE_FLAG_PROPAGATE_CUSTOM` and a way to set the `custom_allowed` list would be nice addition.

**Comment by ximion** [comment]
Sure! Giving the CLI access to the whitelist shouldn't be difficult at all. It's funny, the `compose` command was originally just thought as a quick way to test catalog composition, and people were supposed to integrate the library in custom tooling instead (via scripts), and now the compose command instead is becoming the primary, fully-features entrypoint.
I guess I should have seen that coming... :-P

**Comment by GeorgesStavracas** [comment]
There's no solution more persistent than a temporary solution :slightly_smiling_face:

**Comment by ximion** [comment]
> There's no solution more persistent than a temporary solution 🙂

Indeed... :wink: 
With this change, you can now select which custom keys will show up in generated output data. If really needed, we could expand it in future to allow everything, but I guess for now this should cover all the usecases that have been raised :-)

Thanks for filing this issue!

**Comment by GeorgesStavracas** [comment]
Thanks @ximion, it was very kind of you to implement it!
