### ISSUE TITLE
Build issue with as-validator.c [-Werror=format-security] format not a string literal and no format arguments

### ISSUE THREAD

**Issue by minlexx** [ximion/appstream#614]
I'm seeing multiple compilation errors like
```
../../src/appstream/src/as-validator.c: In function 'as_validator_check_web_url':
../../src/appstream/src/as-validator.c:411:17: error: format not a string literal and no format arguments [-Werror=format-security]
  411 |                 as_validator_add_issue (validator, node, "url-uses-ftp", url);
      |                 ^~~~~~~~~~~~~~~~~~~~~~
```

* on branch main, appstream version 1.0.3
* os/compiler: Alpine Linux, gcc-13

log with more errors: https://paste.sr.ht/~minlexx/5a020ecde1dfad2c97cc4988fd8b56f0c7e8f965

I had to remove both declarations with `G_GNUC_PRINTF` to make it compile, I'm guessing c3f28ff4668a99e766a710556b4d1e5b5de2bc19 did not help? Where is the issue?

**Comment by ximion** [comment]
Odd - why does the CI work but not Alpine?
I also need to check if the way the function is called is allowed behavior, but it certainly seems like it does not cause any issues (but also maybe there is a better annotation to use...).

**Comment by ximion** [comment]
I'll have a look on the weekend. The compiler is probably right here (and can't know the data is safe...), but I want to have a look why the CI isn't properly catching this on all OSes.
Should be resolved by Sunday though :-)
