### ISSUE TITLE
Developer ID, mismatch between recommended and example

### ISSUE THREAD

**Issue by trixon** [ximion/appstream#618]
Not really sure where to report this but while trying to understand appstream at 
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

I noticed on https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer

> It is recommended to use a reverse-DNS name, like org.gnome

but at the very end of the same page I found
`<developer id="example.org">`

**Comment by ximion** [comment]
You've come to the right place :-)
This issue has already been fixed though via https://github.com/ximion/appstream/commit/f88ec00d1ec9f73b41f4550e5cbb19c8d9c95fec and will show up on the documentations page with the next AppStream release.
