### ISSUE TITLE
docs/meson.build:15:4: ERROR: Problem encountered: Unable to find Docbook XSL stylesheets for man pages

### ISSUE THREAD

**Issue by rubyFeedback** [ximion/appstream#624]
Hey guys,

I am in general compiling stuff from source on my Linux box.

Gimp (https://www.gimp.org/) wants appstream (at the least the latest gimp git clone)
and I have had issues with appstream before, so I thought I should check out the git
sources here, in order to avoid stable-but-never-updated-anymore releases.

The meson build system used by appstream insists on building manpages though:

    docs/meson.build:15:4: ERROR: Problem encountered: Unable to find Docbook XSL stylesheets for man pages

I do not use manpages. I think they are outdated. I tend to look online for help in
general. I never look at local manpages and I don't need them.

I tried various ways to disable them in meson:

            -Dapidocs=false     \
               -Ddocs=false     \
    -Dinstall-docs=false     \
    -Dapidocs=false     \
    -Dstemming=false    

But I am also a meson noob, kind of. GNU configure was easier to use than meson.
I never know which options exist.

I get help from LFS/BLFS but even then I often run into issues:

https://www.linuxfromscratch.org/blfs/view/svn/general/appstream.html

My suggestion is thus: Because manpages are so useless, could they be
disabled by default? Those who would like to have them can compile 
appstream via: -Dmanpages=enabled or whatever random impossible-to-guess
syntax meson is using here. After all a man page should not be REQUIRED
to get software to run. I can use gimp, for example, fine, even without 
manpages, so manpages should be off by default, but an enable-switch
should exist.

(Or I may find out how to use meson properly one day, and tell appstream,
to not build manpages by default, but I always keep on forgetting meson
syntax, so for me the better option would be to have manpages disabled.
I only need appstream itself, due to gimp; I never read or use manpages
either. We are no longer living in the 1980s UNIX world either...)

**Comment by ximion** [comment]
Install [docbook-xsl](https://packages.debian.org/sid/docbook-xsl) or whatever the equivalent is for your distribution (or from scratch via https://github.com/docbook/wiki/wiki/DocBookXslStylesheets
