### ISSUE TITLE
Handle too many branding colors

### ISSUE THREAD

**Issue by razzeee** [ximion/appstream#626]
I'm not sure what to do, but code like this

https://github.com/ryonakano/konbucase/blob/main/data/konbucase.metainfo.xml.in#L35

```
  <branding>
    <color type="primary">#f9c440</color>
    <color type="primary" schema_preference="light">#d48e15</color>
    <color type="primary" schema_preference="dark">#ffe16b</color>
  </branding>
```

Seems to end up in a broken format after being commited to flathub, the repofile shows it as 
```
   <branding>
      <color type="primary">#f9c440</color>
      <color type="primary">#d48e15</color>
      <color type="primary">#ffe16b</color>
    </branding>
```

**Comment by ximion** [comment]
Plain ol' bug. Weird though, this should be covered by tests. I'll have a look!

**Comment by ximion** [comment]
Oh god... This is not a bug! `schema_preference` != `scheme_preference`...
Since this is probably a common typo, I will add a dedicated validator check for this.

**Comment by ximion** [comment]
> So that means if the typo is fixed it will fail on the three definitions or is that a valid thing to do?

It is not, according to the spec. I'll add a check for that too.
