### ISSUE TITLE
Appstreamcli validate error on Fedora

### ISSUE THREAD

**Issue by minosimo** [ximion/appstream#627]
Hello, when I attempt to run `appstreamcli validate /path/to/com.app.metainfo.xml`, I get the error:

> appstreamcli: symbol lookup error: appstreamcli: undefined symbol: as_validator_set_check_urls

This is on Fedora 40, which has
ApPStream CLI 1.0.0
ApPStream library version 1.0.2

I am guessing this is likely an issue with the fedora package? I tried to build from source to compare but got stuck with gobject-introspection-1.0 not recognized as installed.

**Comment by razzeee** [comment]
You probably need to also include your metainfo file

**Comment by minosimo** [comment]
Sure, here it is. 
[ee.ria.qdigidoc4.metainfo.zip](https://github.com/ximion/appstream/files/15077636/ee.ria.qdigidoc4.metainfo.zip)

**Comment by ximion** [comment]
> This is on Fedora 40, which has
> ApPStream CLI 1.0.0
> ApPStream library version 1.0.2

This is wrong, the library version and the CLI version *must* match in this case. The lookup error indicates that you are likely loading an even older version of libappstream from somewhere than 1.0 is...
Please double-check your environment that you have no older version around somewhere (and also check the usual suspects like LD_LIBRARY_PATH & Co.), and if there is none, please report this to Fedora!

**Comment by minosimo** [comment]
Apologies! I did have an older version floating in /usr/local/bin.
