### ISSUE TITLE
news-to-metainfo adds the deprecated developer_name tag

### ISSUE THREAD

**Issue by n-stein** [ximion/appstream#631]
We are using appstreamcli with an xml based metainfo file.

Since 1.0.3 usage of the deprecated `<developer_name>` tag causes validation to fail. We have removed the `<developer_name>` from our metainfo and instead used a `<name>` tag within the `<developer>` block. However, calling `news-to-metainfo` is automatically repopulating the `developer_name` tag so the metainfo again fails validation.

Offending lines:
https://github.com/ximion/appstream/blob/5920761df20e216dc8d5e8791dab45befd593664/src/as-component.c#L5039-L5046

Changing the `<=` to `<` resolves the issue

**Comment by ximion** [comment]
Damn, these kinds of changes always come back to bit you one way or another...

Can you test the patch that resolved this issue and see if that would work for you?

**Comment by n-stein** [comment]
Thanks for the quick turnaround. I confirm that patch 6ed8a98dd921afe3eb42765e49e9f09a46a006bc resolves the issue.
