### ISSUE TITLE
"<summary>" length limit?

### ISSUE THREAD

**Issue by buhtz** [ximion/appstream#648]
Hello,

this is about the [`<summary>`](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-summary) tag.

The docu doesn't tell about a length limit. Is there a length limit but not documented? Or isn't there one?

The background of my question is that the Debian build system tells me the current content is to long. But it doesn't tell me about the limit ([Debian#1078593](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078593)).

![image](https://github.com/user-attachments/assets/e3c7255a-b8f6-4a83-a8cd-cc5bcb515f05)

EDIT: Might this be the line to improve the error message and give more details about the allowed limit?
https://github.com/ximion/appstream/blob/373ecb59cb2701628096ff09b5864f9767c0d949/src/as-validator-issue-tag.h#L529

EDIT2: The limit seems to be 90. Am I right?
https://github.com/ximion/appstream/blob/373ecb59cb2701628096ff09b5864f9767c0d949/src/as-validator.c#L3215

**Comment by buhtz** [comment]
Makes sense but cause to much confusion.
If there is no strict limit on your site don't warn.

Another way would be to make the limit configurable so that "users" like flathub or Debian can add their concrete limit. In my case my Debian package as an AppStream warning and I do take this serious. Ignoring a warning is useless.

Maybe you should give Debian the ability to set a strict character limit for the fields.

But I also recommend again to be more clear in this warning message. Based on your codebase there seems to be a limit. Name that value in the warning message.

**Comment by razzeee** [comment]
> Another way would be to make the limit configurable so that "users" like flathub or Debian can add their concrete limit. 

The flathub warning is designed to be a warning and non fatal. That's no accident.

**Comment by buhtz** [comment]
But please name the limit. Give the users a number in that warning. Otherwise they are not able to fix it.
