### ISSUE TITLE
0.10 doesn't provide screenshot url info

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream#66]
With 0.10, 'appstream-cli get --details' doesn't provide a screenshot url anymore. The data has been extracted with "createScreenshotsStore": false and screenshot urls are available in the app-info xmls.

**Comment by antonio-rojas** [comment]
still not getting screenshot urls with  cef772a, is any other commit required?

**Comment by ximion** [comment]
@antonio-rojas Did you run `appstreamcli refresh --force`? Are you using XML or YAML metadata as source data?

**Comment by antonio-rojas** [comment]
Yes, I ran appstreamcli refresh-cache --force. The metadata is in XML.

**Comment by ximion** [comment]
Hmm, are you *sure* you have the right appstreamcli and the right libappstream?
Because I just tried this here with the Arch metadata and got the expected screenshots...

**Comment by antonio-rojas** [comment]
yes, I just tried git head and still doesn't work

**Comment by ximion** [comment]
Weird...
Can you paste the output of `appstreamcli status`? Also run `appstreamcli dump <component-id>` with a component-ID for a component that has screenshots, and check if the screenshot tags are present in the output.

**Comment by antonio-rojas** [comment]
> appstreamcli status
AppStream Status:
Version: 0.10.1

Distribution metadata:
 /usr/share/app-info
  - XML:  3
  - Iconsets:
     archlinux-arch-core
     archlinux-arch-extra
     archlinux-arch-community

 /var/lib/app-info
  - Empty.

 /var/cache/app-info
  - Empty.

Metainfo files:
  - Found 97 components.
  - Found 81 components in legacy paths.

Summary:
We have information on 985 software components.
-----------------------

appstreamcli dump org.kde.dolphin.desktop doesn't output any screenshot tag.

**Comment by ximion** [comment]
Hmm, strange, I can not reproduce this at all...
Also, these codepaths are all unit-tested now, so this really should work. Does `make test` complete without failure?

**Comment by antonio-rojas** [comment]
Yep, all tests pass. No idea what could be the problem, I even tried regenerating the xmls but it makes no difference.

**Comment by ximion** [comment]
The tests read, write and cache read/write metadata, which is exactly what ascli does as well...
So, I have no idea what could be broken here...
Maybe remove all AppStream libraries you have installed and install the master copy again, to be 100% sure nothing is interfering...

If nothing helps, I will fetch some arch user (maybe @aleixpol ) at Akademy and try to reproduce the issue there.
With the Archlinux metadata on Debian, at least, this problem doesn't happen.

**Comment by antonio-rojas** [comment]
ok found it... it was the old cached data from /var/cache/app-info that was somehow interfering. After wiping that dir and regenerating the cache once again it works. Thanks for the help.

**Comment by ximion** [comment]
Oh, that should not happen - if you run with --force, the old data should be overridden...
But good that it's working now :-)
