### ISSUE TITLE
missing default dependency (librsvg-devel) on Tumbleweed

### ISSUE THREAD

**Issue by PennRobotics** [ximion/appstream#662]
On a mostly freshly installed OpenSUSE Tumbleweed, if I download **kdesrc-build** and then run `kdesrc-build breeze` (which calls `kdesrc-build appstream` eventually) I get a build error from Meson stopping at **appstream**:

```log
 . . .
 . . .
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Run-time dependency cairo found: YES 1.18.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.12
Run-time dependency freetype2 found: YES 26.1.20
Run-time dependency pango found: YES 1.54.0
Run-time dependency fontconfig found: YES 2.15.0
Library m found: YES 
Run-time dependency librsvg-2.0 found: NO (tried pkgconfig and cmake)
 
compose/meson.build:70:21: ERROR: Dependency "librsvg-2.0" not found, tried pkgconfig and cmake
```

From very briefly looking, this package looks optional by design but is not skipped if missing as part of the default installation, causing the error shown.

I could propose several different treatments but don't have a strong recommendation one way or the other:

- Add **librsvg** to the dependencies list in the README
- Change the default for _svg-support_ to _optional_ (I suspect this is NOT the answer!)
- Ask CMake or pkgconfig to check if the package installation for **librsvg** is broken and to please fix
- Tell users that land on this issue to `sudo zypper in librsvg-devel` (and, optionally, close the issue)
- Something else. I'm tired and not thinking clearly.

Thanks, all!

**Comment by ximion** [comment]
This is not an issue we can deal with upstream.
Please raise this with either OpenSUSE or kdesrc-build. They apparently pass `-Dcompose=true` to the AppStream build, which needs rsvg, hence either you or them need to ensure it's available.
