### ISSUE TITLE
[Feature Request] Add ability to modify(or insert if not there) values in existing xml files

### ISSUE THREAD

**Issue by Justinzobel** [ximion/appstream#668]

**Comment by aleixpol** [comment]
This needs far more explanation. Why can't you add information to xml files?

**Comment by Justinzobel** [comment]
appstream-glib was used by Flathub for validating and modifying appstream data in manifests. This is no longer possible as they are moving to appstream.

It had a tool to easily modify values of appstream data e.g. `"appstream-util modify ${FLATPAK_DEST}/share/metainfo/${FLATPAK_ID}.appdata.xml project_license GPL-3.0-or-later"`

**Comment by ximion** [comment]
Why would you want to modify the license, or anything in the MetaInfo file at all? The very purpose of these files is to be the same everywhere for the same version of a software component...

**Comment by Justinzobel** [comment]
Nevermind I guess I'll find another tool.
