### ISSUE TITLE
libxmlb 0.3.20 breaks appstream search

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream#672]
`appstreamcli search` completely stopped working after updating libxmlb to 0.3.20 (doesn't find any matches). Rebuilding appstream doesn't help.

**Comment by ximion** [comment]
Do you know which commit broke this? Kind of sounds like a regression in libxmlb...
You did rebuild the cache with `--force` right? (although an outdated cache should be rebuilt automatically).

**Comment by antonio-rojas** [comment]
Bisected to https://github.com/hughsie/libxmlb/commit/77f7c86c70279d6eecc5437c38a4ad44307b95cd

Rebuilding the cache doesn't help

**Comment by hughsie** [comment]
Okay weird; I can reproduce the failure. What query string does `appstreamcli search` do under the covers?

**Comment by ximion** [comment]
`search` runs a whole bunch of queries... => https://github.com/ximion/appstream/blob/main/src/as-cache.c#L1937
If any of them matches, we should get results...

**Comment by hughsie** [comment]
https://github.com/hughsie/libxmlb/pull/213

**Comment by hughsie** [comment]
aaaand released https://github.com/hughsie/libxmlb/releases/tag/0.3.21 -- thanks @antonio-rojas

**Comment by ximion** [comment]
Awesome @hughsie thank you so much for the quick debugging & fix & release! :heart:

**Comment by sidt4** [comment]
Related bugs. Adding for reference:

- https://bugzilla.redhat.com/show_bug.cgi?id=2318784
- https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2696
