### ISSUE TITLE
Repository icons not installed

### ISSUE THREAD

**Issue by mcrha** [ximion/appstream#679]
Since PackageKit switched to `appstream` (from `libappstream-glib`), the repository-provided icons are not installed with `as_utils_install_metadata_file()` any more,  claiming:

* for `appstream-icons.tar.gz` - `Unable to find valid icon size in icon tarball name.`
* for `appstream-icons.tar` - `Can not process files of this type.` (this comes for example from the RPMFusion)

This leads to the appstream data without proper icons being installed, showing the provided packages in the GUI apps with a fallback icon.

Could you provide some "backward" compatibility, please?

Otherwise the repository providers need to generate the appstream icons in different ways, depending which version (of PackageKit or other appstream repo data consumer) they target, which, in fact, they do not have under their control that much. It means to have different icon files generated in different ways for them, thus currently doubled work.

I mean, do not add more work to the repo providers, please.

**Comment by ximion** [comment]
Hmm, but how should we know the icon size then? The backwards-compatible-but-wrong way would, from reading the older code, likely just be to assume 64x64px.

I changed that, as it at least shouldn't cause any breakage. Let's see if that is enough.

**Comment by mcrha** [comment]
> The backwards-compatible-but-wrong way would, from reading the older code, likely just be to assume 64x64px.

No, the tarball contains subdirectories with the icon sizes. See for example: https://download1.rpmfusion.org/nonfree/fedora/steam/39/x86_64/repodata/appstream-icons.tar
