### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by probonopd** [ximion/appstream#68]
http://www.freedesktop.org/software/appstream/docs/api/html seems to be broken.

```
The requested URL /software/appstream/docs/api/html was not found on this server.
Apache/2.4.10 (Debian) Server at www.freedesktop.org Port 443
```

**Comment by ximion** [comment]
That's simply because they are on https://www.freedesktop.org/software/appstream/docs/api/ - is the link to the docs outdated somewhere?

**Comment by probonopd** [comment]
Just about [everywhere](https://github.com/ximion/appstream/search?utf8=%E2%9C%93&q=http%3A%2F%2Fwww.freedesktop.org%2Fsoftware%2Fappstream%2Fdocs%2Fapi%2Fhtml&type=Code) ;-)

**Comment by ximion** [comment]
I found just two, fixed with https://github.com/ximion/appstream/commit/9f6168914f48897ebe6421a3b61dfe67467cd32c - but adding a compatibility symlink might be a good idea in case some external sites are still referring to the old locations.

**Comment by probonopd** [comment]
Thanks!
