### ISSUE TITLE
Add Unlicense as valid metadata license

### ISSUE THREAD

**Issue by cassidyjames** [ximion/appstream#688]
A project I'm helping get onto Flatpak uses [The Unlicense](https://unlicense.org/) for their entire repo, which is a straightforward copyright-waiving public domain license similar to CC0. I was surprised that it was marked as invalid (before reading the docs). In this case we can probably just mark it as CC0, but it would be convenient to be able to keep the same broad public domain license for the entire project if possible.

Could The Unlicense be added to the supported list, or is there a more specific vetting process for appending valid licenses?

**Comment by ximion** [comment]
The Unlicense has an SPDX ID, https://spdx.org/licenses/Unlicense.html, and is recognized by its ID `Unlicense`.
AppStream also knows about it for an incredibly long time (since version 0.12.11 I think, released in early 2020).

So, just use it :-)

**Comment by cassidyjames** [comment]
@ximion no worries, CC0 seems to be the most equivalent to The Unlicense (they both explicitly waive both copyright and warranty, whereas FDFAP waives the latter but explicitly retains copyright). I am not a lawyer, either—but CC0 seems closest to the same intent as Unlicense. 👍🏻
