### ISSUE TITLE
Fails to compile, GObject introspection scanner was not found

### ISSUE THREAD

**Issue by probonopd** [ximion/appstream#79]
Trying to compile on Ubuntu 16.04:

```
sudo apt install cmake libglib2.0-dev libxml2-dev libyaml-dev gobject-introspection
git clone https://github.com/ximion/appstream.git
cd appstream/
mkdir build
cd build
cmake -DSTEMMING=OFF ..

-- Compiling AppStream version 0.10.2
-- Checking for module 'gobject-introspection-1.0'
--   No package 'gobject-introspection-1.0' found
CMake Error at src/CMakeLists.txt:24 (message):
  GObject introspection scanner was not found! Please install it to continue.
```

Is the __gobject-introspection__ package not the correct one?

**Comment by ximion** [comment]
That is the right package - do you also have `libgirepository1.0-dev` installed?

**Comment by probonopd** [comment]
Thanks for the hint to the Dockerfile. Now I get

```
-- Compiling AppStream version 0.10.2
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SNOWBALL_LIB
    linked by target "appstream" in directory /home/me/appstream/src
```

What is __SNOWBALL_LIB__?

**Comment by ximion** [comment]
Snowball is a stemming-algorithm library. See https://en.wikipedia.org/wiki/Stemming
It is used to improve search results.
Install `libstemmer-dev` to make it available.

This warning shouldn't appear though, unless of course you compiled with stemming support (but then you would have seen a fatal error earlier)

**Comment by probonopd** [comment]
I even called `cmake -DSTEMMING=OFF ..`...

**Comment by ximion** [comment]
Maybe just a fluke. It should work now (especially since the .deb packages compile and I haven't heard of any existing issues on any distribution).
