### ISSUE TITLE
Backport to debian oldstable

### ISSUE THREAD

**Issue by probonopd** [ximion/appstream#88]
Would it be possible to backport the continuous build to something like precise, CentOS 6, or debian oldstable, so that we could point people there? Right now, the `appstreamcli` version coming with distribution is outdated almost all of the time, giving false results ([example](https://github.com/arduino/Arduino/pull/5280)).

By providing a backport, the resulting deb/rpm would be expected to run almost everywhere. I could even make an AppImage for it, bundling it with the required libraries.

**Comment by ximion** [comment]
I can't help with backports to CentOS etc., better ask the distributors about this directly.
Newer AppStream versions also require a relatively new version of GLib, which makes backporting them harder.
Backporting to Debian oldstable is impossible for that reason, only a backport to stable could work (which already ships with a recent enough GLib in backports).
Please file appropriate bugs downstream, there is nothing we can do about this in the upstream project.
