### ISSUE TITLE
AppStreamQt: Do not break source compatibility in minor releases

### ISSUE THREAD

**Issue by lbeltrame** [ximion/appstream#95]
This is a **major** pain point for Linux distributions: in openSUSE, we had a bunch of KDE things not building properly because of source incompatibilities in a minor release (including but not limited to CMake files changing names, new includes, etc...).

Please bump the major version if there are API/SIC changes, or at least provide a migration path.

**Comment by ximion** [comment]
Not a bug and the version number is bumped on API changes. Furthermore, the SONAME is bumped on ABI changes, which makes this really easy to discover and to test, as well as to switch back to older versions.

As far as the Qt version of the library is concerned, all KDE components using it (mainly Discover) have releases which work with both APIs and ABIs, the exception being current master which has all compatibility glue removed.
Furthermore, this change happened at the beginning of November already and was clearly announced in the NEWS file, so any distributor should have noticed it.

The overall version number of AppStream follows the spec version, and not the library versions (which only very rarely break ABI anyway).
