### ISSUE TITLE
Content rating key

### ISSUE THREAD

**Issue by tintou** [ximion/appstream#98]
It would be nice to provide a way for applications to declare that they are providing content not suitable for all kind of audience.
For reference, the [PEGI specification](http://www.pegi.info/en/index/id/33/) contains those keys :
 * Bad language
 * Discrimination
 * Drugs
 * Fear
 * Gambling
 * Sex
 * Violence
 * Online Gameplay

**Comment by ximion** [comment]
@hughsie Do you want to submit what you came up with in that regard? I think adding it would make sense.

**Comment by hughsie** [comment]
There is lots of research and background reading on my blog (e.g. https://blogs.gnome.org/hughsie/2016/03/07/age-ratings-in-gnome-software-introducing-oars/ ) but the culmination of the work is OARS which is being used by about 40-50 projects at the moment. You can gernerate metadata using https://odrs.gnome.org/oars for your game or application and the rating and break-down is shown in gnome-software.

OARS is WIP (and I'm working with other media and distribution companies behind the scenes) but I think it makes sense to standardize the AppStream tags if we didn't already do that. I don't think it makes sense to standardize the content_attribute id's, as this will be different for OARS-1.0 and any extension specifications we come up with in the future.

**Comment by ximion** [comment]
Will be added for the 0.11 revision, I think - since we discussed this on the ML a while back, I think adding it will be really easy, since all controversial stuff was resolved back then.
